// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jvm.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//合约对象信息
type JVMContractObject struct {
	Addr                 string            `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Data                 *JVMContractData  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	State                *JVMContractState `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JVMContractObject) Reset()         { *m = JVMContractObject{} }
func (m *JVMContractObject) String() string { return proto.CompactTextString(m) }
func (*JVMContractObject) ProtoMessage()    {}
func (*JVMContractObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{0}
}

func (m *JVMContractObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMContractObject.Unmarshal(m, b)
}
func (m *JVMContractObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMContractObject.Marshal(b, m, deterministic)
}
func (m *JVMContractObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMContractObject.Merge(m, src)
}
func (m *JVMContractObject) XXX_Size() int {
	return xxx_messageInfo_JVMContractObject.Size(m)
}
func (m *JVMContractObject) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMContractObject.DiscardUnknown(m)
}

var xxx_messageInfo_JVMContractObject proto.InternalMessageInfo

func (m *JVMContractObject) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *JVMContractObject) GetData() *JVMContractData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *JVMContractObject) GetState() *JVMContractState {
	if m != nil {
		return m.State
	}
	return nil
}

// 存放合约固定数据
type JVMContractData struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	Code                 []byte   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	CodeHash             []byte   `protobuf:"bytes,6,opt,name=codeHash,proto3" json:"codeHash,omitempty"`
	Abi                  []byte   `protobuf:"bytes,7,opt,name=abi,proto3" json:"abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JVMContractData) Reset()         { *m = JVMContractData{} }
func (m *JVMContractData) String() string { return proto.CompactTextString(m) }
func (*JVMContractData) ProtoMessage()    {}
func (*JVMContractData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{1}
}

func (m *JVMContractData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMContractData.Unmarshal(m, b)
}
func (m *JVMContractData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMContractData.Marshal(b, m, deterministic)
}
func (m *JVMContractData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMContractData.Merge(m, src)
}
func (m *JVMContractData) XXX_Size() int {
	return xxx_messageInfo_JVMContractData.Size(m)
}
func (m *JVMContractData) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMContractData.DiscardUnknown(m)
}

var xxx_messageInfo_JVMContractData proto.InternalMessageInfo

func (m *JVMContractData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *JVMContractData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JVMContractData) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *JVMContractData) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *JVMContractData) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *JVMContractData) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

type LogJVMContractData struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	CodeHash             string   `protobuf:"bytes,4,opt,name=codeHash,proto3" json:"codeHash,omitempty"`
	AbiHash              string   `protobuf:"bytes,5,opt,name=abiHash,proto3" json:"abiHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogJVMContractData) Reset()         { *m = LogJVMContractData{} }
func (m *LogJVMContractData) String() string { return proto.CompactTextString(m) }
func (*LogJVMContractData) ProtoMessage()    {}
func (*LogJVMContractData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{2}
}

func (m *LogJVMContractData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogJVMContractData.Unmarshal(m, b)
}
func (m *LogJVMContractData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogJVMContractData.Marshal(b, m, deterministic)
}
func (m *LogJVMContractData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogJVMContractData.Merge(m, src)
}
func (m *LogJVMContractData) XXX_Size() int {
	return xxx_messageInfo_LogJVMContractData.Size(m)
}
func (m *LogJVMContractData) XXX_DiscardUnknown() {
	xxx_messageInfo_LogJVMContractData.DiscardUnknown(m)
}

var xxx_messageInfo_LogJVMContractData proto.InternalMessageInfo

func (m *LogJVMContractData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *LogJVMContractData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogJVMContractData) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *LogJVMContractData) GetCodeHash() string {
	if m != nil {
		return m.CodeHash
	}
	return ""
}

func (m *LogJVMContractData) GetAbiHash() string {
	if m != nil {
		return m.AbiHash
	}
	return ""
}

// 存放合约变化数据
type JVMContractState struct {
	Nonce                uint64            `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Suicided             bool              `protobuf:"varint,2,opt,name=suicided,proto3" json:"suicided,omitempty"`
	Storage              map[string][]byte `protobuf:"bytes,3,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JVMContractState) Reset()         { *m = JVMContractState{} }
func (m *JVMContractState) String() string { return proto.CompactTextString(m) }
func (*JVMContractState) ProtoMessage()    {}
func (*JVMContractState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{3}
}

func (m *JVMContractState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMContractState.Unmarshal(m, b)
}
func (m *JVMContractState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMContractState.Marshal(b, m, deterministic)
}
func (m *JVMContractState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMContractState.Merge(m, src)
}
func (m *JVMContractState) XXX_Size() int {
	return xxx_messageInfo_JVMContractState.Size(m)
}
func (m *JVMContractState) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMContractState.DiscardUnknown(m)
}

var xxx_messageInfo_JVMContractState proto.InternalMessageInfo

func (m *JVMContractState) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *JVMContractState) GetSuicided() bool {
	if m != nil {
		return m.Suicided
	}
	return false
}

func (m *JVMContractState) GetStorage() map[string][]byte {
	if m != nil {
		return m.Storage
	}
	return nil
}

type JVMContractAction struct {
	// Types that are valid to be assigned to Value:
	//	*JVMContractAction_CreateJvmContract
	//	*JVMContractAction_CallJvmContract
	//	*JVMContractAction_UpdateJvmContract
	Value                isJVMContractAction_Value `protobuf_oneof:"value"`
	Ty                   int32                     `protobuf:"varint,4,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *JVMContractAction) Reset()         { *m = JVMContractAction{} }
func (m *JVMContractAction) String() string { return proto.CompactTextString(m) }
func (*JVMContractAction) ProtoMessage()    {}
func (*JVMContractAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{4}
}

func (m *JVMContractAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMContractAction.Unmarshal(m, b)
}
func (m *JVMContractAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMContractAction.Marshal(b, m, deterministic)
}
func (m *JVMContractAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMContractAction.Merge(m, src)
}
func (m *JVMContractAction) XXX_Size() int {
	return xxx_messageInfo_JVMContractAction.Size(m)
}
func (m *JVMContractAction) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMContractAction.DiscardUnknown(m)
}

var xxx_messageInfo_JVMContractAction proto.InternalMessageInfo

type isJVMContractAction_Value interface {
	isJVMContractAction_Value()
}

type JVMContractAction_CreateJvmContract struct {
	CreateJvmContract *CreateJvmContract `protobuf:"bytes,1,opt,name=createJvmContract,proto3,oneof"`
}

type JVMContractAction_CallJvmContract struct {
	CallJvmContract *CallJvmContract `protobuf:"bytes,2,opt,name=callJvmContract,proto3,oneof"`
}

type JVMContractAction_UpdateJvmContract struct {
	UpdateJvmContract *UpdateJvmContract `protobuf:"bytes,3,opt,name=updateJvmContract,proto3,oneof"`
}

func (*JVMContractAction_CreateJvmContract) isJVMContractAction_Value() {}

func (*JVMContractAction_CallJvmContract) isJVMContractAction_Value() {}

func (*JVMContractAction_UpdateJvmContract) isJVMContractAction_Value() {}

func (m *JVMContractAction) GetValue() isJVMContractAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *JVMContractAction) GetCreateJvmContract() *CreateJvmContract {
	if x, ok := m.GetValue().(*JVMContractAction_CreateJvmContract); ok {
		return x.CreateJvmContract
	}
	return nil
}

func (m *JVMContractAction) GetCallJvmContract() *CallJvmContract {
	if x, ok := m.GetValue().(*JVMContractAction_CallJvmContract); ok {
		return x.CallJvmContract
	}
	return nil
}

func (m *JVMContractAction) GetUpdateJvmContract() *UpdateJvmContract {
	if x, ok := m.GetValue().(*JVMContractAction_UpdateJvmContract); ok {
		return x.UpdateJvmContract
	}
	return nil
}

func (m *JVMContractAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*JVMContractAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*JVMContractAction_CreateJvmContract)(nil),
		(*JVMContractAction_CallJvmContract)(nil),
		(*JVMContractAction_UpdateJvmContract)(nil),
	}
}

// 创建JVM合约
type CreateJvmContract struct {
	// 合约数据
	Code []byte `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// abi数据
	Abi string `protobuf:"bytes,4,opt,name=abi,proto3" json:"abi,omitempty"`
	// 用户自定义Jvm合约名字，必须是user.Jvm.xxx的风格，且xxx由a-z，0-9组成的4-16字符长度组成
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// 交易备注
	Note                 string   `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJvmContract) Reset()         { *m = CreateJvmContract{} }
func (m *CreateJvmContract) String() string { return proto.CompactTextString(m) }
func (*CreateJvmContract) ProtoMessage()    {}
func (*CreateJvmContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{5}
}

func (m *CreateJvmContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJvmContract.Unmarshal(m, b)
}
func (m *CreateJvmContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJvmContract.Marshal(b, m, deterministic)
}
func (m *CreateJvmContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJvmContract.Merge(m, src)
}
func (m *CreateJvmContract) XXX_Size() int {
	return xxx_messageInfo_CreateJvmContract.Size(m)
}
func (m *CreateJvmContract) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJvmContract.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJvmContract proto.InternalMessageInfo

func (m *CreateJvmContract) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreateJvmContract) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *CreateJvmContract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateJvmContract) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 调用Jvm合约
type CallJvmContract struct {
	//合约名称
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	//执行参数
	ActionData []string `protobuf:"bytes,2,rep,name=actionData,proto3" json:"actionData,omitempty"`
	//手续费
	Fee int64 `protobuf:"varint,3,opt,name=Fee,proto3" json:"Fee,omitempty"`
	// 交易备注
	Note                 string   `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallJvmContract) Reset()         { *m = CallJvmContract{} }
func (m *CallJvmContract) String() string { return proto.CompactTextString(m) }
func (*CallJvmContract) ProtoMessage()    {}
func (*CallJvmContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{6}
}

func (m *CallJvmContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallJvmContract.Unmarshal(m, b)
}
func (m *CallJvmContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallJvmContract.Marshal(b, m, deterministic)
}
func (m *CallJvmContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallJvmContract.Merge(m, src)
}
func (m *CallJvmContract) XXX_Size() int {
	return xxx_messageInfo_CallJvmContract.Size(m)
}
func (m *CallJvmContract) XXX_DiscardUnknown() {
	xxx_messageInfo_CallJvmContract.DiscardUnknown(m)
}

var xxx_messageInfo_CallJvmContract proto.InternalMessageInfo

func (m *CallJvmContract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CallJvmContract) GetActionData() []string {
	if m != nil {
		return m.ActionData
	}
	return nil
}

func (m *CallJvmContract) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *CallJvmContract) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 更新Jvm合约
type UpdateJvmContract struct {
	// 合约数据
	Code []byte `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// abi数据
	Abi string `protobuf:"bytes,4,opt,name=abi,proto3" json:"abi,omitempty"`
	// 用户自定义Jvm合约名字，必须是user.Jvm.xxx的风格，且xxx由a-z，0-9组成的4-16字符长度组成
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// 交易备注
	Note                 string   `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJvmContract) Reset()         { *m = UpdateJvmContract{} }
func (m *UpdateJvmContract) String() string { return proto.CompactTextString(m) }
func (*UpdateJvmContract) ProtoMessage()    {}
func (*UpdateJvmContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{7}
}

func (m *UpdateJvmContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJvmContract.Unmarshal(m, b)
}
func (m *UpdateJvmContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJvmContract.Marshal(b, m, deterministic)
}
func (m *UpdateJvmContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJvmContract.Merge(m, src)
}
func (m *UpdateJvmContract) XXX_Size() int {
	return xxx_messageInfo_UpdateJvmContract.Size(m)
}
func (m *UpdateJvmContract) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJvmContract.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJvmContract proto.InternalMessageInfo

func (m *UpdateJvmContract) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *UpdateJvmContract) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *UpdateJvmContract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateJvmContract) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 存放本地数据库的数据
type ReceiptLocalData struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CurValue             []byte   `protobuf:"bytes,2,opt,name=curValue,proto3" json:"curValue,omitempty"`
	PreValue             []byte   `protobuf:"bytes,3,opt,name=preValue,proto3" json:"preValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptLocalData) Reset()         { *m = ReceiptLocalData{} }
func (m *ReceiptLocalData) String() string { return proto.CompactTextString(m) }
func (*ReceiptLocalData) ProtoMessage()    {}
func (*ReceiptLocalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{8}
}

func (m *ReceiptLocalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptLocalData.Unmarshal(m, b)
}
func (m *ReceiptLocalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptLocalData.Marshal(b, m, deterministic)
}
func (m *ReceiptLocalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptLocalData.Merge(m, src)
}
func (m *ReceiptLocalData) XXX_Size() int {
	return xxx_messageInfo_ReceiptLocalData.Size(m)
}
func (m *ReceiptLocalData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptLocalData.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptLocalData proto.InternalMessageInfo

func (m *ReceiptLocalData) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ReceiptLocalData) GetCurValue() []byte {
	if m != nil {
		return m.CurValue
	}
	return nil
}

func (m *ReceiptLocalData) GetPreValue() []byte {
	if m != nil {
		return m.PreValue
	}
	return nil
}

// 合约创建/调用日志
type ReceiptJVMContract struct {
	Caller               string   `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	ContractName         string   `protobuf:"bytes,2,opt,name=contractName,proto3" json:"contractName,omitempty"`
	ContractAddr         string   `protobuf:"bytes,3,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptJVMContract) Reset()         { *m = ReceiptJVMContract{} }
func (m *ReceiptJVMContract) String() string { return proto.CompactTextString(m) }
func (*ReceiptJVMContract) ProtoMessage()    {}
func (*ReceiptJVMContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{9}
}

func (m *ReceiptJVMContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptJVMContract.Unmarshal(m, b)
}
func (m *ReceiptJVMContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptJVMContract.Marshal(b, m, deterministic)
}
func (m *ReceiptJVMContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptJVMContract.Merge(m, src)
}
func (m *ReceiptJVMContract) XXX_Size() int {
	return xxx_messageInfo_ReceiptJVMContract.Size(m)
}
func (m *ReceiptJVMContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptJVMContract.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptJVMContract proto.InternalMessageInfo

func (m *ReceiptJVMContract) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *ReceiptJVMContract) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ReceiptJVMContract) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

// 用于保存JVM只能合约中的状态数据变更
type JVMStateChangeItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PreValue             []byte   `protobuf:"bytes,2,opt,name=preValue,proto3" json:"preValue,omitempty"`
	CurrentValue         []byte   `protobuf:"bytes,3,opt,name=currentValue,proto3" json:"currentValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JVMStateChangeItem) Reset()         { *m = JVMStateChangeItem{} }
func (m *JVMStateChangeItem) String() string { return proto.CompactTextString(m) }
func (*JVMStateChangeItem) ProtoMessage()    {}
func (*JVMStateChangeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{10}
}

func (m *JVMStateChangeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMStateChangeItem.Unmarshal(m, b)
}
func (m *JVMStateChangeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMStateChangeItem.Marshal(b, m, deterministic)
}
func (m *JVMStateChangeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMStateChangeItem.Merge(m, src)
}
func (m *JVMStateChangeItem) XXX_Size() int {
	return xxx_messageInfo_JVMStateChangeItem.Size(m)
}
func (m *JVMStateChangeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMStateChangeItem.DiscardUnknown(m)
}

var xxx_messageInfo_JVMStateChangeItem proto.InternalMessageInfo

func (m *JVMStateChangeItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *JVMStateChangeItem) GetPreValue() []byte {
	if m != nil {
		return m.PreValue
	}
	return nil
}

func (m *JVMStateChangeItem) GetCurrentValue() []byte {
	if m != nil {
		return m.CurrentValue
	}
	return nil
}

type CheckJVMContractNameReq struct {
	JvmContractName      string   `protobuf:"bytes,1,opt,name=JvmContractName,proto3" json:"JvmContractName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckJVMContractNameReq) Reset()         { *m = CheckJVMContractNameReq{} }
func (m *CheckJVMContractNameReq) String() string { return proto.CompactTextString(m) }
func (*CheckJVMContractNameReq) ProtoMessage()    {}
func (*CheckJVMContractNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{11}
}

func (m *CheckJVMContractNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckJVMContractNameReq.Unmarshal(m, b)
}
func (m *CheckJVMContractNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckJVMContractNameReq.Marshal(b, m, deterministic)
}
func (m *CheckJVMContractNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckJVMContractNameReq.Merge(m, src)
}
func (m *CheckJVMContractNameReq) XXX_Size() int {
	return xxx_messageInfo_CheckJVMContractNameReq.Size(m)
}
func (m *CheckJVMContractNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckJVMContractNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckJVMContractNameReq proto.InternalMessageInfo

func (m *CheckJVMContractNameReq) GetJvmContractName() string {
	if m != nil {
		return m.JvmContractName
	}
	return ""
}

type CheckJVMAddrResp struct {
	ExistAlready         bool     `protobuf:"varint,1,opt,name=existAlready,proto3" json:"existAlready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckJVMAddrResp) Reset()         { *m = CheckJVMAddrResp{} }
func (m *CheckJVMAddrResp) String() string { return proto.CompactTextString(m) }
func (*CheckJVMAddrResp) ProtoMessage()    {}
func (*CheckJVMAddrResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{12}
}

func (m *CheckJVMAddrResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckJVMAddrResp.Unmarshal(m, b)
}
func (m *CheckJVMAddrResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckJVMAddrResp.Marshal(b, m, deterministic)
}
func (m *CheckJVMAddrResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckJVMAddrResp.Merge(m, src)
}
func (m *CheckJVMAddrResp) XXX_Size() int {
	return xxx_messageInfo_CheckJVMAddrResp.Size(m)
}
func (m *CheckJVMAddrResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckJVMAddrResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckJVMAddrResp proto.InternalMessageInfo

func (m *CheckJVMAddrResp) GetExistAlready() bool {
	if m != nil {
		return m.ExistAlready
	}
	return false
}

type JVMDebugReq struct {
	// 0 query, 1 set, -1 clear
	Optype               int32    `protobuf:"varint,1,opt,name=optype,proto3" json:"optype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JVMDebugReq) Reset()         { *m = JVMDebugReq{} }
func (m *JVMDebugReq) String() string { return proto.CompactTextString(m) }
func (*JVMDebugReq) ProtoMessage()    {}
func (*JVMDebugReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{13}
}

func (m *JVMDebugReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMDebugReq.Unmarshal(m, b)
}
func (m *JVMDebugReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMDebugReq.Marshal(b, m, deterministic)
}
func (m *JVMDebugReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMDebugReq.Merge(m, src)
}
func (m *JVMDebugReq) XXX_Size() int {
	return xxx_messageInfo_JVMDebugReq.Size(m)
}
func (m *JVMDebugReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMDebugReq.DiscardUnknown(m)
}

var xxx_messageInfo_JVMDebugReq proto.InternalMessageInfo

func (m *JVMDebugReq) GetOptype() int32 {
	if m != nil {
		return m.Optype
	}
	return 0
}

type JVMDebugResp struct {
	DebugStatus          string   `protobuf:"bytes,1,opt,name=debugStatus,proto3" json:"debugStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JVMDebugResp) Reset()         { *m = JVMDebugResp{} }
func (m *JVMDebugResp) String() string { return proto.CompactTextString(m) }
func (*JVMDebugResp) ProtoMessage()    {}
func (*JVMDebugResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{14}
}

func (m *JVMDebugResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMDebugResp.Unmarshal(m, b)
}
func (m *JVMDebugResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMDebugResp.Marshal(b, m, deterministic)
}
func (m *JVMDebugResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMDebugResp.Merge(m, src)
}
func (m *JVMDebugResp) XXX_Size() int {
	return xxx_messageInfo_JVMDebugResp.Size(m)
}
func (m *JVMDebugResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMDebugResp.DiscardUnknown(m)
}

var xxx_messageInfo_JVMDebugResp proto.InternalMessageInfo

func (m *JVMDebugResp) GetDebugStatus() string {
	if m != nil {
		return m.DebugStatus
	}
	return ""
}

type JVMGetAbiResp struct {
	Abi                  []byte   `protobuf:"bytes,1,opt,name=abi,proto3" json:"abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JVMGetAbiResp) Reset()         { *m = JVMGetAbiResp{} }
func (m *JVMGetAbiResp) String() string { return proto.CompactTextString(m) }
func (*JVMGetAbiResp) ProtoMessage()    {}
func (*JVMGetAbiResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{15}
}

func (m *JVMGetAbiResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMGetAbiResp.Unmarshal(m, b)
}
func (m *JVMGetAbiResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMGetAbiResp.Marshal(b, m, deterministic)
}
func (m *JVMGetAbiResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMGetAbiResp.Merge(m, src)
}
func (m *JVMGetAbiResp) XXX_Size() int {
	return xxx_messageInfo_JVMGetAbiResp.Size(m)
}
func (m *JVMGetAbiResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMGetAbiResp.DiscardUnknown(m)
}

var xxx_messageInfo_JVMGetAbiResp proto.InternalMessageInfo

func (m *JVMGetAbiResp) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

type JVMQueryReq struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Para                 []string `protobuf:"bytes,2,rep,name=para,proto3" json:"para,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JVMQueryReq) Reset()         { *m = JVMQueryReq{} }
func (m *JVMQueryReq) String() string { return proto.CompactTextString(m) }
func (*JVMQueryReq) ProtoMessage()    {}
func (*JVMQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{16}
}

func (m *JVMQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMQueryReq.Unmarshal(m, b)
}
func (m *JVMQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMQueryReq.Marshal(b, m, deterministic)
}
func (m *JVMQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMQueryReq.Merge(m, src)
}
func (m *JVMQueryReq) XXX_Size() int {
	return xxx_messageInfo_JVMQueryReq.Size(m)
}
func (m *JVMQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_JVMQueryReq proto.InternalMessageInfo

func (m *JVMQueryReq) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *JVMQueryReq) GetPara() []string {
	if m != nil {
		return m.Para
	}
	return nil
}

type JVMQueryResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result               []string `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JVMQueryResponse) Reset()         { *m = JVMQueryResponse{} }
func (m *JVMQueryResponse) String() string { return proto.CompactTextString(m) }
func (*JVMQueryResponse) ProtoMessage()    {}
func (*JVMQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{17}
}

func (m *JVMQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMQueryResponse.Unmarshal(m, b)
}
func (m *JVMQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMQueryResponse.Marshal(b, m, deterministic)
}
func (m *JVMQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMQueryResponse.Merge(m, src)
}
func (m *JVMQueryResponse) XXX_Size() int {
	return xxx_messageInfo_JVMQueryResponse.Size(m)
}
func (m *JVMQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JVMQueryResponse proto.InternalMessageInfo

func (m *JVMQueryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *JVMQueryResponse) GetResult() []string {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateContractReq struct {
	// abi字符串
	Abi string `protobuf:"bytes,1,opt,name=Abi,proto3" json:"Abi,omitempty"`
	// 合约别名，方便识别
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// 交易备注
	Note string `protobuf:"bytes,3,opt,name=Note,proto3" json:"Note,omitempty"`
	// 合约字节码
	Code []byte `protobuf:"bytes,4,opt,name=Code,proto3" json:"Code,omitempty"`
	// Fee 交易手续费
	Fee                  int64    `protobuf:"varint,5,opt,name=Fee,proto3" json:"Fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContractReq) Reset()         { *m = CreateContractReq{} }
func (m *CreateContractReq) String() string { return proto.CompactTextString(m) }
func (*CreateContractReq) ProtoMessage()    {}
func (*CreateContractReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{18}
}

func (m *CreateContractReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContractReq.Unmarshal(m, b)
}
func (m *CreateContractReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContractReq.Marshal(b, m, deterministic)
}
func (m *CreateContractReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContractReq.Merge(m, src)
}
func (m *CreateContractReq) XXX_Size() int {
	return xxx_messageInfo_CreateContractReq.Size(m)
}
func (m *CreateContractReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContractReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContractReq proto.InternalMessageInfo

func (m *CreateContractReq) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *CreateContractReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateContractReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *CreateContractReq) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreateContractReq) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type QueryCallContractReq struct {
	// 合约别名，方便识别
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 交易备注
	Note                 string   `protobuf:"bytes,2,opt,name=Note,proto3" json:"Note,omitempty"`
	ActionName           string   `protobuf:"bytes,3,opt,name=ActionName,proto3" json:"ActionName,omitempty"`
	ParaData             []string `protobuf:"bytes,4,rep,name=ParaData,proto3" json:"ParaData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCallContractReq) Reset()         { *m = QueryCallContractReq{} }
func (m *QueryCallContractReq) String() string { return proto.CompactTextString(m) }
func (*QueryCallContractReq) ProtoMessage()    {}
func (*QueryCallContractReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{19}
}

func (m *QueryCallContractReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCallContractReq.Unmarshal(m, b)
}
func (m *QueryCallContractReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCallContractReq.Marshal(b, m, deterministic)
}
func (m *QueryCallContractReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCallContractReq.Merge(m, src)
}
func (m *QueryCallContractReq) XXX_Size() int {
	return xxx_messageInfo_QueryCallContractReq.Size(m)
}
func (m *QueryCallContractReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCallContractReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCallContractReq proto.InternalMessageInfo

func (m *QueryCallContractReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueryCallContractReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *QueryCallContractReq) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *QueryCallContractReq) GetParaData() []string {
	if m != nil {
		return m.ParaData
	}
	return nil
}

type UpdateContractReq struct {
	// abi字符串
	Abi string `protobuf:"bytes,1,opt,name=Abi,proto3" json:"Abi,omitempty"`
	// 合约别名，方便识别
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// 交易备注
	Note string `protobuf:"bytes,3,opt,name=Note,proto3" json:"Note,omitempty"`
	// 合约字节码
	Code []byte `protobuf:"bytes,4,opt,name=Code,proto3" json:"Code,omitempty"`
	// Fee 交易手续费
	Fee                  int64    `protobuf:"varint,5,opt,name=Fee,proto3" json:"Fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContractReq) Reset()         { *m = UpdateContractReq{} }
func (m *UpdateContractReq) String() string { return proto.CompactTextString(m) }
func (*UpdateContractReq) ProtoMessage()    {}
func (*UpdateContractReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{20}
}

func (m *UpdateContractReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContractReq.Unmarshal(m, b)
}
func (m *UpdateContractReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContractReq.Marshal(b, m, deterministic)
}
func (m *UpdateContractReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContractReq.Merge(m, src)
}
func (m *UpdateContractReq) XXX_Size() int {
	return xxx_messageInfo_UpdateContractReq.Size(m)
}
func (m *UpdateContractReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContractReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContractReq proto.InternalMessageInfo

func (m *UpdateContractReq) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *UpdateContractReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateContractReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *UpdateContractReq) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *UpdateContractReq) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type JVMLog struct {
	LogInfo              []string `protobuf:"bytes,1,rep,name=LogInfo,proto3" json:"LogInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JVMLog) Reset()         { *m = JVMLog{} }
func (m *JVMLog) String() string { return proto.CompactTextString(m) }
func (*JVMLog) ProtoMessage()    {}
func (*JVMLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1047aed7729a0b, []int{21}
}

func (m *JVMLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMLog.Unmarshal(m, b)
}
func (m *JVMLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMLog.Marshal(b, m, deterministic)
}
func (m *JVMLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMLog.Merge(m, src)
}
func (m *JVMLog) XXX_Size() int {
	return xxx_messageInfo_JVMLog.Size(m)
}
func (m *JVMLog) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMLog.DiscardUnknown(m)
}

var xxx_messageInfo_JVMLog proto.InternalMessageInfo

func (m *JVMLog) GetLogInfo() []string {
	if m != nil {
		return m.LogInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*JVMContractObject)(nil), "types.JVMContractObject")
	proto.RegisterType((*JVMContractData)(nil), "types.JVMContractData")
	proto.RegisterType((*LogJVMContractData)(nil), "types.LogJVMContractData")
	proto.RegisterType((*JVMContractState)(nil), "types.JVMContractState")
	proto.RegisterMapType((map[string][]byte)(nil), "types.JVMContractState.StorageEntry")
	proto.RegisterType((*JVMContractAction)(nil), "types.JVMContractAction")
	proto.RegisterType((*CreateJvmContract)(nil), "types.CreateJvmContract")
	proto.RegisterType((*CallJvmContract)(nil), "types.CallJvmContract")
	proto.RegisterType((*UpdateJvmContract)(nil), "types.UpdateJvmContract")
	proto.RegisterType((*ReceiptLocalData)(nil), "types.ReceiptLocalData")
	proto.RegisterType((*ReceiptJVMContract)(nil), "types.ReceiptJVMContract")
	proto.RegisterType((*JVMStateChangeItem)(nil), "types.JVMStateChangeItem")
	proto.RegisterType((*CheckJVMContractNameReq)(nil), "types.CheckJVMContractNameReq")
	proto.RegisterType((*CheckJVMAddrResp)(nil), "types.CheckJVMAddrResp")
	proto.RegisterType((*JVMDebugReq)(nil), "types.JVMDebugReq")
	proto.RegisterType((*JVMDebugResp)(nil), "types.JVMDebugResp")
	proto.RegisterType((*JVMGetAbiResp)(nil), "types.JVMGetAbiResp")
	proto.RegisterType((*JVMQueryReq)(nil), "types.JVMQueryReq")
	proto.RegisterType((*JVMQueryResponse)(nil), "types.JVMQueryResponse")
	proto.RegisterType((*CreateContractReq)(nil), "types.CreateContractReq")
	proto.RegisterType((*QueryCallContractReq)(nil), "types.QueryCallContractReq")
	proto.RegisterType((*UpdateContractReq)(nil), "types.UpdateContractReq")
	proto.RegisterType((*JVMLog)(nil), "types.JVMLog")
}

func init() {
	proto.RegisterFile("jvm.proto", fileDescriptor_ea1047aed7729a0b)
}

var fileDescriptor_ea1047aed7729a0b = []byte{
	// 888 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x3f, 0xc7, 0x71, 0xd3, 0x4c, 0x02, 0x4d, 0x57, 0xa7, 0x9e, 0x75, 0x0f, 0xa7, 0xb2, 0x02,
	0x29, 0x42, 0xa2, 0x42, 0x45, 0x42, 0xe8, 0x24, 0x90, 0x72, 0x29, 0xd0, 0x8b, 0x9a, 0x03, 0xf6,
	0x44, 0x9e, 0x78, 0xd9, 0xd8, 0x7b, 0x69, 0xae, 0xa9, 0xd7, 0xd8, 0xeb, 0x8a, 0xf0, 0x88, 0x78,
	0xe4, 0x95, 0xef, 0xc3, 0x47, 0x43, 0x33, 0xbb, 0x76, 0xd6, 0xc9, 0xf1, 0x76, 0xe2, 0xa9, 0xf3,
	0x77, 0xe7, 0x37, 0xe3, 0xf9, 0x4d, 0x03, 0xfd, 0xb7, 0x0f, 0xf7, 0x17, 0x79, 0xa1, 0x8d, 0x66,
	0x91, 0xd9, 0xe6, 0xaa, 0xe4, 0x7f, 0x04, 0x70, 0x3a, 0x5b, 0xcc, 0xa7, 0x3a, 0x33, 0x85, 0x4c,
	0xcc, 0x0f, 0xcb, 0xb7, 0x2a, 0x31, 0x8c, 0x41, 0x57, 0xa6, 0x69, 0x11, 0x07, 0xe7, 0xc1, 0xb8,
	0x2f, 0x48, 0x66, 0x9f, 0x42, 0x37, 0x95, 0x46, 0xc6, 0x9d, 0xf3, 0x60, 0x3c, 0xb8, 0x3c, 0xbb,
	0xa0, 0xfc, 0x0b, 0x2f, 0xf7, 0x4a, 0x1a, 0x29, 0x28, 0x86, 0x7d, 0x06, 0x51, 0x69, 0xa4, 0x51,
	0x71, 0x48, 0xc1, 0x4f, 0x0e, 0x83, 0x5f, 0xa3, 0x5b, 0xd8, 0x28, 0xfe, 0x77, 0x00, 0x27, 0x7b,
	0x0f, 0xb1, 0x18, 0x7a, 0x49, 0xa1, 0xa4, 0xd1, 0x35, 0x8a, 0x5a, 0x45, 0x70, 0x99, 0xbc, 0x57,
	0x04, 0xa4, 0x2f, 0x48, 0x6e, 0x00, 0x77, 0x3d, 0xc0, 0x0c, 0xba, 0x89, 0x4e, 0x55, 0x1c, 0x9d,
	0x07, 0xe3, 0xa1, 0x20, 0x99, 0x3d, 0x85, 0x63, 0xfc, 0x7b, 0x2d, 0xcb, 0xdb, 0xf8, 0x88, 0xec,
	0x8d, 0xce, 0x46, 0x10, 0xca, 0xe5, 0x3a, 0xee, 0x91, 0x19, 0x45, 0xfe, 0x57, 0x00, 0xec, 0x46,
	0xaf, 0xde, 0x0f, 0xb4, 0xd0, 0x83, 0xe6, 0xc3, 0xb0, 0x90, 0x77, 0x30, 0x62, 0xe8, 0xc9, 0xe5,
	0x9a, 0x5c, 0x91, 0x7d, 0xdd, 0xa9, 0xfc, 0x9f, 0x00, 0x46, 0xfb, 0x23, 0x64, 0x8f, 0x21, 0xca,
	0x74, 0x96, 0x28, 0x82, 0xd2, 0x15, 0x56, 0xc1, 0x02, 0x65, 0xb5, 0x4e, 0xd6, 0xa9, 0x4a, 0x09,
	0xcc, 0xb1, 0x68, 0x74, 0xf6, 0x0d, 0xf4, 0x4a, 0xa3, 0x0b, 0xb9, 0xc2, 0xcf, 0x13, 0x8e, 0x07,
	0x97, 0x1f, 0xff, 0xc7, 0xe7, 0xb9, 0x78, 0x6d, 0xc3, 0xbe, 0xcd, 0x4c, 0xb1, 0x15, 0x75, 0xd2,
	0xd3, 0xe7, 0x30, 0xf4, 0x1d, 0x38, 0xb7, 0x3b, 0xb5, 0x75, 0xa3, 0x40, 0x11, 0x31, 0x3d, 0xc8,
	0x4d, 0x65, 0xe7, 0x30, 0x14, 0x56, 0x79, 0xde, 0xf9, 0x2a, 0xe0, 0x7f, 0x76, 0x5a, 0xeb, 0x36,
	0x49, 0xcc, 0x5a, 0x67, 0xec, 0x1a, 0x4e, 0x69, 0x82, 0x6a, 0xf6, 0x70, 0x5f, 0xbb, 0xe8, 0xbd,
	0xc1, 0x65, 0xec, 0xb0, 0x4d, 0xf7, 0xfd, 0xd7, 0x8f, 0xc4, 0x61, 0x12, 0x7b, 0x01, 0x27, 0x89,
	0xdc, 0x6c, 0xfc, 0x77, 0xda, 0xfb, 0x3a, 0x6d, 0x7b, 0xaf, 0x1f, 0x89, 0xfd, 0x04, 0x44, 0x53,
	0xe5, 0xe9, 0x1e, 0x9a, 0xb0, 0x85, 0xe6, 0xe7, 0x7d, 0x3f, 0xa2, 0x39, 0x48, 0x62, 0x1f, 0x42,
	0xc7, 0x6c, 0xe9, 0x03, 0x47, 0xa2, 0x63, 0xb6, 0x2f, 0x7a, 0x6e, 0x2e, 0x5c, 0xc2, 0xe9, 0x41,
	0x43, 0xcd, 0xbe, 0x86, 0xde, 0xbe, 0xba, 0x9d, 0xb4, 0x3b, 0x82, 0x62, 0xb3, 0x62, 0x51, 0x7b,
	0xc5, 0x32, 0x6d, 0x14, 0x6d, 0x34, 0xda, 0xb4, 0x51, 0xfc, 0x0e, 0x4e, 0xf6, 0x7a, 0xc5, 0xb0,
	0x57, 0x98, 0xea, 0x58, 0x8d, 0x32, 0x7b, 0x06, 0x20, 0xe9, 0x23, 0x5c, 0x59, 0x6e, 0x87, 0xe3,
	0xbe, 0xf0, 0x2c, 0x08, 0xe0, 0x3b, 0x65, 0x31, 0x85, 0x02, 0xc5, 0xa6, 0x58, 0xd7, 0x2b, 0x26,
	0xe1, 0xf4, 0x60, 0x24, 0xef, 0xb9, 0x9f, 0x5f, 0x60, 0x24, 0x54, 0xa2, 0xd6, 0xb9, 0xb9, 0xd1,
	0x89, 0xdc, 0xd4, 0xe0, 0xea, 0xcd, 0x1b, 0xda, 0xcd, 0x43, 0x62, 0x55, 0xc5, 0xc2, 0x5b, 0xbe,
	0x46, 0x47, 0x5f, 0x5e, 0x28, 0xeb, 0xb3, 0x98, 0x1a, 0x9d, 0x1b, 0x60, 0xee, 0x75, 0x6f, 0x3b,
	0xd9, 0x19, 0x1c, 0xe1, 0x72, 0xa8, 0x9a, 0xe7, 0x4e, 0x63, 0x1c, 0x86, 0x89, 0x8b, 0x79, 0xb5,
	0xa3, 0x7b, 0xcb, 0xe6, 0xc7, 0x4c, 0x76, 0xf4, 0x6f, 0xd9, 0xf8, 0x1b, 0x60, 0xb3, 0xc5, 0x9c,
	0xb8, 0x36, 0xbd, 0x95, 0xd9, 0x4a, 0xbd, 0x34, 0xea, 0xfe, 0x1d, 0x7c, 0xf2, 0x91, 0x77, 0xda,
	0xc8, 0xa9, 0x4e, 0x55, 0x14, 0x2a, 0x33, 0x7e, 0x67, 0x2d, 0x1b, 0x9f, 0xc2, 0x93, 0xe9, 0xad,
	0x4a, 0xee, 0xbc, 0xde, 0x10, 0xa3, 0x50, 0xbf, 0xb2, 0x31, 0x9c, 0x78, 0xdf, 0xcc, 0x5b, 0x8f,
	0x7d, 0x33, 0xff, 0x12, 0x46, 0xf5, 0x23, 0x08, 0x5e, 0xa8, 0x32, 0xc7, 0xe2, 0xea, 0xb7, 0x75,
	0x69, 0x26, 0x9b, 0x42, 0xc9, 0xd4, 0x62, 0x3e, 0x16, 0x2d, 0x1b, 0xff, 0x04, 0x06, 0xb3, 0xc5,
	0xfc, 0x4a, 0x2d, 0xab, 0x15, 0x16, 0x3c, 0x83, 0x23, 0x9d, 0x23, 0x8b, 0x28, 0x38, 0x12, 0x4e,
	0xe3, 0x9f, 0xc3, 0x70, 0x17, 0x56, 0xe6, 0xec, 0x1c, 0x06, 0x29, 0x2a, 0x38, 0x9d, 0xaa, 0x74,
	0xa0, 0x7c, 0x13, 0xff, 0x08, 0x3e, 0x98, 0x2d, 0xe6, 0xdf, 0x2b, 0x33, 0x59, 0xae, 0x29, 0xc5,
	0x2d, 0x57, 0xb0, 0x3b, 0xe0, 0x5f, 0x53, 0xed, 0x9f, 0x2a, 0x55, 0x6c, 0xb1, 0x36, 0x9d, 0x5d,
	0xef, 0xbc, 0xd0, 0xd9, 0xdd, 0x6d, 0x6b, 0x2e, 0x8b, 0x9a, 0x02, 0x24, 0xf3, 0x2b, 0xba, 0xb7,
	0x2e, 0xbd, 0xcc, 0x75, 0x56, 0x2a, 0x3c, 0xcf, 0x65, 0x95, 0x24, 0xaa, 0x2c, 0x5d, 0xb7, 0xb5,
	0x8a, 0x9d, 0x15, 0xaa, 0xac, 0x36, 0xc6, 0xbd, 0xe1, 0x34, 0x5e, 0xd6, 0x64, 0xaf, 0xc7, 0x89,
	0x50, 0x46, 0x10, 0x4e, 0x1c, 0xd6, 0xbe, 0x40, 0xb1, 0x61, 0x67, 0xc7, 0x63, 0x27, 0xda, 0xb4,
	0xfb, 0x37, 0x8a, 0x36, 0x6d, 0xc8, 0x36, 0x45, 0x5a, 0x75, 0x2d, 0xad, 0xa6, 0x8e, 0x56, 0xc8,
	0xd2, 0xa8, 0x61, 0x29, 0xff, 0x1d, 0x1e, 0x13, 0x6e, 0xbc, 0x01, 0x7e, 0xdd, 0x77, 0xdd, 0x80,
	0xba, 0x4a, 0xc7, 0xab, 0xf2, 0x0c, 0xc0, 0x1e, 0x67, 0x8a, 0xb6, 0xf5, 0x3d, 0x0b, 0x8e, 0xf2,
	0x47, 0x59, 0x48, 0xba, 0x1a, 0x5d, 0x6a, 0xb7, 0xd1, 0xb1, 0x61, 0x7b, 0x0d, 0xfe, 0xcf, 0x86,
	0x39, 0x1c, 0xcd, 0x16, 0xf3, 0x1b, 0xbd, 0xc2, 0x2f, 0x74, 0xa3, 0x57, 0x2f, 0xb3, 0x37, 0x3a,
	0x0e, 0x08, 0x59, 0xad, 0x2e, 0x8f, 0xe8, 0xa7, 0xcf, 0x17, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x9a, 0xa5, 0x57, 0xa9, 0x07, 0x09, 0x00, 0x00,
}
