// Code generated by protoc-gen-go. DO NOT EDIT.
// source: evmcontract.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//合约对象信息
type EVMContractObject struct {
	Addr                 string            `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Data                 *EVMContractData  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	State                *EVMContractState `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EVMContractObject) Reset()         { *m = EVMContractObject{} }
func (m *EVMContractObject) String() string { return proto.CompactTextString(m) }
func (*EVMContractObject) ProtoMessage()    {}
func (*EVMContractObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{0}
}

func (m *EVMContractObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractObject.Unmarshal(m, b)
}
func (m *EVMContractObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractObject.Marshal(b, m, deterministic)
}
func (m *EVMContractObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractObject.Merge(m, src)
}
func (m *EVMContractObject) XXX_Size() int {
	return xxx_messageInfo_EVMContractObject.Size(m)
}
func (m *EVMContractObject) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractObject.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractObject proto.InternalMessageInfo

func (m *EVMContractObject) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *EVMContractObject) GetData() *EVMContractData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EVMContractObject) GetState() *EVMContractState {
	if m != nil {
		return m.State
	}
	return nil
}

// 存放合约固定数据
type EVMContractData struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias    string `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Addr     string `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	Code     []byte `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	CodeHash []byte `protobuf:"bytes,6,opt,name=codeHash,proto3" json:"codeHash,omitempty"`
	// 绑定ABI数据 ForkEVMABI
	Abi                  string   `protobuf:"bytes,7,opt,name=abi,proto3" json:"abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVMContractData) Reset()         { *m = EVMContractData{} }
func (m *EVMContractData) String() string { return proto.CompactTextString(m) }
func (*EVMContractData) ProtoMessage()    {}
func (*EVMContractData) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{1}
}

func (m *EVMContractData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractData.Unmarshal(m, b)
}
func (m *EVMContractData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractData.Marshal(b, m, deterministic)
}
func (m *EVMContractData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractData.Merge(m, src)
}
func (m *EVMContractData) XXX_Size() int {
	return xxx_messageInfo_EVMContractData.Size(m)
}
func (m *EVMContractData) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractData.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractData proto.InternalMessageInfo

func (m *EVMContractData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EVMContractData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EVMContractData) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *EVMContractData) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *EVMContractData) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *EVMContractData) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *EVMContractData) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

// 存放合约变化数据
type EVMContractState struct {
	Nonce                uint64            `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Suicided             bool              `protobuf:"varint,2,opt,name=suicided,proto3" json:"suicided,omitempty"`
	Frozen               uint64            `protobuf:"varint,3,opt,name=frozen,proto3" json:"frozen,omitempty"`
	StorageHash          []byte            `protobuf:"bytes,4,opt,name=storageHash,proto3" json:"storageHash,omitempty"`
	Storage              map[string][]byte `protobuf:"bytes,5,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EVMContractState) Reset()         { *m = EVMContractState{} }
func (m *EVMContractState) String() string { return proto.CompactTextString(m) }
func (*EVMContractState) ProtoMessage()    {}
func (*EVMContractState) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{2}
}

func (m *EVMContractState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractState.Unmarshal(m, b)
}
func (m *EVMContractState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractState.Marshal(b, m, deterministic)
}
func (m *EVMContractState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractState.Merge(m, src)
}
func (m *EVMContractState) XXX_Size() int {
	return xxx_messageInfo_EVMContractState.Size(m)
}
func (m *EVMContractState) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractState.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractState proto.InternalMessageInfo

func (m *EVMContractState) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *EVMContractState) GetSuicided() bool {
	if m != nil {
		return m.Suicided
	}
	return false
}

func (m *EVMContractState) GetFrozen() uint64 {
	if m != nil {
		return m.Frozen
	}
	return 0
}

func (m *EVMContractState) GetStorageHash() []byte {
	if m != nil {
		return m.StorageHash
	}
	return nil
}

func (m *EVMContractState) GetStorage() map[string][]byte {
	if m != nil {
		return m.Storage
	}
	return nil
}

type EVMContractAction struct {
	// Types that are valid to be assigned to Value:
	//	*EVMContractAction_Exec
	//	*EVMContractAction_Destroy
	//	*EVMContractAction_Freeze
	//	*EVMContractAction_Release
	//	*EVMContractAction_Update
	Value                isEVMContractAction_Value `protobuf_oneof:"value"`
	Ty                   int32                     `protobuf:"varint,6,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *EVMContractAction) Reset()         { *m = EVMContractAction{} }
func (m *EVMContractAction) String() string { return proto.CompactTextString(m) }
func (*EVMContractAction) ProtoMessage()    {}
func (*EVMContractAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{3}
}

func (m *EVMContractAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractAction.Unmarshal(m, b)
}
func (m *EVMContractAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractAction.Marshal(b, m, deterministic)
}
func (m *EVMContractAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractAction.Merge(m, src)
}
func (m *EVMContractAction) XXX_Size() int {
	return xxx_messageInfo_EVMContractAction.Size(m)
}
func (m *EVMContractAction) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractAction.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractAction proto.InternalMessageInfo

type isEVMContractAction_Value interface {
	isEVMContractAction_Value()
}

type EVMContractAction_Exec struct {
	Exec *EVMContractExec `protobuf:"bytes,1,opt,name=exec,proto3,oneof"`
}

type EVMContractAction_Destroy struct {
	Destroy *EVMContractDestroy `protobuf:"bytes,2,opt,name=destroy,proto3,oneof"`
}

type EVMContractAction_Freeze struct {
	Freeze *EVMContractFreeze `protobuf:"bytes,3,opt,name=freeze,proto3,oneof"`
}

type EVMContractAction_Release struct {
	Release *EVMContractRelease `protobuf:"bytes,4,opt,name=release,proto3,oneof"`
}

type EVMContractAction_Update struct {
	Update *EVMContractUpdate `protobuf:"bytes,5,opt,name=update,proto3,oneof"`
}

func (*EVMContractAction_Exec) isEVMContractAction_Value() {}

func (*EVMContractAction_Destroy) isEVMContractAction_Value() {}

func (*EVMContractAction_Freeze) isEVMContractAction_Value() {}

func (*EVMContractAction_Release) isEVMContractAction_Value() {}

func (*EVMContractAction_Update) isEVMContractAction_Value() {}

func (m *EVMContractAction) GetValue() isEVMContractAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *EVMContractAction) GetExec() *EVMContractExec {
	if x, ok := m.GetValue().(*EVMContractAction_Exec); ok {
		return x.Exec
	}
	return nil
}

func (m *EVMContractAction) GetDestroy() *EVMContractDestroy {
	if x, ok := m.GetValue().(*EVMContractAction_Destroy); ok {
		return x.Destroy
	}
	return nil
}

func (m *EVMContractAction) GetFreeze() *EVMContractFreeze {
	if x, ok := m.GetValue().(*EVMContractAction_Freeze); ok {
		return x.Freeze
	}
	return nil
}

func (m *EVMContractAction) GetRelease() *EVMContractRelease {
	if x, ok := m.GetValue().(*EVMContractAction_Release); ok {
		return x.Release
	}
	return nil
}

func (m *EVMContractAction) GetUpdate() *EVMContractUpdate {
	if x, ok := m.GetValue().(*EVMContractAction_Update); ok {
		return x.Update
	}
	return nil
}

func (m *EVMContractAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EVMContractAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EVMContractAction_Exec)(nil),
		(*EVMContractAction_Destroy)(nil),
		(*EVMContractAction_Freeze)(nil),
		(*EVMContractAction_Release)(nil),
		(*EVMContractAction_Update)(nil),
	}
}

// 创建和调用合约的请求结构
type EVMContractExec struct {
	// 转账金额
	Amount uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// 消耗限制，默认为Transaction.Fee
	GasLimit uint64 `protobuf:"varint,2,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	// gas价格，默认为1
	GasPrice uint32 `protobuf:"varint,3,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	// 合约数据
	Code []byte `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	//交易参数
	Para []byte `protobuf:"bytes,5,opt,name=para,proto3" json:"para,omitempty"`
	// 合约别名，方便识别
	Alias string `protobuf:"bytes,6,opt,name=alias,proto3" json:"alias,omitempty"`
	// 交易备注
	Note                 string   `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVMContractExec) Reset()         { *m = EVMContractExec{} }
func (m *EVMContractExec) String() string { return proto.CompactTextString(m) }
func (*EVMContractExec) ProtoMessage()    {}
func (*EVMContractExec) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{4}
}

func (m *EVMContractExec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractExec.Unmarshal(m, b)
}
func (m *EVMContractExec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractExec.Marshal(b, m, deterministic)
}
func (m *EVMContractExec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractExec.Merge(m, src)
}
func (m *EVMContractExec) XXX_Size() int {
	return xxx_messageInfo_EVMContractExec.Size(m)
}
func (m *EVMContractExec) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractExec.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractExec proto.InternalMessageInfo

func (m *EVMContractExec) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *EVMContractExec) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *EVMContractExec) GetGasPrice() uint32 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *EVMContractExec) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *EVMContractExec) GetPara() []byte {
	if m != nil {
		return m.Para
	}
	return nil
}

func (m *EVMContractExec) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *EVMContractExec) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 更新合约的请求结构
type EVMContractUpdate struct {
	// 待更新的合约地址
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// 转账金额
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// 消耗限制，默认为Transaction.Fee
	GasLimit uint64 `protobuf:"varint,3,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	// gas价格，默认为1
	GasPrice uint32 `protobuf:"varint,4,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	// 合约数据
	Code []byte `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	// 合约别名，方便识别
	Alias string `protobuf:"bytes,6,opt,name=alias,proto3" json:"alias,omitempty"`
	// 交易备注
	Note                 string   `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVMContractUpdate) Reset()         { *m = EVMContractUpdate{} }
func (m *EVMContractUpdate) String() string { return proto.CompactTextString(m) }
func (*EVMContractUpdate) ProtoMessage()    {}
func (*EVMContractUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{5}
}

func (m *EVMContractUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractUpdate.Unmarshal(m, b)
}
func (m *EVMContractUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractUpdate.Marshal(b, m, deterministic)
}
func (m *EVMContractUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractUpdate.Merge(m, src)
}
func (m *EVMContractUpdate) XXX_Size() int {
	return xxx_messageInfo_EVMContractUpdate.Size(m)
}
func (m *EVMContractUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractUpdate proto.InternalMessageInfo

func (m *EVMContractUpdate) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *EVMContractUpdate) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *EVMContractUpdate) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *EVMContractUpdate) GetGasPrice() uint32 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *EVMContractUpdate) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *EVMContractUpdate) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *EVMContractUpdate) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

type EVMContractDestroy struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVMContractDestroy) Reset()         { *m = EVMContractDestroy{} }
func (m *EVMContractDestroy) String() string { return proto.CompactTextString(m) }
func (*EVMContractDestroy) ProtoMessage()    {}
func (*EVMContractDestroy) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{6}
}

func (m *EVMContractDestroy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractDestroy.Unmarshal(m, b)
}
func (m *EVMContractDestroy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractDestroy.Marshal(b, m, deterministic)
}
func (m *EVMContractDestroy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractDestroy.Merge(m, src)
}
func (m *EVMContractDestroy) XXX_Size() int {
	return xxx_messageInfo_EVMContractDestroy.Size(m)
}
func (m *EVMContractDestroy) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractDestroy.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractDestroy proto.InternalMessageInfo

func (m *EVMContractDestroy) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type EVMContractFreeze struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVMContractFreeze) Reset()         { *m = EVMContractFreeze{} }
func (m *EVMContractFreeze) String() string { return proto.CompactTextString(m) }
func (*EVMContractFreeze) ProtoMessage()    {}
func (*EVMContractFreeze) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{7}
}

func (m *EVMContractFreeze) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractFreeze.Unmarshal(m, b)
}
func (m *EVMContractFreeze) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractFreeze.Marshal(b, m, deterministic)
}
func (m *EVMContractFreeze) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractFreeze.Merge(m, src)
}
func (m *EVMContractFreeze) XXX_Size() int {
	return xxx_messageInfo_EVMContractFreeze.Size(m)
}
func (m *EVMContractFreeze) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractFreeze.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractFreeze proto.InternalMessageInfo

func (m *EVMContractFreeze) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type EVMContractRelease struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVMContractRelease) Reset()         { *m = EVMContractRelease{} }
func (m *EVMContractRelease) String() string { return proto.CompactTextString(m) }
func (*EVMContractRelease) ProtoMessage()    {}
func (*EVMContractRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{8}
}

func (m *EVMContractRelease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractRelease.Unmarshal(m, b)
}
func (m *EVMContractRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractRelease.Marshal(b, m, deterministic)
}
func (m *EVMContractRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractRelease.Merge(m, src)
}
func (m *EVMContractRelease) XXX_Size() int {
	return xxx_messageInfo_EVMContractRelease.Size(m)
}
func (m *EVMContractRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractRelease.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractRelease proto.InternalMessageInfo

func (m *EVMContractRelease) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// 合约创建/调用日志
type ReceiptEVMContract struct {
	Caller       string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	ContractName string `protobuf:"bytes,2,opt,name=contractName,proto3" json:"contractName,omitempty"`
	ContractAddr string `protobuf:"bytes,3,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	UsedGas      uint64 `protobuf:"varint,4,opt,name=usedGas,proto3" json:"usedGas,omitempty"`
	// 创建合约返回的代码
	Ret []byte `protobuf:"bytes,5,opt,name=ret,proto3" json:"ret,omitempty"`
	// json格式化后的返回值
	JsonRet              string   `protobuf:"bytes,6,opt,name=jsonRet,proto3" json:"jsonRet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptEVMContract) Reset()         { *m = ReceiptEVMContract{} }
func (m *ReceiptEVMContract) String() string { return proto.CompactTextString(m) }
func (*ReceiptEVMContract) ProtoMessage()    {}
func (*ReceiptEVMContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{9}
}

func (m *ReceiptEVMContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptEVMContract.Unmarshal(m, b)
}
func (m *ReceiptEVMContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptEVMContract.Marshal(b, m, deterministic)
}
func (m *ReceiptEVMContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptEVMContract.Merge(m, src)
}
func (m *ReceiptEVMContract) XXX_Size() int {
	return xxx_messageInfo_ReceiptEVMContract.Size(m)
}
func (m *ReceiptEVMContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptEVMContract.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptEVMContract proto.InternalMessageInfo

func (m *ReceiptEVMContract) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *ReceiptEVMContract) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ReceiptEVMContract) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *ReceiptEVMContract) GetUsedGas() uint64 {
	if m != nil {
		return m.UsedGas
	}
	return 0
}

func (m *ReceiptEVMContract) GetRet() []byte {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *ReceiptEVMContract) GetJsonRet() string {
	if m != nil {
		return m.JsonRet
	}
	return ""
}

// 用于保存EVM只能合约中的状态数据变更
type EVMStateChangeItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PreValue             []byte   `protobuf:"bytes,2,opt,name=preValue,proto3" json:"preValue,omitempty"`
	CurrentValue         []byte   `protobuf:"bytes,3,opt,name=currentValue,proto3" json:"currentValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVMStateChangeItem) Reset()         { *m = EVMStateChangeItem{} }
func (m *EVMStateChangeItem) String() string { return proto.CompactTextString(m) }
func (*EVMStateChangeItem) ProtoMessage()    {}
func (*EVMStateChangeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{10}
}

func (m *EVMStateChangeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMStateChangeItem.Unmarshal(m, b)
}
func (m *EVMStateChangeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMStateChangeItem.Marshal(b, m, deterministic)
}
func (m *EVMStateChangeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMStateChangeItem.Merge(m, src)
}
func (m *EVMStateChangeItem) XXX_Size() int {
	return xxx_messageInfo_EVMStateChangeItem.Size(m)
}
func (m *EVMStateChangeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMStateChangeItem.DiscardUnknown(m)
}

var xxx_messageInfo_EVMStateChangeItem proto.InternalMessageInfo

func (m *EVMStateChangeItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EVMStateChangeItem) GetPreValue() []byte {
	if m != nil {
		return m.PreValue
	}
	return nil
}

func (m *EVMStateChangeItem) GetCurrentValue() []byte {
	if m != nil {
		return m.CurrentValue
	}
	return nil
}

// 存放合约固定数据
type EVMContractDataCmd struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias                string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	CodeHash             string   `protobuf:"bytes,6,opt,name=codeHash,proto3" json:"codeHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVMContractDataCmd) Reset()         { *m = EVMContractDataCmd{} }
func (m *EVMContractDataCmd) String() string { return proto.CompactTextString(m) }
func (*EVMContractDataCmd) ProtoMessage()    {}
func (*EVMContractDataCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{11}
}

func (m *EVMContractDataCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractDataCmd.Unmarshal(m, b)
}
func (m *EVMContractDataCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractDataCmd.Marshal(b, m, deterministic)
}
func (m *EVMContractDataCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractDataCmd.Merge(m, src)
}
func (m *EVMContractDataCmd) XXX_Size() int {
	return xxx_messageInfo_EVMContractDataCmd.Size(m)
}
func (m *EVMContractDataCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractDataCmd.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractDataCmd proto.InternalMessageInfo

func (m *EVMContractDataCmd) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EVMContractDataCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EVMContractDataCmd) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *EVMContractDataCmd) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *EVMContractDataCmd) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *EVMContractDataCmd) GetCodeHash() string {
	if m != nil {
		return m.CodeHash
	}
	return ""
}

// 存放合约变化数据
type EVMContractStateCmd struct {
	Nonce                uint64            `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Suicided             bool              `protobuf:"varint,2,opt,name=suicided,proto3" json:"suicided,omitempty"`
	StorageHash          string            `protobuf:"bytes,3,opt,name=storageHash,proto3" json:"storageHash,omitempty"`
	Storage              map[string]string `protobuf:"bytes,4,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EVMContractStateCmd) Reset()         { *m = EVMContractStateCmd{} }
func (m *EVMContractStateCmd) String() string { return proto.CompactTextString(m) }
func (*EVMContractStateCmd) ProtoMessage()    {}
func (*EVMContractStateCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{12}
}

func (m *EVMContractStateCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMContractStateCmd.Unmarshal(m, b)
}
func (m *EVMContractStateCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMContractStateCmd.Marshal(b, m, deterministic)
}
func (m *EVMContractStateCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMContractStateCmd.Merge(m, src)
}
func (m *EVMContractStateCmd) XXX_Size() int {
	return xxx_messageInfo_EVMContractStateCmd.Size(m)
}
func (m *EVMContractStateCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMContractStateCmd.DiscardUnknown(m)
}

var xxx_messageInfo_EVMContractStateCmd proto.InternalMessageInfo

func (m *EVMContractStateCmd) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *EVMContractStateCmd) GetSuicided() bool {
	if m != nil {
		return m.Suicided
	}
	return false
}

func (m *EVMContractStateCmd) GetStorageHash() string {
	if m != nil {
		return m.StorageHash
	}
	return ""
}

func (m *EVMContractStateCmd) GetStorage() map[string]string {
	if m != nil {
		return m.Storage
	}
	return nil
}

// 合约创建/调用日志
type ReceiptEVMContractCmd struct {
	Caller string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	// 合约创建时才会返回此内容
	ContractName string `protobuf:"bytes,2,opt,name=contractName,proto3" json:"contractName,omitempty"`
	ContractAddr string `protobuf:"bytes,3,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	UsedGas      uint64 `protobuf:"varint,4,opt,name=usedGas,proto3" json:"usedGas,omitempty"`
	// 创建合约返回的代码
	Ret                  string   `protobuf:"bytes,5,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptEVMContractCmd) Reset()         { *m = ReceiptEVMContractCmd{} }
func (m *ReceiptEVMContractCmd) String() string { return proto.CompactTextString(m) }
func (*ReceiptEVMContractCmd) ProtoMessage()    {}
func (*ReceiptEVMContractCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{13}
}

func (m *ReceiptEVMContractCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptEVMContractCmd.Unmarshal(m, b)
}
func (m *ReceiptEVMContractCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptEVMContractCmd.Marshal(b, m, deterministic)
}
func (m *ReceiptEVMContractCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptEVMContractCmd.Merge(m, src)
}
func (m *ReceiptEVMContractCmd) XXX_Size() int {
	return xxx_messageInfo_ReceiptEVMContractCmd.Size(m)
}
func (m *ReceiptEVMContractCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptEVMContractCmd.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptEVMContractCmd proto.InternalMessageInfo

func (m *ReceiptEVMContractCmd) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *ReceiptEVMContractCmd) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ReceiptEVMContractCmd) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *ReceiptEVMContractCmd) GetUsedGas() uint64 {
	if m != nil {
		return m.UsedGas
	}
	return 0
}

func (m *ReceiptEVMContractCmd) GetRet() string {
	if m != nil {
		return m.Ret
	}
	return ""
}

type CheckEVMAddrReq struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEVMAddrReq) Reset()         { *m = CheckEVMAddrReq{} }
func (m *CheckEVMAddrReq) String() string { return proto.CompactTextString(m) }
func (*CheckEVMAddrReq) ProtoMessage()    {}
func (*CheckEVMAddrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{14}
}

func (m *CheckEVMAddrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEVMAddrReq.Unmarshal(m, b)
}
func (m *CheckEVMAddrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEVMAddrReq.Marshal(b, m, deterministic)
}
func (m *CheckEVMAddrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEVMAddrReq.Merge(m, src)
}
func (m *CheckEVMAddrReq) XXX_Size() int {
	return xxx_messageInfo_CheckEVMAddrReq.Size(m)
}
func (m *CheckEVMAddrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEVMAddrReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEVMAddrReq proto.InternalMessageInfo

func (m *CheckEVMAddrReq) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type CheckEVMAddrResp struct {
	Contract             bool     `protobuf:"varint,1,opt,name=contract,proto3" json:"contract,omitempty"`
	ContractAddr         string   `protobuf:"bytes,2,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	ContractName         string   `protobuf:"bytes,3,opt,name=contractName,proto3" json:"contractName,omitempty"`
	AliasName            string   `protobuf:"bytes,4,opt,name=aliasName,proto3" json:"aliasName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEVMAddrResp) Reset()         { *m = CheckEVMAddrResp{} }
func (m *CheckEVMAddrResp) String() string { return proto.CompactTextString(m) }
func (*CheckEVMAddrResp) ProtoMessage()    {}
func (*CheckEVMAddrResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{15}
}

func (m *CheckEVMAddrResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEVMAddrResp.Unmarshal(m, b)
}
func (m *CheckEVMAddrResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEVMAddrResp.Marshal(b, m, deterministic)
}
func (m *CheckEVMAddrResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEVMAddrResp.Merge(m, src)
}
func (m *CheckEVMAddrResp) XXX_Size() int {
	return xxx_messageInfo_CheckEVMAddrResp.Size(m)
}
func (m *CheckEVMAddrResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEVMAddrResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEVMAddrResp proto.InternalMessageInfo

func (m *CheckEVMAddrResp) GetContract() bool {
	if m != nil {
		return m.Contract
	}
	return false
}

func (m *CheckEVMAddrResp) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *CheckEVMAddrResp) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *CheckEVMAddrResp) GetAliasName() string {
	if m != nil {
		return m.AliasName
	}
	return ""
}

type EstimateEVMGasReq struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Para                 []byte   `protobuf:"bytes,2,opt,name=para,proto3" json:"para,omitempty"`
	Caller               string   `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`
	Amount               uint64   `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstimateEVMGasReq) Reset()         { *m = EstimateEVMGasReq{} }
func (m *EstimateEVMGasReq) String() string { return proto.CompactTextString(m) }
func (*EstimateEVMGasReq) ProtoMessage()    {}
func (*EstimateEVMGasReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{16}
}

func (m *EstimateEVMGasReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateEVMGasReq.Unmarshal(m, b)
}
func (m *EstimateEVMGasReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateEVMGasReq.Marshal(b, m, deterministic)
}
func (m *EstimateEVMGasReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateEVMGasReq.Merge(m, src)
}
func (m *EstimateEVMGasReq) XXX_Size() int {
	return xxx_messageInfo_EstimateEVMGasReq.Size(m)
}
func (m *EstimateEVMGasReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateEVMGasReq.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateEVMGasReq proto.InternalMessageInfo

func (m *EstimateEVMGasReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EstimateEVMGasReq) GetPara() []byte {
	if m != nil {
		return m.Para
	}
	return nil
}

func (m *EstimateEVMGasReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *EstimateEVMGasReq) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type EstimateEVMGasResp struct {
	Gas                  uint64   `protobuf:"varint,1,opt,name=gas,proto3" json:"gas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstimateEVMGasResp) Reset()         { *m = EstimateEVMGasResp{} }
func (m *EstimateEVMGasResp) String() string { return proto.CompactTextString(m) }
func (*EstimateEVMGasResp) ProtoMessage()    {}
func (*EstimateEVMGasResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{17}
}

func (m *EstimateEVMGasResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateEVMGasResp.Unmarshal(m, b)
}
func (m *EstimateEVMGasResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateEVMGasResp.Marshal(b, m, deterministic)
}
func (m *EstimateEVMGasResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateEVMGasResp.Merge(m, src)
}
func (m *EstimateEVMGasResp) XXX_Size() int {
	return xxx_messageInfo_EstimateEVMGasResp.Size(m)
}
func (m *EstimateEVMGasResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateEVMGasResp.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateEVMGasResp proto.InternalMessageInfo

func (m *EstimateEVMGasResp) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

type EvmDebugReq struct {
	// 0 query, 1 set, -1 clear
	Optype               int32    `protobuf:"varint,1,opt,name=optype,proto3" json:"optype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmDebugReq) Reset()         { *m = EvmDebugReq{} }
func (m *EvmDebugReq) String() string { return proto.CompactTextString(m) }
func (*EvmDebugReq) ProtoMessage()    {}
func (*EvmDebugReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{18}
}

func (m *EvmDebugReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmDebugReq.Unmarshal(m, b)
}
func (m *EvmDebugReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmDebugReq.Marshal(b, m, deterministic)
}
func (m *EvmDebugReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmDebugReq.Merge(m, src)
}
func (m *EvmDebugReq) XXX_Size() int {
	return xxx_messageInfo_EvmDebugReq.Size(m)
}
func (m *EvmDebugReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmDebugReq.DiscardUnknown(m)
}

var xxx_messageInfo_EvmDebugReq proto.InternalMessageInfo

func (m *EvmDebugReq) GetOptype() int32 {
	if m != nil {
		return m.Optype
	}
	return 0
}

type EvmDebugResp struct {
	DebugStatus          string   `protobuf:"bytes,1,opt,name=debugStatus,proto3" json:"debugStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmDebugResp) Reset()         { *m = EvmDebugResp{} }
func (m *EvmDebugResp) String() string { return proto.CompactTextString(m) }
func (*EvmDebugResp) ProtoMessage()    {}
func (*EvmDebugResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{19}
}

func (m *EvmDebugResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmDebugResp.Unmarshal(m, b)
}
func (m *EvmDebugResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmDebugResp.Marshal(b, m, deterministic)
}
func (m *EvmDebugResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmDebugResp.Merge(m, src)
}
func (m *EvmDebugResp) XXX_Size() int {
	return xxx_messageInfo_EvmDebugResp.Size(m)
}
func (m *EvmDebugResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmDebugResp.DiscardUnknown(m)
}

var xxx_messageInfo_EvmDebugResp proto.InternalMessageInfo

func (m *EvmDebugResp) GetDebugStatus() string {
	if m != nil {
		return m.DebugStatus
	}
	return ""
}

type EvmQueryAbiReq struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmQueryAbiReq) Reset()         { *m = EvmQueryAbiReq{} }
func (m *EvmQueryAbiReq) String() string { return proto.CompactTextString(m) }
func (*EvmQueryAbiReq) ProtoMessage()    {}
func (*EvmQueryAbiReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{20}
}

func (m *EvmQueryAbiReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmQueryAbiReq.Unmarshal(m, b)
}
func (m *EvmQueryAbiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmQueryAbiReq.Marshal(b, m, deterministic)
}
func (m *EvmQueryAbiReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmQueryAbiReq.Merge(m, src)
}
func (m *EvmQueryAbiReq) XXX_Size() int {
	return xxx_messageInfo_EvmQueryAbiReq.Size(m)
}
func (m *EvmQueryAbiReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmQueryAbiReq.DiscardUnknown(m)
}

var xxx_messageInfo_EvmQueryAbiReq proto.InternalMessageInfo

func (m *EvmQueryAbiReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type EvmQueryAbiResp struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Abi                  string   `protobuf:"bytes,2,opt,name=abi,proto3" json:"abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmQueryAbiResp) Reset()         { *m = EvmQueryAbiResp{} }
func (m *EvmQueryAbiResp) String() string { return proto.CompactTextString(m) }
func (*EvmQueryAbiResp) ProtoMessage()    {}
func (*EvmQueryAbiResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{21}
}

func (m *EvmQueryAbiResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmQueryAbiResp.Unmarshal(m, b)
}
func (m *EvmQueryAbiResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmQueryAbiResp.Marshal(b, m, deterministic)
}
func (m *EvmQueryAbiResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmQueryAbiResp.Merge(m, src)
}
func (m *EvmQueryAbiResp) XXX_Size() int {
	return xxx_messageInfo_EvmQueryAbiResp.Size(m)
}
func (m *EvmQueryAbiResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmQueryAbiResp.DiscardUnknown(m)
}

var xxx_messageInfo_EvmQueryAbiResp proto.InternalMessageInfo

func (m *EvmQueryAbiResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EvmQueryAbiResp) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

type EvmQueryReq struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Caller               string   `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmQueryReq) Reset()         { *m = EvmQueryReq{} }
func (m *EvmQueryReq) String() string { return proto.CompactTextString(m) }
func (*EvmQueryReq) ProtoMessage()    {}
func (*EvmQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{22}
}

func (m *EvmQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmQueryReq.Unmarshal(m, b)
}
func (m *EvmQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmQueryReq.Marshal(b, m, deterministic)
}
func (m *EvmQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmQueryReq.Merge(m, src)
}
func (m *EvmQueryReq) XXX_Size() int {
	return xxx_messageInfo_EvmQueryReq.Size(m)
}
func (m *EvmQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_EvmQueryReq proto.InternalMessageInfo

func (m *EvmQueryReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EvmQueryReq) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *EvmQueryReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

type EvmQueryResp struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Caller               string   `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`
	RawData              string   `protobuf:"bytes,4,opt,name=rawData,proto3" json:"rawData,omitempty"`
	JsonData             string   `protobuf:"bytes,5,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmQueryResp) Reset()         { *m = EvmQueryResp{} }
func (m *EvmQueryResp) String() string { return proto.CompactTextString(m) }
func (*EvmQueryResp) ProtoMessage()    {}
func (*EvmQueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{23}
}

func (m *EvmQueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmQueryResp.Unmarshal(m, b)
}
func (m *EvmQueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmQueryResp.Marshal(b, m, deterministic)
}
func (m *EvmQueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmQueryResp.Merge(m, src)
}
func (m *EvmQueryResp) XXX_Size() int {
	return xxx_messageInfo_EvmQueryResp.Size(m)
}
func (m *EvmQueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmQueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_EvmQueryResp proto.InternalMessageInfo

func (m *EvmQueryResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EvmQueryResp) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *EvmQueryResp) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *EvmQueryResp) GetRawData() string {
	if m != nil {
		return m.RawData
	}
	return ""
}

func (m *EvmQueryResp) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

type EvmContractCreateReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Fee                  int64    `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	Note                 string   `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Alias                string   `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	Caller               string   `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"`
	Parameter            string   `protobuf:"bytes,6,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Expire               string   `protobuf:"bytes,7,opt,name=expire,proto3" json:"expire,omitempty"`
	ParaName             string   `protobuf:"bytes,8,opt,name=paraName,proto3" json:"paraName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmContractCreateReq) Reset()         { *m = EvmContractCreateReq{} }
func (m *EvmContractCreateReq) String() string { return proto.CompactTextString(m) }
func (*EvmContractCreateReq) ProtoMessage()    {}
func (*EvmContractCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{24}
}

func (m *EvmContractCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmContractCreateReq.Unmarshal(m, b)
}
func (m *EvmContractCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmContractCreateReq.Marshal(b, m, deterministic)
}
func (m *EvmContractCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmContractCreateReq.Merge(m, src)
}
func (m *EvmContractCreateReq) XXX_Size() int {
	return xxx_messageInfo_EvmContractCreateReq.Size(m)
}
func (m *EvmContractCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmContractCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_EvmContractCreateReq proto.InternalMessageInfo

func (m *EvmContractCreateReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *EvmContractCreateReq) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *EvmContractCreateReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *EvmContractCreateReq) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *EvmContractCreateReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *EvmContractCreateReq) GetParameter() string {
	if m != nil {
		return m.Parameter
	}
	return ""
}

func (m *EvmContractCreateReq) GetExpire() string {
	if m != nil {
		return m.Expire
	}
	return ""
}

func (m *EvmContractCreateReq) GetParaName() string {
	if m != nil {
		return m.ParaName
	}
	return ""
}

type EvmContractCallReq struct {
	Amount               uint64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Fee                  int64    `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Note                 string   `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Caller               string   `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"`
	Parameter            string   `protobuf:"bytes,6,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Exec                 string   `protobuf:"bytes,7,opt,name=exec,proto3" json:"exec,omitempty"`
	Expire               string   `protobuf:"bytes,8,opt,name=expire,proto3" json:"expire,omitempty"`
	ParaName             string   `protobuf:"bytes,9,opt,name=paraName,proto3" json:"paraName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmContractCallReq) Reset()         { *m = EvmContractCallReq{} }
func (m *EvmContractCallReq) String() string { return proto.CompactTextString(m) }
func (*EvmContractCallReq) ProtoMessage()    {}
func (*EvmContractCallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{25}
}

func (m *EvmContractCallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmContractCallReq.Unmarshal(m, b)
}
func (m *EvmContractCallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmContractCallReq.Marshal(b, m, deterministic)
}
func (m *EvmContractCallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmContractCallReq.Merge(m, src)
}
func (m *EvmContractCallReq) XXX_Size() int {
	return xxx_messageInfo_EvmContractCallReq.Size(m)
}
func (m *EvmContractCallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmContractCallReq.DiscardUnknown(m)
}

var xxx_messageInfo_EvmContractCallReq proto.InternalMessageInfo

func (m *EvmContractCallReq) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *EvmContractCallReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *EvmContractCallReq) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *EvmContractCallReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *EvmContractCallReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *EvmContractCallReq) GetParameter() string {
	if m != nil {
		return m.Parameter
	}
	return ""
}

func (m *EvmContractCallReq) GetExec() string {
	if m != nil {
		return m.Exec
	}
	return ""
}

func (m *EvmContractCallReq) GetExpire() string {
	if m != nil {
		return m.Expire
	}
	return ""
}

func (m *EvmContractCallReq) GetParaName() string {
	if m != nil {
		return m.ParaName
	}
	return ""
}

type EvmContractTransferReq struct {
	Caller               string   `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Exec                 string   `protobuf:"bytes,3,opt,name=exec,proto3" json:"exec,omitempty"`
	Expire               string   `protobuf:"bytes,4,opt,name=expire,proto3" json:"expire,omitempty"`
	IsWithdraw           bool     `protobuf:"varint,5,opt,name=isWithdraw,proto3" json:"isWithdraw,omitempty"`
	ParaName             string   `protobuf:"bytes,6,opt,name=paraName,proto3" json:"paraName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmContractTransferReq) Reset()         { *m = EvmContractTransferReq{} }
func (m *EvmContractTransferReq) String() string { return proto.CompactTextString(m) }
func (*EvmContractTransferReq) ProtoMessage()    {}
func (*EvmContractTransferReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{26}
}

func (m *EvmContractTransferReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmContractTransferReq.Unmarshal(m, b)
}
func (m *EvmContractTransferReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmContractTransferReq.Marshal(b, m, deterministic)
}
func (m *EvmContractTransferReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmContractTransferReq.Merge(m, src)
}
func (m *EvmContractTransferReq) XXX_Size() int {
	return xxx_messageInfo_EvmContractTransferReq.Size(m)
}
func (m *EvmContractTransferReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmContractTransferReq.DiscardUnknown(m)
}

var xxx_messageInfo_EvmContractTransferReq proto.InternalMessageInfo

func (m *EvmContractTransferReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *EvmContractTransferReq) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *EvmContractTransferReq) GetExec() string {
	if m != nil {
		return m.Exec
	}
	return ""
}

func (m *EvmContractTransferReq) GetExpire() string {
	if m != nil {
		return m.Expire
	}
	return ""
}

func (m *EvmContractTransferReq) GetIsWithdraw() bool {
	if m != nil {
		return m.IsWithdraw
	}
	return false
}

func (m *EvmContractTransferReq) GetParaName() string {
	if m != nil {
		return m.ParaName
	}
	return ""
}

type EvmGetNonceReq struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmGetNonceReq) Reset()         { *m = EvmGetNonceReq{} }
func (m *EvmGetNonceReq) String() string { return proto.CompactTextString(m) }
func (*EvmGetNonceReq) ProtoMessage()    {}
func (*EvmGetNonceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{27}
}

func (m *EvmGetNonceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmGetNonceReq.Unmarshal(m, b)
}
func (m *EvmGetNonceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmGetNonceReq.Marshal(b, m, deterministic)
}
func (m *EvmGetNonceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmGetNonceReq.Merge(m, src)
}
func (m *EvmGetNonceReq) XXX_Size() int {
	return xxx_messageInfo_EvmGetNonceReq.Size(m)
}
func (m *EvmGetNonceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmGetNonceReq.DiscardUnknown(m)
}

var xxx_messageInfo_EvmGetNonceReq proto.InternalMessageInfo

func (m *EvmGetNonceReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type EvmGetNonceRespose struct {
	Nonce                int64    `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmGetNonceRespose) Reset()         { *m = EvmGetNonceRespose{} }
func (m *EvmGetNonceRespose) String() string { return proto.CompactTextString(m) }
func (*EvmGetNonceRespose) ProtoMessage()    {}
func (*EvmGetNonceRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_74353de561acd7c6, []int{28}
}

func (m *EvmGetNonceRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmGetNonceRespose.Unmarshal(m, b)
}
func (m *EvmGetNonceRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmGetNonceRespose.Marshal(b, m, deterministic)
}
func (m *EvmGetNonceRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmGetNonceRespose.Merge(m, src)
}
func (m *EvmGetNonceRespose) XXX_Size() int {
	return xxx_messageInfo_EvmGetNonceRespose.Size(m)
}
func (m *EvmGetNonceRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmGetNonceRespose.DiscardUnknown(m)
}

var xxx_messageInfo_EvmGetNonceRespose proto.InternalMessageInfo

func (m *EvmGetNonceRespose) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func init() {
	proto.RegisterType((*EVMContractObject)(nil), "types.EVMContractObject")
	proto.RegisterType((*EVMContractData)(nil), "types.EVMContractData")
	proto.RegisterType((*EVMContractState)(nil), "types.EVMContractState")
	proto.RegisterMapType((map[string][]byte)(nil), "types.EVMContractState.StorageEntry")
	proto.RegisterType((*EVMContractAction)(nil), "types.EVMContractAction")
	proto.RegisterType((*EVMContractExec)(nil), "types.EVMContractExec")
	proto.RegisterType((*EVMContractUpdate)(nil), "types.EVMContractUpdate")
	proto.RegisterType((*EVMContractDestroy)(nil), "types.EVMContractDestroy")
	proto.RegisterType((*EVMContractFreeze)(nil), "types.EVMContractFreeze")
	proto.RegisterType((*EVMContractRelease)(nil), "types.EVMContractRelease")
	proto.RegisterType((*ReceiptEVMContract)(nil), "types.ReceiptEVMContract")
	proto.RegisterType((*EVMStateChangeItem)(nil), "types.EVMStateChangeItem")
	proto.RegisterType((*EVMContractDataCmd)(nil), "types.EVMContractDataCmd")
	proto.RegisterType((*EVMContractStateCmd)(nil), "types.EVMContractStateCmd")
	proto.RegisterMapType((map[string]string)(nil), "types.EVMContractStateCmd.StorageEntry")
	proto.RegisterType((*ReceiptEVMContractCmd)(nil), "types.ReceiptEVMContractCmd")
	proto.RegisterType((*CheckEVMAddrReq)(nil), "types.CheckEVMAddrReq")
	proto.RegisterType((*CheckEVMAddrResp)(nil), "types.CheckEVMAddrResp")
	proto.RegisterType((*EstimateEVMGasReq)(nil), "types.EstimateEVMGasReq")
	proto.RegisterType((*EstimateEVMGasResp)(nil), "types.EstimateEVMGasResp")
	proto.RegisterType((*EvmDebugReq)(nil), "types.EvmDebugReq")
	proto.RegisterType((*EvmDebugResp)(nil), "types.EvmDebugResp")
	proto.RegisterType((*EvmQueryAbiReq)(nil), "types.EvmQueryAbiReq")
	proto.RegisterType((*EvmQueryAbiResp)(nil), "types.EvmQueryAbiResp")
	proto.RegisterType((*EvmQueryReq)(nil), "types.EvmQueryReq")
	proto.RegisterType((*EvmQueryResp)(nil), "types.EvmQueryResp")
	proto.RegisterType((*EvmContractCreateReq)(nil), "types.EvmContractCreateReq")
	proto.RegisterType((*EvmContractCallReq)(nil), "types.EvmContractCallReq")
	proto.RegisterType((*EvmContractTransferReq)(nil), "types.EvmContractTransferReq")
	proto.RegisterType((*EvmGetNonceReq)(nil), "types.EvmGetNonceReq")
	proto.RegisterType((*EvmGetNonceRespose)(nil), "types.EvmGetNonceRespose")
}

func init() { proto.RegisterFile("evmcontract.proto", fileDescriptor_74353de561acd7c6) }

var fileDescriptor_74353de561acd7c6 = []byte{
	// 1213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x4b, 0x6f, 0x1c, 0x45,
	0x17, 0x75, 0x3f, 0xe6, 0x55, 0xf6, 0x17, 0xdb, 0xfd, 0x05, 0x33, 0x58, 0x11, 0xb2, 0x5a, 0x84,
	0x58, 0x16, 0x58, 0xc8, 0x08, 0x09, 0x45, 0x02, 0xc9, 0x38, 0x83, 0x8d, 0x84, 0x03, 0x54, 0x88,
	0x59, 0x97, 0xbb, 0xaf, 0xc7, 0x9d, 0x4c, 0x3f, 0xa8, 0xaa, 0x71, 0x3c, 0x59, 0xb2, 0x66, 0xc9,
	0x92, 0x1d, 0x4b, 0x36, 0x91, 0x10, 0x1b, 0x7e, 0x05, 0x3f, 0x82, 0x05, 0xbf, 0x81, 0x15, 0xba,
	0xb7, 0xab, 0x5f, 0x33, 0x3d, 0x16, 0x41, 0x08, 0xb1, 0x9a, 0xba, 0x55, 0xb7, 0xaa, 0xce, 0xb9,
	0x7d, 0xea, 0x54, 0x0d, 0xdb, 0x84, 0xab, 0x38, 0x48, 0x13, 0x2d, 0x45, 0xa0, 0xf7, 0x33, 0x99,
	0xea, 0xd4, 0xeb, 0xe8, 0x59, 0x06, 0xca, 0xff, 0xc6, 0x62, 0x9b, 0xa3, 0xb3, 0xd3, 0x23, 0x33,
	0xf8, 0xd9, 0xf9, 0x13, 0x08, 0xb4, 0xe7, 0x31, 0x57, 0x84, 0xa1, 0x1c, 0x5a, 0x3b, 0xd6, 0xee,
	0x80, 0x53, 0xdb, 0xdb, 0x63, 0x6e, 0x28, 0xb4, 0x18, 0xda, 0x3b, 0xd6, 0xee, 0xea, 0xc1, 0xd6,
	0x3e, 0xcd, 0xdf, 0xaf, 0xcd, 0x7d, 0x20, 0xb4, 0xe0, 0x94, 0xe3, 0xbd, 0xcd, 0x3a, 0x4a, 0x0b,
	0x0d, 0x43, 0x87, 0x92, 0x5f, 0x5d, 0x4c, 0x7e, 0x84, 0xc3, 0x3c, 0xcf, 0xf2, 0x7f, 0xb4, 0xd8,
	0xfa, 0xdc, 0x42, 0xde, 0x90, 0xf5, 0x02, 0x09, 0x42, 0xa7, 0x05, 0x8a, 0x22, 0x44, 0x70, 0x89,
	0x88, 0x81, 0x80, 0x0c, 0x38, 0xb5, 0xbd, 0xdb, 0xac, 0x23, 0x26, 0x91, 0x50, 0xb4, 0xe1, 0x80,
	0xe7, 0x41, 0x49, 0xc3, 0xad, 0xd1, 0xf0, 0x98, 0x1b, 0xa4, 0x21, 0x0c, 0x3b, 0x3b, 0xd6, 0xee,
	0x1a, 0xa7, 0xb6, 0xb7, 0xcd, 0xfa, 0xf8, 0x7b, 0x22, 0xd4, 0xe5, 0xb0, 0x4b, 0xfd, 0x65, 0xec,
	0x6d, 0x30, 0x47, 0x9c, 0x47, 0xc3, 0x1e, 0x2d, 0x81, 0x4d, 0xff, 0x0f, 0x8b, 0x6d, 0xcc, 0x33,
	0x41, 0x00, 0x49, 0x9a, 0x04, 0x40, 0x60, 0x5d, 0x9e, 0x07, 0xb8, 0xb0, 0x9a, 0x46, 0x41, 0x14,
	0x42, 0x48, 0x70, 0xfb, 0xbc, 0x8c, 0xbd, 0x2d, 0xd6, 0xbd, 0x90, 0xe9, 0x73, 0x48, 0x08, 0xb3,
	0xcb, 0x4d, 0xe4, 0xed, 0xb0, 0x55, 0xa5, 0x53, 0x29, 0xc6, 0x39, 0x1e, 0x97, 0xf0, 0xd4, 0xbb,
	0xbc, 0x0f, 0x59, 0xcf, 0x84, 0xc3, 0xce, 0x8e, 0xb3, 0xbb, 0x7a, 0xf0, 0xc6, 0x92, 0xfa, 0xee,
	0x3f, 0xca, 0xd3, 0x46, 0x89, 0x96, 0x33, 0x5e, 0x4c, 0xda, 0xbe, 0xcf, 0xd6, 0xea, 0x03, 0x48,
	0xf1, 0x29, 0xcc, 0x4c, 0x99, 0xb1, 0x89, 0x6c, 0xae, 0xc4, 0x64, 0x9a, 0xd7, 0x78, 0x8d, 0xe7,
	0xc1, 0x7d, 0xfb, 0x7d, 0xcb, 0x7f, 0x61, 0x37, 0xf4, 0x72, 0x18, 0xe8, 0x28, 0x4d, 0xbc, 0xb7,
	0x98, 0x0b, 0xd7, 0x10, 0xd0, 0x12, 0xad, 0xda, 0x18, 0x5d, 0x43, 0x70, 0xb2, 0xc2, 0x29, 0xcb,
	0x7b, 0x8f, 0xf5, 0x42, 0x50, 0x5a, 0xa6, 0x33, 0x23, 0xa6, 0xd7, 0x5a, 0xc4, 0x94, 0x27, 0x9c,
	0xac, 0xf0, 0x22, 0xd7, 0x3b, 0xc0, 0x82, 0x01, 0x3c, 0x2f, 0x54, 0x35, 0x5c, 0x9c, 0xf5, 0x31,
	0x8d, 0x9f, 0xac, 0x70, 0x93, 0x89, 0x5b, 0x49, 0x98, 0x80, 0x50, 0x40, 0x85, 0x6c, 0xdd, 0x8a,
	0xe7, 0x09, 0xb8, 0x95, 0xc9, 0xc5, 0xad, 0xa6, 0x59, 0x88, 0x02, 0xee, 0x2c, 0xdb, 0xea, 0x31,
	0x8d, 0xe3, 0x56, 0x79, 0xa6, 0x77, 0x8b, 0xd9, 0x7a, 0x46, 0xf2, 0xe9, 0x70, 0x5b, 0xcf, 0x3e,
	0xea, 0x99, 0x1a, 0xfa, 0x3f, 0x35, 0xd5, 0x8d, 0xa5, 0xc0, 0x8f, 0x2f, 0xe2, 0x74, 0x9a, 0x68,
	0xa3, 0x17, 0x13, 0xa1, 0x60, 0xc6, 0x42, 0x7d, 0x1a, 0xc5, 0x91, 0xa6, 0xda, 0xb8, 0xbc, 0x8c,
	0xcd, 0xd8, 0xe7, 0x32, 0x0a, 0xf2, 0x0a, 0xfc, 0x8f, 0x97, 0x71, 0xa9, 0x6a, 0xb7, 0xa6, 0x6a,
	0x8f, 0xb9, 0x99, 0x90, 0xa2, 0x50, 0x3a, 0xb6, 0xab, 0x73, 0xd2, 0x9d, 0x3b, 0x27, 0x49, 0xaa,
	0xc1, 0x88, 0x9c, 0xda, 0xfe, 0xcf, 0x4d, 0x63, 0xc8, 0xe9, 0xb6, 0x1a, 0x43, 0xc5, 0xc5, 0x5e,
	0xca, 0xc5, 0xb9, 0x81, 0x8b, 0xbb, 0x84, 0x4b, 0xfd, 0x84, 0xfe, 0x75, 0xdc, 0xbb, 0xcc, 0x5b,
	0x94, 0x51, 0x1b, 0x6e, 0xff, 0x5e, 0x83, 0x60, 0x2e, 0x9d, 0xd6, 0xc4, 0xe6, 0x92, 0x46, 0x2e,
	0xad, 0x99, 0xbf, 0x58, 0xcc, 0xe3, 0x10, 0x40, 0x94, 0xe9, 0xda, 0x0c, 0xac, 0x50, 0x20, 0x26,
	0x13, 0x28, 0x92, 0x4d, 0xe4, 0xf9, 0x6c, 0xad, 0x70, 0xe5, 0x87, 0x95, 0xa3, 0x35, 0xfa, 0xea,
	0x39, 0x87, 0xb8, 0x9d, 0xd3, 0xcc, 0xc1, 0x3e, 0xf4, 0xca, 0xa9, 0x82, 0xf0, 0x58, 0x28, 0x2a,
	0xa6, 0xcb, 0x8b, 0x10, 0x8f, 0xb6, 0x04, 0x6d, 0x4a, 0x89, 0x4d, 0xcc, 0x7d, 0xa2, 0xd2, 0x84,
	0x83, 0x36, 0xb5, 0x2c, 0x42, 0xff, 0x82, 0x68, 0x92, 0x71, 0x1c, 0x5d, 0x8a, 0x64, 0x0c, 0x9f,
	0x68, 0x88, 0x5b, 0xcc, 0x61, 0x9b, 0xf5, 0x33, 0x09, 0x67, 0x35, 0x7f, 0x28, 0x63, 0x42, 0x3b,
	0x95, 0x12, 0x12, 0x9d, 0x8f, 0x3b, 0x34, 0xde, 0xe8, 0xf3, 0xbf, 0xb7, 0x9a, 0x9f, 0x48, 0x68,
	0x71, 0x14, 0x87, 0xff, 0x8a, 0xe1, 0x0f, 0x96, 0x18, 0xfe, 0xa0, 0x32, 0x7c, 0xff, 0x77, 0x8b,
	0xfd, 0x7f, 0xde, 0x48, 0x11, 0xdf, 0xcb, 0x3b, 0xfc, 0x9c, 0x93, 0xe7, 0x48, 0x1b, 0x4e, 0x7e,
	0x58, 0x39, 0xb9, 0x4b, 0x4e, 0x7e, 0x6f, 0x89, 0x93, 0x1f, 0xc5, 0xe1, 0x3f, 0x63, 0xe6, 0x83,
	0xba, 0x99, 0xff, 0x60, 0xb1, 0x57, 0x16, 0xe5, 0x8a, 0x64, 0xff, 0x13, 0x8a, 0x1d, 0x90, 0x62,
	0xfd, 0xbb, 0x6c, 0xfd, 0xe8, 0x12, 0x82, 0xa7, 0xa3, 0xb3, 0x53, 0x9c, 0xcb, 0xe1, 0xeb, 0xd6,
	0xb3, 0xf7, 0x9d, 0xc5, 0x36, 0x9a, 0x79, 0x2a, 0xcb, 0x3f, 0x74, 0xbe, 0x2f, 0x25, 0xf7, 0x79,
	0x19, 0x2f, 0xe0, 0xb4, 0x5b, 0x70, 0xce, 0xf3, 0x75, 0x5a, 0xf8, 0xde, 0x61, 0x03, 0x52, 0x1f,
	0x25, 0xe4, 0xca, 0xab, 0x3a, 0xfc, 0x31, 0xdb, 0x1c, 0x29, 0x1d, 0xc5, 0x42, 0xc3, 0xe8, 0xec,
	0xf4, 0x58, 0x28, 0xc4, 0x8f, 0x77, 0x45, 0x6a, 0xd0, 0xdb, 0x3a, 0x2d, 0xad, 0xda, 0xae, 0x59,
	0x75, 0xf5, 0x09, 0x9c, 0xc6, 0x27, 0xa8, 0xec, 0xd6, 0xad, 0xdb, 0xad, 0xff, 0x26, 0xf3, 0xe6,
	0x37, 0x52, 0x19, 0x96, 0x73, 0x2c, 0x94, 0xd1, 0x2c, 0x36, 0xfd, 0xbb, 0x6c, 0x75, 0x74, 0x15,
	0x3f, 0x80, 0xf3, 0xe9, 0x18, 0xa1, 0x6c, 0xb1, 0x6e, 0x9a, 0xa1, 0xe8, 0x28, 0xa7, 0xc3, 0x4d,
	0xe4, 0xbf, 0xc3, 0xd6, 0xaa, 0x34, 0x95, 0xa1, 0x98, 0x43, 0x0c, 0x50, 0x8e, 0x53, 0x65, 0xb0,
	0xd7, 0xbb, 0xfc, 0x3d, 0x76, 0x6b, 0x74, 0x15, 0x7f, 0x31, 0x05, 0x39, 0x3b, 0x3c, 0x8f, 0x70,
	0xed, 0x21, 0xeb, 0xe1, 0xa7, 0x01, 0x55, 0xe4, 0x17, 0xa1, 0xff, 0x01, 0x5b, 0x6f, 0xe4, 0xaa,
	0x6c, 0x79, 0x72, 0xf1, 0x04, 0xb3, 0xab, 0x27, 0xd8, 0x63, 0xe2, 0x40, 0xd3, 0x6f, 0xdc, 0x07,
	0xb5, 0x1f, 0x25, 0xd9, 0x54, 0x17, 0xda, 0xa7, 0x60, 0x59, 0x69, 0xfd, 0x6f, 0x2d, 0x22, 0x6d,
	0xd6, 0xbd, 0x11, 0xd3, 0x4b, 0x2d, 0x8c, 0xeb, 0x48, 0xf1, 0x0c, 0x9d, 0xce, 0x08, 0xa4, 0x08,
	0x51, 0xa0, 0xe8, 0xbf, 0x34, 0x94, 0x6b, 0xbe, 0x8c, 0xfd, 0x5f, 0x2d, 0x76, 0x7b, 0x74, 0x15,
	0x97, 0xe7, 0x12, 0xed, 0x10, 0x8c, 0xfc, 0xc9, 0xd2, 0xac, 0x9a, 0xa5, 0x6d, 0x30, 0xe7, 0x02,
	0xf2, 0x03, 0xe9, 0x70, 0x6c, 0x96, 0xb7, 0xa3, 0x53, 0xdd, 0x8e, 0x95, 0x6d, 0xba, 0x75, 0xdb,
	0xac, 0x60, 0x77, 0x1a, 0xb0, 0xef, 0xb0, 0x01, 0x4a, 0x31, 0x06, 0x0d, 0xd2, 0xf8, 0x64, 0xd5,
	0x81, 0xb3, 0xe0, 0x3a, 0x8b, 0x64, 0x71, 0xff, 0x9a, 0x88, 0xee, 0x07, 0x21, 0x05, 0x1d, 0x87,
	0x7e, 0x4e, 0xa9, 0x88, 0xfd, 0xdf, 0xd0, 0xfb, 0x6b, 0x94, 0xc4, 0x64, 0x62, 0x44, 0xd8, 0xfa,
	0x1c, 0x2a, 0x88, 0xda, 0x8b, 0x44, 0x9d, 0x45, 0xa2, 0x6e, 0x8d, 0xe8, 0xdf, 0xa3, 0xe4, 0x99,
	0x77, 0xac, 0x79, 0x50, 0x80, 0x79, 0xaa, 0x19, 0x9a, 0xfd, 0xa5, 0x34, 0x07, 0x73, 0x34, 0x5f,
	0x58, 0x6c, 0xab, 0x46, 0xf3, 0x4b, 0x29, 0x12, 0x75, 0x01, 0xd2, 0x50, 0x6d, 0x75, 0xd6, 0xe6,
	0x2b, 0xca, 0xae, 0x97, 0x80, 0x20, 0x39, 0xad, 0x90, 0xdc, 0x06, 0xa4, 0xd7, 0x19, 0x8b, 0xd4,
	0x57, 0x91, 0xbe, 0x0c, 0xa5, 0x78, 0x46, 0xc4, 0xfb, 0xbc, 0xd6, 0xd3, 0x80, 0xdc, 0x9d, 0x83,
	0x9c, 0x9f, 0xde, 0x63, 0xd0, 0x0f, 0xf1, 0x5e, 0xbb, 0xf9, 0xf4, 0xee, 0xd1, 0x47, 0xac, 0x72,
	0x55, 0x96, 0xaa, 0xb9, 0xbf, 0x40, 0x8e, 0xb9, 0x20, 0xcf, 0xbb, 0xf4, 0x77, 0xf3, 0xdd, 0x3f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x79, 0xdb, 0x1e, 0x63, 0x83, 0x0e, 0x00, 0x00,
}
