// Code generated by protoc-gen-go. DO NOT EDIT.
// source: x2ethereum.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EthBridgeStatus int32

const (
	EthBridgeStatus_PendingStatusText    EthBridgeStatus = 0
	EthBridgeStatus_SuccessStatusText    EthBridgeStatus = 1
	EthBridgeStatus_FailedStatusText     EthBridgeStatus = 2
	EthBridgeStatus_WithdrawedStatusText EthBridgeStatus = 3
)

var EthBridgeStatus_name = map[int32]string{
	0: "PendingStatusText",
	1: "SuccessStatusText",
	2: "FailedStatusText",
	3: "WithdrawedStatusText",
}
var EthBridgeStatus_value = map[string]int32{
	"PendingStatusText":    0,
	"SuccessStatusText":    1,
	"FailedStatusText":     2,
	"WithdrawedStatusText": 3,
}

func (x EthBridgeStatus) String() string {
	return proto.EnumName(EthBridgeStatus_name, int32(x))
}
func (EthBridgeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{0}
}

type X2EthereumAction struct {
	// Types that are valid to be assigned to Value:
	//	*X2EthereumAction_Eth2Chain33
	//	*X2EthereumAction_WithdrawEth
	//	*X2EthereumAction_WithdrawChain33
	//	*X2EthereumAction_Chain33ToEth
	//	*X2EthereumAction_AddValidator
	//	*X2EthereumAction_RemoveValidator
	//	*X2EthereumAction_ModifyPower
	//	*X2EthereumAction_SetConsensusThreshold
	Value                isX2EthereumAction_Value `protobuf_oneof:"value"`
	Ty                   int32                    `protobuf:"varint,10,opt,name=ty" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *X2EthereumAction) Reset()         { *m = X2EthereumAction{} }
func (m *X2EthereumAction) String() string { return proto.CompactTextString(m) }
func (*X2EthereumAction) ProtoMessage()    {}
func (*X2EthereumAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{0}
}
func (m *X2EthereumAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_X2EthereumAction.Unmarshal(m, b)
}
func (m *X2EthereumAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_X2EthereumAction.Marshal(b, m, deterministic)
}
func (dst *X2EthereumAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_X2EthereumAction.Merge(dst, src)
}
func (m *X2EthereumAction) XXX_Size() int {
	return xxx_messageInfo_X2EthereumAction.Size(m)
}
func (m *X2EthereumAction) XXX_DiscardUnknown() {
	xxx_messageInfo_X2EthereumAction.DiscardUnknown(m)
}

var xxx_messageInfo_X2EthereumAction proto.InternalMessageInfo

type isX2EthereumAction_Value interface {
	isX2EthereumAction_Value()
}

type X2EthereumAction_Eth2Chain33 struct {
	Eth2Chain33 *Eth2Chain33 `protobuf:"bytes,1,opt,name=eth2Chain33,oneof"`
}
type X2EthereumAction_WithdrawEth struct {
	WithdrawEth *Eth2Chain33 `protobuf:"bytes,2,opt,name=withdrawEth,oneof"`
}
type X2EthereumAction_WithdrawChain33 struct {
	WithdrawChain33 *Chain33ToEth `protobuf:"bytes,3,opt,name=withdrawChain33,oneof"`
}
type X2EthereumAction_Chain33ToEth struct {
	Chain33ToEth *Chain33ToEth `protobuf:"bytes,4,opt,name=chain33ToEth,oneof"`
}
type X2EthereumAction_AddValidator struct {
	AddValidator *MsgValidator `protobuf:"bytes,5,opt,name=addValidator,oneof"`
}
type X2EthereumAction_RemoveValidator struct {
	RemoveValidator *MsgValidator `protobuf:"bytes,6,opt,name=removeValidator,oneof"`
}
type X2EthereumAction_ModifyPower struct {
	ModifyPower *MsgValidator `protobuf:"bytes,7,opt,name=modifyPower,oneof"`
}
type X2EthereumAction_SetConsensusThreshold struct {
	SetConsensusThreshold *MsgConsensusThreshold `protobuf:"bytes,8,opt,name=setConsensusThreshold,oneof"`
}

func (*X2EthereumAction_Eth2Chain33) isX2EthereumAction_Value()           {}
func (*X2EthereumAction_WithdrawEth) isX2EthereumAction_Value()           {}
func (*X2EthereumAction_WithdrawChain33) isX2EthereumAction_Value()       {}
func (*X2EthereumAction_Chain33ToEth) isX2EthereumAction_Value()          {}
func (*X2EthereumAction_AddValidator) isX2EthereumAction_Value()          {}
func (*X2EthereumAction_RemoveValidator) isX2EthereumAction_Value()       {}
func (*X2EthereumAction_ModifyPower) isX2EthereumAction_Value()           {}
func (*X2EthereumAction_SetConsensusThreshold) isX2EthereumAction_Value() {}

func (m *X2EthereumAction) GetValue() isX2EthereumAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *X2EthereumAction) GetEth2Chain33() *Eth2Chain33 {
	if x, ok := m.GetValue().(*X2EthereumAction_Eth2Chain33); ok {
		return x.Eth2Chain33
	}
	return nil
}

func (m *X2EthereumAction) GetWithdrawEth() *Eth2Chain33 {
	if x, ok := m.GetValue().(*X2EthereumAction_WithdrawEth); ok {
		return x.WithdrawEth
	}
	return nil
}

func (m *X2EthereumAction) GetWithdrawChain33() *Chain33ToEth {
	if x, ok := m.GetValue().(*X2EthereumAction_WithdrawChain33); ok {
		return x.WithdrawChain33
	}
	return nil
}

func (m *X2EthereumAction) GetChain33ToEth() *Chain33ToEth {
	if x, ok := m.GetValue().(*X2EthereumAction_Chain33ToEth); ok {
		return x.Chain33ToEth
	}
	return nil
}

func (m *X2EthereumAction) GetAddValidator() *MsgValidator {
	if x, ok := m.GetValue().(*X2EthereumAction_AddValidator); ok {
		return x.AddValidator
	}
	return nil
}

func (m *X2EthereumAction) GetRemoveValidator() *MsgValidator {
	if x, ok := m.GetValue().(*X2EthereumAction_RemoveValidator); ok {
		return x.RemoveValidator
	}
	return nil
}

func (m *X2EthereumAction) GetModifyPower() *MsgValidator {
	if x, ok := m.GetValue().(*X2EthereumAction_ModifyPower); ok {
		return x.ModifyPower
	}
	return nil
}

func (m *X2EthereumAction) GetSetConsensusThreshold() *MsgConsensusThreshold {
	if x, ok := m.GetValue().(*X2EthereumAction_SetConsensusThreshold); ok {
		return x.SetConsensusThreshold
	}
	return nil
}

func (m *X2EthereumAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*X2EthereumAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _X2EthereumAction_OneofMarshaler, _X2EthereumAction_OneofUnmarshaler, _X2EthereumAction_OneofSizer, []interface{}{
		(*X2EthereumAction_Eth2Chain33)(nil),
		(*X2EthereumAction_WithdrawEth)(nil),
		(*X2EthereumAction_WithdrawChain33)(nil),
		(*X2EthereumAction_Chain33ToEth)(nil),
		(*X2EthereumAction_AddValidator)(nil),
		(*X2EthereumAction_RemoveValidator)(nil),
		(*X2EthereumAction_ModifyPower)(nil),
		(*X2EthereumAction_SetConsensusThreshold)(nil),
	}
}

func _X2EthereumAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*X2EthereumAction)
	// value
	switch x := m.Value.(type) {
	case *X2EthereumAction_Eth2Chain33:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Eth2Chain33); err != nil {
			return err
		}
	case *X2EthereumAction_WithdrawEth:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WithdrawEth); err != nil {
			return err
		}
	case *X2EthereumAction_WithdrawChain33:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WithdrawChain33); err != nil {
			return err
		}
	case *X2EthereumAction_Chain33ToEth:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Chain33ToEth); err != nil {
			return err
		}
	case *X2EthereumAction_AddValidator:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AddValidator); err != nil {
			return err
		}
	case *X2EthereumAction_RemoveValidator:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoveValidator); err != nil {
			return err
		}
	case *X2EthereumAction_ModifyPower:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ModifyPower); err != nil {
			return err
		}
	case *X2EthereumAction_SetConsensusThreshold:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetConsensusThreshold); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("X2EthereumAction.Value has unexpected type %T", x)
	}
	return nil
}

func _X2EthereumAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*X2EthereumAction)
	switch tag {
	case 1: // value.eth2Chain33
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Eth2Chain33)
		err := b.DecodeMessage(msg)
		m.Value = &X2EthereumAction_Eth2Chain33{msg}
		return true, err
	case 2: // value.withdrawEth
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Eth2Chain33)
		err := b.DecodeMessage(msg)
		m.Value = &X2EthereumAction_WithdrawEth{msg}
		return true, err
	case 3: // value.withdrawChain33
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Chain33ToEth)
		err := b.DecodeMessage(msg)
		m.Value = &X2EthereumAction_WithdrawChain33{msg}
		return true, err
	case 4: // value.chain33ToEth
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Chain33ToEth)
		err := b.DecodeMessage(msg)
		m.Value = &X2EthereumAction_Chain33ToEth{msg}
		return true, err
	case 5: // value.addValidator
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MsgValidator)
		err := b.DecodeMessage(msg)
		m.Value = &X2EthereumAction_AddValidator{msg}
		return true, err
	case 6: // value.removeValidator
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MsgValidator)
		err := b.DecodeMessage(msg)
		m.Value = &X2EthereumAction_RemoveValidator{msg}
		return true, err
	case 7: // value.modifyPower
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MsgValidator)
		err := b.DecodeMessage(msg)
		m.Value = &X2EthereumAction_ModifyPower{msg}
		return true, err
	case 8: // value.setConsensusThreshold
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MsgConsensusThreshold)
		err := b.DecodeMessage(msg)
		m.Value = &X2EthereumAction_SetConsensusThreshold{msg}
		return true, err
	default:
		return false, nil
	}
}

func _X2EthereumAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*X2EthereumAction)
	// value
	switch x := m.Value.(type) {
	case *X2EthereumAction_Eth2Chain33:
		s := proto.Size(x.Eth2Chain33)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *X2EthereumAction_WithdrawEth:
		s := proto.Size(x.WithdrawEth)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *X2EthereumAction_WithdrawChain33:
		s := proto.Size(x.WithdrawChain33)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *X2EthereumAction_Chain33ToEth:
		s := proto.Size(x.Chain33ToEth)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *X2EthereumAction_AddValidator:
		s := proto.Size(x.AddValidator)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *X2EthereumAction_RemoveValidator:
		s := proto.Size(x.RemoveValidator)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *X2EthereumAction_ModifyPower:
		s := proto.Size(x.ModifyPower)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *X2EthereumAction_SetConsensusThreshold:
		s := proto.Size(x.SetConsensusThreshold)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MsgConsensusThreshold struct {
	ConsensusThreshold   int64    `protobuf:"varint,1,opt,name=consensusThreshold" json:"consensusThreshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgConsensusThreshold) Reset()         { *m = MsgConsensusThreshold{} }
func (m *MsgConsensusThreshold) String() string { return proto.CompactTextString(m) }
func (*MsgConsensusThreshold) ProtoMessage()    {}
func (*MsgConsensusThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{1}
}
func (m *MsgConsensusThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgConsensusThreshold.Unmarshal(m, b)
}
func (m *MsgConsensusThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgConsensusThreshold.Marshal(b, m, deterministic)
}
func (dst *MsgConsensusThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConsensusThreshold.Merge(dst, src)
}
func (m *MsgConsensusThreshold) XXX_Size() int {
	return xxx_messageInfo_MsgConsensusThreshold.Size(m)
}
func (m *MsgConsensusThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConsensusThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConsensusThreshold proto.InternalMessageInfo

func (m *MsgConsensusThreshold) GetConsensusThreshold() int64 {
	if m != nil {
		return m.ConsensusThreshold
	}
	return 0
}

type MsgValidator struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Power                int64    `protobuf:"varint,2,opt,name=power" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgValidator) Reset()         { *m = MsgValidator{} }
func (m *MsgValidator) String() string { return proto.CompactTextString(m) }
func (*MsgValidator) ProtoMessage()    {}
func (*MsgValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{2}
}
func (m *MsgValidator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgValidator.Unmarshal(m, b)
}
func (m *MsgValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgValidator.Marshal(b, m, deterministic)
}
func (dst *MsgValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgValidator.Merge(dst, src)
}
func (m *MsgValidator) XXX_Size() int {
	return xxx_messageInfo_MsgValidator.Size(m)
}
func (m *MsgValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgValidator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgValidator proto.InternalMessageInfo

func (m *MsgValidator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgValidator) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

// EthBridgeClaim is a structure that contains all the data for a particular bridge claim
type Eth2Chain33 struct {
	EthereumChainID       int64    `protobuf:"varint,1,opt,name=EthereumChainID" json:"EthereumChainID,omitempty"`
	BridgeContractAddress string   `protobuf:"bytes,2,opt,name=BridgeContractAddress" json:"BridgeContractAddress,omitempty"`
	Nonce                 int64    `protobuf:"varint,3,opt,name=Nonce" json:"Nonce,omitempty"`
	LocalCoinSymbol       string   `protobuf:"bytes,4,opt,name=localCoinSymbol" json:"localCoinSymbol,omitempty"`
	LocalCoinExec         string   `protobuf:"bytes,5,opt,name=localCoinExec" json:"localCoinExec,omitempty"`
	TokenContractAddress  string   `protobuf:"bytes,6,opt,name=TokenContractAddress" json:"TokenContractAddress,omitempty"`
	EthereumSender        string   `protobuf:"bytes,7,opt,name=EthereumSender" json:"EthereumSender,omitempty"`
	Chain33Receiver       string   `protobuf:"bytes,8,opt,name=Chain33Receiver" json:"Chain33Receiver,omitempty"`
	ValidatorAddress      string   `protobuf:"bytes,9,opt,name=ValidatorAddress" json:"ValidatorAddress,omitempty"`
	Amount                uint64   `protobuf:"varint,10,opt,name=Amount" json:"Amount,omitempty"`
	ClaimType             int64    `protobuf:"varint,11,opt,name=ClaimType" json:"ClaimType,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Eth2Chain33) Reset()         { *m = Eth2Chain33{} }
func (m *Eth2Chain33) String() string { return proto.CompactTextString(m) }
func (*Eth2Chain33) ProtoMessage()    {}
func (*Eth2Chain33) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{3}
}
func (m *Eth2Chain33) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Eth2Chain33.Unmarshal(m, b)
}
func (m *Eth2Chain33) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Eth2Chain33.Marshal(b, m, deterministic)
}
func (dst *Eth2Chain33) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Eth2Chain33.Merge(dst, src)
}
func (m *Eth2Chain33) XXX_Size() int {
	return xxx_messageInfo_Eth2Chain33.Size(m)
}
func (m *Eth2Chain33) XXX_DiscardUnknown() {
	xxx_messageInfo_Eth2Chain33.DiscardUnknown(m)
}

var xxx_messageInfo_Eth2Chain33 proto.InternalMessageInfo

func (m *Eth2Chain33) GetEthereumChainID() int64 {
	if m != nil {
		return m.EthereumChainID
	}
	return 0
}

func (m *Eth2Chain33) GetBridgeContractAddress() string {
	if m != nil {
		return m.BridgeContractAddress
	}
	return ""
}

func (m *Eth2Chain33) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Eth2Chain33) GetLocalCoinSymbol() string {
	if m != nil {
		return m.LocalCoinSymbol
	}
	return ""
}

func (m *Eth2Chain33) GetLocalCoinExec() string {
	if m != nil {
		return m.LocalCoinExec
	}
	return ""
}

func (m *Eth2Chain33) GetTokenContractAddress() string {
	if m != nil {
		return m.TokenContractAddress
	}
	return ""
}

func (m *Eth2Chain33) GetEthereumSender() string {
	if m != nil {
		return m.EthereumSender
	}
	return ""
}

func (m *Eth2Chain33) GetChain33Receiver() string {
	if m != nil {
		return m.Chain33Receiver
	}
	return ""
}

func (m *Eth2Chain33) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *Eth2Chain33) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Eth2Chain33) GetClaimType() int64 {
	if m != nil {
		return m.ClaimType
	}
	return 0
}

// OracleClaimContent is the details of how the content of the claim for each validator will be stored in the oracle
type OracleClaimContent struct {
	Chain33Receiver      string   `protobuf:"bytes,1,opt,name=Chain33Receiver" json:"Chain33Receiver,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=Amount" json:"Amount,omitempty"`
	ClaimType            int64    `protobuf:"varint,3,opt,name=ClaimType" json:"ClaimType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OracleClaimContent) Reset()         { *m = OracleClaimContent{} }
func (m *OracleClaimContent) String() string { return proto.CompactTextString(m) }
func (*OracleClaimContent) ProtoMessage()    {}
func (*OracleClaimContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{4}
}
func (m *OracleClaimContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OracleClaimContent.Unmarshal(m, b)
}
func (m *OracleClaimContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OracleClaimContent.Marshal(b, m, deterministic)
}
func (dst *OracleClaimContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleClaimContent.Merge(dst, src)
}
func (m *OracleClaimContent) XXX_Size() int {
	return xxx_messageInfo_OracleClaimContent.Size(m)
}
func (m *OracleClaimContent) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleClaimContent.DiscardUnknown(m)
}

var xxx_messageInfo_OracleClaimContent proto.InternalMessageInfo

func (m *OracleClaimContent) GetChain33Receiver() string {
	if m != nil {
		return m.Chain33Receiver
	}
	return ""
}

func (m *OracleClaimContent) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OracleClaimContent) GetClaimType() int64 {
	if m != nil {
		return m.ClaimType
	}
	return 0
}

// MsgBurn defines a message for burning coins and triggering a related event
type Chain33ToEth struct {
	TokenContract        string   `protobuf:"bytes,1,opt,name=TokenContract" json:"TokenContract,omitempty"`
	Chain33Sender        string   `protobuf:"bytes,2,opt,name=Chain33Sender" json:"Chain33Sender,omitempty"`
	EthereumReceiver     string   `protobuf:"bytes,3,opt,name=EthereumReceiver" json:"EthereumReceiver,omitempty"`
	Amount               uint64   `protobuf:"varint,4,opt,name=Amount" json:"Amount,omitempty"`
	LocalCoinSymbol      string   `protobuf:"bytes,5,opt,name=localCoinSymbol" json:"localCoinSymbol,omitempty"`
	LocalCoinExec        string   `protobuf:"bytes,6,opt,name=localCoinExec" json:"localCoinExec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chain33ToEth) Reset()         { *m = Chain33ToEth{} }
func (m *Chain33ToEth) String() string { return proto.CompactTextString(m) }
func (*Chain33ToEth) ProtoMessage()    {}
func (*Chain33ToEth) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{5}
}
func (m *Chain33ToEth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chain33ToEth.Unmarshal(m, b)
}
func (m *Chain33ToEth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chain33ToEth.Marshal(b, m, deterministic)
}
func (dst *Chain33ToEth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain33ToEth.Merge(dst, src)
}
func (m *Chain33ToEth) XXX_Size() int {
	return xxx_messageInfo_Chain33ToEth.Size(m)
}
func (m *Chain33ToEth) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain33ToEth.DiscardUnknown(m)
}

var xxx_messageInfo_Chain33ToEth proto.InternalMessageInfo

func (m *Chain33ToEth) GetTokenContract() string {
	if m != nil {
		return m.TokenContract
	}
	return ""
}

func (m *Chain33ToEth) GetChain33Sender() string {
	if m != nil {
		return m.Chain33Sender
	}
	return ""
}

func (m *Chain33ToEth) GetEthereumReceiver() string {
	if m != nil {
		return m.EthereumReceiver
	}
	return ""
}

func (m *Chain33ToEth) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Chain33ToEth) GetLocalCoinSymbol() string {
	if m != nil {
		return m.LocalCoinSymbol
	}
	return ""
}

func (m *Chain33ToEth) GetLocalCoinExec() string {
	if m != nil {
		return m.LocalCoinExec
	}
	return ""
}

// 回执接口定义
type ReceiptEth2Chain33 struct {
	EthereumChainID       int64    `protobuf:"varint,1,opt,name=EthereumChainID" json:"EthereumChainID,omitempty"`
	BridgeContractAddress string   `protobuf:"bytes,2,opt,name=BridgeContractAddress" json:"BridgeContractAddress,omitempty"`
	Nonce                 int64    `protobuf:"varint,3,opt,name=Nonce" json:"Nonce,omitempty"`
	LocalCoinSymbol       string   `protobuf:"bytes,4,opt,name=localCoinSymbol" json:"localCoinSymbol,omitempty"`
	LocalCoinExec         string   `protobuf:"bytes,5,opt,name=localCoinExec" json:"localCoinExec,omitempty"`
	TokenContractAddress  string   `protobuf:"bytes,6,opt,name=TokenContractAddress" json:"TokenContractAddress,omitempty"`
	EthereumSender        string   `protobuf:"bytes,7,opt,name=EthereumSender" json:"EthereumSender,omitempty"`
	Chain33Receiver       string   `protobuf:"bytes,8,opt,name=Chain33Receiver" json:"Chain33Receiver,omitempty"`
	ValidatorAddress      string   `protobuf:"bytes,9,opt,name=ValidatorAddress" json:"ValidatorAddress,omitempty"`
	Amount                uint64   `protobuf:"varint,10,opt,name=Amount" json:"Amount,omitempty"`
	ClaimType             int64    `protobuf:"varint,11,opt,name=ClaimType" json:"ClaimType,omitempty"`
	XTxHash               []byte   `protobuf:"bytes,12,opt,name=xTxHash,proto3" json:"xTxHash,omitempty"`
	XHeight               uint64   `protobuf:"varint,13,opt,name=xHeight" json:"xHeight,omitempty"`
	ProphecyID            string   `protobuf:"bytes,14,opt,name=ProphecyID" json:"ProphecyID,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ReceiptEth2Chain33) Reset()         { *m = ReceiptEth2Chain33{} }
func (m *ReceiptEth2Chain33) String() string { return proto.CompactTextString(m) }
func (*ReceiptEth2Chain33) ProtoMessage()    {}
func (*ReceiptEth2Chain33) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{6}
}
func (m *ReceiptEth2Chain33) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptEth2Chain33.Unmarshal(m, b)
}
func (m *ReceiptEth2Chain33) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptEth2Chain33.Marshal(b, m, deterministic)
}
func (dst *ReceiptEth2Chain33) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptEth2Chain33.Merge(dst, src)
}
func (m *ReceiptEth2Chain33) XXX_Size() int {
	return xxx_messageInfo_ReceiptEth2Chain33.Size(m)
}
func (m *ReceiptEth2Chain33) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptEth2Chain33.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptEth2Chain33 proto.InternalMessageInfo

func (m *ReceiptEth2Chain33) GetEthereumChainID() int64 {
	if m != nil {
		return m.EthereumChainID
	}
	return 0
}

func (m *ReceiptEth2Chain33) GetBridgeContractAddress() string {
	if m != nil {
		return m.BridgeContractAddress
	}
	return ""
}

func (m *ReceiptEth2Chain33) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ReceiptEth2Chain33) GetLocalCoinSymbol() string {
	if m != nil {
		return m.LocalCoinSymbol
	}
	return ""
}

func (m *ReceiptEth2Chain33) GetLocalCoinExec() string {
	if m != nil {
		return m.LocalCoinExec
	}
	return ""
}

func (m *ReceiptEth2Chain33) GetTokenContractAddress() string {
	if m != nil {
		return m.TokenContractAddress
	}
	return ""
}

func (m *ReceiptEth2Chain33) GetEthereumSender() string {
	if m != nil {
		return m.EthereumSender
	}
	return ""
}

func (m *ReceiptEth2Chain33) GetChain33Receiver() string {
	if m != nil {
		return m.Chain33Receiver
	}
	return ""
}

func (m *ReceiptEth2Chain33) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *ReceiptEth2Chain33) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReceiptEth2Chain33) GetClaimType() int64 {
	if m != nil {
		return m.ClaimType
	}
	return 0
}

func (m *ReceiptEth2Chain33) GetXTxHash() []byte {
	if m != nil {
		return m.XTxHash
	}
	return nil
}

func (m *ReceiptEth2Chain33) GetXHeight() uint64 {
	if m != nil {
		return m.XHeight
	}
	return 0
}

func (m *ReceiptEth2Chain33) GetProphecyID() string {
	if m != nil {
		return m.ProphecyID
	}
	return ""
}

type ReceiptChain33ToEth struct {
	TokenContract        string   `protobuf:"bytes,1,opt,name=TokenContract" json:"TokenContract,omitempty"`
	Chain33Sender        string   `protobuf:"bytes,2,opt,name=Chain33Sender" json:"Chain33Sender,omitempty"`
	EthereumReceiver     string   `protobuf:"bytes,3,opt,name=EthereumReceiver" json:"EthereumReceiver,omitempty"`
	Amount               uint64   `protobuf:"varint,4,opt,name=Amount" json:"Amount,omitempty"`
	EthSymbol            string   `protobuf:"bytes,5,opt,name=EthSymbol" json:"EthSymbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptChain33ToEth) Reset()         { *m = ReceiptChain33ToEth{} }
func (m *ReceiptChain33ToEth) String() string { return proto.CompactTextString(m) }
func (*ReceiptChain33ToEth) ProtoMessage()    {}
func (*ReceiptChain33ToEth) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{7}
}
func (m *ReceiptChain33ToEth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptChain33ToEth.Unmarshal(m, b)
}
func (m *ReceiptChain33ToEth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptChain33ToEth.Marshal(b, m, deterministic)
}
func (dst *ReceiptChain33ToEth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptChain33ToEth.Merge(dst, src)
}
func (m *ReceiptChain33ToEth) XXX_Size() int {
	return xxx_messageInfo_ReceiptChain33ToEth.Size(m)
}
func (m *ReceiptChain33ToEth) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptChain33ToEth.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptChain33ToEth proto.InternalMessageInfo

func (m *ReceiptChain33ToEth) GetTokenContract() string {
	if m != nil {
		return m.TokenContract
	}
	return ""
}

func (m *ReceiptChain33ToEth) GetChain33Sender() string {
	if m != nil {
		return m.Chain33Sender
	}
	return ""
}

func (m *ReceiptChain33ToEth) GetEthereumReceiver() string {
	if m != nil {
		return m.EthereumReceiver
	}
	return ""
}

func (m *ReceiptChain33ToEth) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReceiptChain33ToEth) GetEthSymbol() string {
	if m != nil {
		return m.EthSymbol
	}
	return ""
}

type ReceiptValidator struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Power                int64    `protobuf:"varint,2,opt,name=power" json:"power,omitempty"`
	XTxHash              []byte   `protobuf:"bytes,3,opt,name=xTxHash,proto3" json:"xTxHash,omitempty"`
	XHeight              uint64   `protobuf:"varint,4,opt,name=xHeight" json:"xHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptValidator) Reset()         { *m = ReceiptValidator{} }
func (m *ReceiptValidator) String() string { return proto.CompactTextString(m) }
func (*ReceiptValidator) ProtoMessage()    {}
func (*ReceiptValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{8}
}
func (m *ReceiptValidator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptValidator.Unmarshal(m, b)
}
func (m *ReceiptValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptValidator.Marshal(b, m, deterministic)
}
func (dst *ReceiptValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptValidator.Merge(dst, src)
}
func (m *ReceiptValidator) XXX_Size() int {
	return xxx_messageInfo_ReceiptValidator.Size(m)
}
func (m *ReceiptValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptValidator.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptValidator proto.InternalMessageInfo

func (m *ReceiptValidator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReceiptValidator) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *ReceiptValidator) GetXTxHash() []byte {
	if m != nil {
		return m.XTxHash
	}
	return nil
}

func (m *ReceiptValidator) GetXHeight() uint64 {
	if m != nil {
		return m.XHeight
	}
	return 0
}

type ReceiptSetConsensusThreshold struct {
	PreConsensusThreshold int64    `protobuf:"varint,1,opt,name=preConsensusThreshold" json:"preConsensusThreshold,omitempty"`
	NowConsensusThreshold int64    `protobuf:"varint,2,opt,name=nowConsensusThreshold" json:"nowConsensusThreshold,omitempty"`
	XTxHash               []byte   `protobuf:"bytes,3,opt,name=xTxHash,proto3" json:"xTxHash,omitempty"`
	XHeight               uint64   `protobuf:"varint,4,opt,name=xHeight" json:"xHeight,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ReceiptSetConsensusThreshold) Reset()         { *m = ReceiptSetConsensusThreshold{} }
func (m *ReceiptSetConsensusThreshold) String() string { return proto.CompactTextString(m) }
func (*ReceiptSetConsensusThreshold) ProtoMessage()    {}
func (*ReceiptSetConsensusThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{9}
}
func (m *ReceiptSetConsensusThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptSetConsensusThreshold.Unmarshal(m, b)
}
func (m *ReceiptSetConsensusThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptSetConsensusThreshold.Marshal(b, m, deterministic)
}
func (dst *ReceiptSetConsensusThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptSetConsensusThreshold.Merge(dst, src)
}
func (m *ReceiptSetConsensusThreshold) XXX_Size() int {
	return xxx_messageInfo_ReceiptSetConsensusThreshold.Size(m)
}
func (m *ReceiptSetConsensusThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptSetConsensusThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptSetConsensusThreshold proto.InternalMessageInfo

func (m *ReceiptSetConsensusThreshold) GetPreConsensusThreshold() int64 {
	if m != nil {
		return m.PreConsensusThreshold
	}
	return 0
}

func (m *ReceiptSetConsensusThreshold) GetNowConsensusThreshold() int64 {
	if m != nil {
		return m.NowConsensusThreshold
	}
	return 0
}

func (m *ReceiptSetConsensusThreshold) GetXTxHash() []byte {
	if m != nil {
		return m.XTxHash
	}
	return nil
}

func (m *ReceiptSetConsensusThreshold) GetXHeight() uint64 {
	if m != nil {
		return m.XHeight
	}
	return 0
}

// 查询接口定义
type QueryEthProphecyParams struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryEthProphecyParams) Reset()         { *m = QueryEthProphecyParams{} }
func (m *QueryEthProphecyParams) String() string { return proto.CompactTextString(m) }
func (*QueryEthProphecyParams) ProtoMessage()    {}
func (*QueryEthProphecyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{10}
}
func (m *QueryEthProphecyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryEthProphecyParams.Unmarshal(m, b)
}
func (m *QueryEthProphecyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryEthProphecyParams.Marshal(b, m, deterministic)
}
func (dst *QueryEthProphecyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEthProphecyParams.Merge(dst, src)
}
func (m *QueryEthProphecyParams) XXX_Size() int {
	return xxx_messageInfo_QueryEthProphecyParams.Size(m)
}
func (m *QueryEthProphecyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEthProphecyParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEthProphecyParams proto.InternalMessageInfo

func (m *QueryEthProphecyParams) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ReceiptEthProphecy struct {
	ID                   string             `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Status               *ProphecyStatus    `protobuf:"bytes,2,opt,name=Status" json:"Status,omitempty"`
	ClaimValidators      []*ClaimValidators `protobuf:"bytes,3,rep,name=ClaimValidators" json:"ClaimValidators,omitempty"`
	ValidatorClaims      []*ValidatorClaims `protobuf:"bytes,4,rep,name=ValidatorClaims" json:"ValidatorClaims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReceiptEthProphecy) Reset()         { *m = ReceiptEthProphecy{} }
func (m *ReceiptEthProphecy) String() string { return proto.CompactTextString(m) }
func (*ReceiptEthProphecy) ProtoMessage()    {}
func (*ReceiptEthProphecy) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{11}
}
func (m *ReceiptEthProphecy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptEthProphecy.Unmarshal(m, b)
}
func (m *ReceiptEthProphecy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptEthProphecy.Marshal(b, m, deterministic)
}
func (dst *ReceiptEthProphecy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptEthProphecy.Merge(dst, src)
}
func (m *ReceiptEthProphecy) XXX_Size() int {
	return xxx_messageInfo_ReceiptEthProphecy.Size(m)
}
func (m *ReceiptEthProphecy) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptEthProphecy.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptEthProphecy proto.InternalMessageInfo

func (m *ReceiptEthProphecy) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ReceiptEthProphecy) GetStatus() *ProphecyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReceiptEthProphecy) GetClaimValidators() []*ClaimValidators {
	if m != nil {
		return m.ClaimValidators
	}
	return nil
}

func (m *ReceiptEthProphecy) GetValidatorClaims() []*ValidatorClaims {
	if m != nil {
		return m.ValidatorClaims
	}
	return nil
}

type ClaimValidators struct {
	Claim                string     `protobuf:"bytes,1,opt,name=claim" json:"claim,omitempty"`
	Validators           *StringMap `protobuf:"bytes,2,opt,name=validators" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ClaimValidators) Reset()         { *m = ClaimValidators{} }
func (m *ClaimValidators) String() string { return proto.CompactTextString(m) }
func (*ClaimValidators) ProtoMessage()    {}
func (*ClaimValidators) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{12}
}
func (m *ClaimValidators) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimValidators.Unmarshal(m, b)
}
func (m *ClaimValidators) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimValidators.Marshal(b, m, deterministic)
}
func (dst *ClaimValidators) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimValidators.Merge(dst, src)
}
func (m *ClaimValidators) XXX_Size() int {
	return xxx_messageInfo_ClaimValidators.Size(m)
}
func (m *ClaimValidators) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimValidators.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimValidators proto.InternalMessageInfo

func (m *ClaimValidators) GetClaim() string {
	if m != nil {
		return m.Claim
	}
	return ""
}

func (m *ClaimValidators) GetValidators() *StringMap {
	if m != nil {
		return m.Validators
	}
	return nil
}

type ValidatorClaims struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator" json:"validator,omitempty"`
	Claim                string   `protobuf:"bytes,2,opt,name=claim" json:"claim,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorClaims) Reset()         { *m = ValidatorClaims{} }
func (m *ValidatorClaims) String() string { return proto.CompactTextString(m) }
func (*ValidatorClaims) ProtoMessage()    {}
func (*ValidatorClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{13}
}
func (m *ValidatorClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorClaims.Unmarshal(m, b)
}
func (m *ValidatorClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorClaims.Marshal(b, m, deterministic)
}
func (dst *ValidatorClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorClaims.Merge(dst, src)
}
func (m *ValidatorClaims) XXX_Size() int {
	return xxx_messageInfo_ValidatorClaims.Size(m)
}
func (m *ValidatorClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorClaims.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorClaims proto.InternalMessageInfo

func (m *ValidatorClaims) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorClaims) GetClaim() string {
	if m != nil {
		return m.Claim
	}
	return ""
}

type StringMap struct {
	Validators           []string `protobuf:"bytes,1,rep,name=validators" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMap) Reset()         { *m = StringMap{} }
func (m *StringMap) String() string { return proto.CompactTextString(m) }
func (*StringMap) ProtoMessage()    {}
func (*StringMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{14}
}
func (m *StringMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMap.Unmarshal(m, b)
}
func (m *StringMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMap.Marshal(b, m, deterministic)
}
func (dst *StringMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMap.Merge(dst, src)
}
func (m *StringMap) XXX_Size() int {
	return xxx_messageInfo_StringMap.Size(m)
}
func (m *StringMap) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMap.DiscardUnknown(m)
}

var xxx_messageInfo_StringMap proto.InternalMessageInfo

func (m *StringMap) GetValidators() []string {
	if m != nil {
		return m.Validators
	}
	return nil
}

type ProphecyStatus struct {
	Text                 EthBridgeStatus `protobuf:"varint,1,opt,name=Text,enum=types.EthBridgeStatus" json:"Text,omitempty"`
	FinalClaim           string          `protobuf:"bytes,2,opt,name=FinalClaim" json:"FinalClaim,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProphecyStatus) Reset()         { *m = ProphecyStatus{} }
func (m *ProphecyStatus) String() string { return proto.CompactTextString(m) }
func (*ProphecyStatus) ProtoMessage()    {}
func (*ProphecyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{15}
}
func (m *ProphecyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProphecyStatus.Unmarshal(m, b)
}
func (m *ProphecyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProphecyStatus.Marshal(b, m, deterministic)
}
func (dst *ProphecyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProphecyStatus.Merge(dst, src)
}
func (m *ProphecyStatus) XXX_Size() int {
	return xxx_messageInfo_ProphecyStatus.Size(m)
}
func (m *ProphecyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ProphecyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ProphecyStatus proto.InternalMessageInfo

func (m *ProphecyStatus) GetText() EthBridgeStatus {
	if m != nil {
		return m.Text
	}
	return EthBridgeStatus_PendingStatusText
}

func (m *ProphecyStatus) GetFinalClaim() string {
	if m != nil {
		return m.FinalClaim
	}
	return ""
}

type QueryValidatorsParams struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryValidatorsParams) Reset()         { *m = QueryValidatorsParams{} }
func (m *QueryValidatorsParams) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorsParams) ProtoMessage()    {}
func (*QueryValidatorsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{16}
}
func (m *QueryValidatorsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryValidatorsParams.Unmarshal(m, b)
}
func (m *QueryValidatorsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryValidatorsParams.Marshal(b, m, deterministic)
}
func (dst *QueryValidatorsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorsParams.Merge(dst, src)
}
func (m *QueryValidatorsParams) XXX_Size() int {
	return xxx_messageInfo_QueryValidatorsParams.Size(m)
}
func (m *QueryValidatorsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorsParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorsParams proto.InternalMessageInfo

func (m *QueryValidatorsParams) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type ReceiptQueryValidator struct {
	Validators           []*MsgValidator `protobuf:"bytes,1,rep,name=validators" json:"validators,omitempty"`
	TotalPower           int64           `protobuf:"varint,2,opt,name=totalPower" json:"totalPower,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReceiptQueryValidator) Reset()         { *m = ReceiptQueryValidator{} }
func (m *ReceiptQueryValidator) String() string { return proto.CompactTextString(m) }
func (*ReceiptQueryValidator) ProtoMessage()    {}
func (*ReceiptQueryValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{17}
}
func (m *ReceiptQueryValidator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptQueryValidator.Unmarshal(m, b)
}
func (m *ReceiptQueryValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptQueryValidator.Marshal(b, m, deterministic)
}
func (dst *ReceiptQueryValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptQueryValidator.Merge(dst, src)
}
func (m *ReceiptQueryValidator) XXX_Size() int {
	return xxx_messageInfo_ReceiptQueryValidator.Size(m)
}
func (m *ReceiptQueryValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptQueryValidator.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptQueryValidator proto.InternalMessageInfo

func (m *ReceiptQueryValidator) GetValidators() []*MsgValidator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *ReceiptQueryValidator) GetTotalPower() int64 {
	if m != nil {
		return m.TotalPower
	}
	return 0
}

type QueryTotalPowerParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTotalPowerParams) Reset()         { *m = QueryTotalPowerParams{} }
func (m *QueryTotalPowerParams) String() string { return proto.CompactTextString(m) }
func (*QueryTotalPowerParams) ProtoMessage()    {}
func (*QueryTotalPowerParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{18}
}
func (m *QueryTotalPowerParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTotalPowerParams.Unmarshal(m, b)
}
func (m *QueryTotalPowerParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTotalPowerParams.Marshal(b, m, deterministic)
}
func (dst *QueryTotalPowerParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalPowerParams.Merge(dst, src)
}
func (m *QueryTotalPowerParams) XXX_Size() int {
	return xxx_messageInfo_QueryTotalPowerParams.Size(m)
}
func (m *QueryTotalPowerParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalPowerParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalPowerParams proto.InternalMessageInfo

type ReceiptQueryTotalPower struct {
	TotalPower           int64    `protobuf:"varint,1,opt,name=totalPower" json:"totalPower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptQueryTotalPower) Reset()         { *m = ReceiptQueryTotalPower{} }
func (m *ReceiptQueryTotalPower) String() string { return proto.CompactTextString(m) }
func (*ReceiptQueryTotalPower) ProtoMessage()    {}
func (*ReceiptQueryTotalPower) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{19}
}
func (m *ReceiptQueryTotalPower) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptQueryTotalPower.Unmarshal(m, b)
}
func (m *ReceiptQueryTotalPower) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptQueryTotalPower.Marshal(b, m, deterministic)
}
func (dst *ReceiptQueryTotalPower) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptQueryTotalPower.Merge(dst, src)
}
func (m *ReceiptQueryTotalPower) XXX_Size() int {
	return xxx_messageInfo_ReceiptQueryTotalPower.Size(m)
}
func (m *ReceiptQueryTotalPower) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptQueryTotalPower.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptQueryTotalPower proto.InternalMessageInfo

func (m *ReceiptQueryTotalPower) GetTotalPower() int64 {
	if m != nil {
		return m.TotalPower
	}
	return 0
}

type QueryConsensusThresholdParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryConsensusThresholdParams) Reset()         { *m = QueryConsensusThresholdParams{} }
func (m *QueryConsensusThresholdParams) String() string { return proto.CompactTextString(m) }
func (*QueryConsensusThresholdParams) ProtoMessage()    {}
func (*QueryConsensusThresholdParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{20}
}
func (m *QueryConsensusThresholdParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryConsensusThresholdParams.Unmarshal(m, b)
}
func (m *QueryConsensusThresholdParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryConsensusThresholdParams.Marshal(b, m, deterministic)
}
func (dst *QueryConsensusThresholdParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConsensusThresholdParams.Merge(dst, src)
}
func (m *QueryConsensusThresholdParams) XXX_Size() int {
	return xxx_messageInfo_QueryConsensusThresholdParams.Size(m)
}
func (m *QueryConsensusThresholdParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConsensusThresholdParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConsensusThresholdParams proto.InternalMessageInfo

type ReceiptQueryConsensusThreshold struct {
	ConsensusThreshold   int64    `protobuf:"varint,1,opt,name=consensusThreshold" json:"consensusThreshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptQueryConsensusThreshold) Reset()         { *m = ReceiptQueryConsensusThreshold{} }
func (m *ReceiptQueryConsensusThreshold) String() string { return proto.CompactTextString(m) }
func (*ReceiptQueryConsensusThreshold) ProtoMessage()    {}
func (*ReceiptQueryConsensusThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{21}
}
func (m *ReceiptQueryConsensusThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptQueryConsensusThreshold.Unmarshal(m, b)
}
func (m *ReceiptQueryConsensusThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptQueryConsensusThreshold.Marshal(b, m, deterministic)
}
func (dst *ReceiptQueryConsensusThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptQueryConsensusThreshold.Merge(dst, src)
}
func (m *ReceiptQueryConsensusThreshold) XXX_Size() int {
	return xxx_messageInfo_ReceiptQueryConsensusThreshold.Size(m)
}
func (m *ReceiptQueryConsensusThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptQueryConsensusThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptQueryConsensusThreshold proto.InternalMessageInfo

func (m *ReceiptQueryConsensusThreshold) GetConsensusThreshold() int64 {
	if m != nil {
		return m.ConsensusThreshold
	}
	return 0
}

type QuerySymbolAssetsByTxTypeParams struct {
	TokenSymbol          string   `protobuf:"bytes,1,opt,name=tokenSymbol" json:"tokenSymbol,omitempty"`
	Direction            int64    `protobuf:"varint,2,opt,name=direction" json:"direction,omitempty"`
	TxType               string   `protobuf:"bytes,3,opt,name=txType" json:"txType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySymbolAssetsByTxTypeParams) Reset()         { *m = QuerySymbolAssetsByTxTypeParams{} }
func (m *QuerySymbolAssetsByTxTypeParams) String() string { return proto.CompactTextString(m) }
func (*QuerySymbolAssetsByTxTypeParams) ProtoMessage()    {}
func (*QuerySymbolAssetsByTxTypeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{22}
}
func (m *QuerySymbolAssetsByTxTypeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySymbolAssetsByTxTypeParams.Unmarshal(m, b)
}
func (m *QuerySymbolAssetsByTxTypeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySymbolAssetsByTxTypeParams.Marshal(b, m, deterministic)
}
func (dst *QuerySymbolAssetsByTxTypeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySymbolAssetsByTxTypeParams.Merge(dst, src)
}
func (m *QuerySymbolAssetsByTxTypeParams) XXX_Size() int {
	return xxx_messageInfo_QuerySymbolAssetsByTxTypeParams.Size(m)
}
func (m *QuerySymbolAssetsByTxTypeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySymbolAssetsByTxTypeParams.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySymbolAssetsByTxTypeParams proto.InternalMessageInfo

func (m *QuerySymbolAssetsByTxTypeParams) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

func (m *QuerySymbolAssetsByTxTypeParams) GetDirection() int64 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *QuerySymbolAssetsByTxTypeParams) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

type ReceiptQuerySymbolAssetsByTxType struct {
	TokenSymbol          string   `protobuf:"bytes,1,opt,name=tokenSymbol" json:"tokenSymbol,omitempty"`
	TotalAmount          uint64   `protobuf:"varint,2,opt,name=totalAmount" json:"totalAmount,omitempty"`
	TxType               string   `protobuf:"bytes,3,opt,name=txType" json:"txType,omitempty"`
	Direction            int64    `protobuf:"varint,4,opt,name=direction" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptQuerySymbolAssetsByTxType) Reset()         { *m = ReceiptQuerySymbolAssetsByTxType{} }
func (m *ReceiptQuerySymbolAssetsByTxType) String() string { return proto.CompactTextString(m) }
func (*ReceiptQuerySymbolAssetsByTxType) ProtoMessage()    {}
func (*ReceiptQuerySymbolAssetsByTxType) Descriptor() ([]byte, []int) {
	return fileDescriptor_x2ethereum_88bd3685a702d97e, []int{23}
}
func (m *ReceiptQuerySymbolAssetsByTxType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptQuerySymbolAssetsByTxType.Unmarshal(m, b)
}
func (m *ReceiptQuerySymbolAssetsByTxType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptQuerySymbolAssetsByTxType.Marshal(b, m, deterministic)
}
func (dst *ReceiptQuerySymbolAssetsByTxType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptQuerySymbolAssetsByTxType.Merge(dst, src)
}
func (m *ReceiptQuerySymbolAssetsByTxType) XXX_Size() int {
	return xxx_messageInfo_ReceiptQuerySymbolAssetsByTxType.Size(m)
}
func (m *ReceiptQuerySymbolAssetsByTxType) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptQuerySymbolAssetsByTxType.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptQuerySymbolAssetsByTxType proto.InternalMessageInfo

func (m *ReceiptQuerySymbolAssetsByTxType) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

func (m *ReceiptQuerySymbolAssetsByTxType) GetTotalAmount() uint64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *ReceiptQuerySymbolAssetsByTxType) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *ReceiptQuerySymbolAssetsByTxType) GetDirection() int64 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func init() {
	proto.RegisterType((*X2EthereumAction)(nil), "types.X2ethereumAction")
	proto.RegisterType((*MsgConsensusThreshold)(nil), "types.MsgConsensusThreshold")
	proto.RegisterType((*MsgValidator)(nil), "types.MsgValidator")
	proto.RegisterType((*Eth2Chain33)(nil), "types.Eth2Chain33")
	proto.RegisterType((*OracleClaimContent)(nil), "types.OracleClaimContent")
	proto.RegisterType((*Chain33ToEth)(nil), "types.Chain33ToEth")
	proto.RegisterType((*ReceiptEth2Chain33)(nil), "types.ReceiptEth2Chain33")
	proto.RegisterType((*ReceiptChain33ToEth)(nil), "types.ReceiptChain33ToEth")
	proto.RegisterType((*ReceiptValidator)(nil), "types.ReceiptValidator")
	proto.RegisterType((*ReceiptSetConsensusThreshold)(nil), "types.ReceiptSetConsensusThreshold")
	proto.RegisterType((*QueryEthProphecyParams)(nil), "types.QueryEthProphecyParams")
	proto.RegisterType((*ReceiptEthProphecy)(nil), "types.ReceiptEthProphecy")
	proto.RegisterType((*ClaimValidators)(nil), "types.ClaimValidators")
	proto.RegisterType((*ValidatorClaims)(nil), "types.ValidatorClaims")
	proto.RegisterType((*StringMap)(nil), "types.StringMap")
	proto.RegisterType((*ProphecyStatus)(nil), "types.ProphecyStatus")
	proto.RegisterType((*QueryValidatorsParams)(nil), "types.QueryValidatorsParams")
	proto.RegisterType((*ReceiptQueryValidator)(nil), "types.ReceiptQueryValidator")
	proto.RegisterType((*QueryTotalPowerParams)(nil), "types.QueryTotalPowerParams")
	proto.RegisterType((*ReceiptQueryTotalPower)(nil), "types.ReceiptQueryTotalPower")
	proto.RegisterType((*QueryConsensusThresholdParams)(nil), "types.QueryConsensusThresholdParams")
	proto.RegisterType((*ReceiptQueryConsensusThreshold)(nil), "types.ReceiptQueryConsensusThreshold")
	proto.RegisterType((*QuerySymbolAssetsByTxTypeParams)(nil), "types.QuerySymbolAssetsByTxTypeParams")
	proto.RegisterType((*ReceiptQuerySymbolAssetsByTxType)(nil), "types.ReceiptQuerySymbolAssetsByTxType")
	proto.RegisterEnum("types.EthBridgeStatus", EthBridgeStatus_name, EthBridgeStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for X2Ethereum service

type X2EthereumClient interface {
}

type x2EthereumClient struct {
	cc *grpc.ClientConn
}

func NewX2EthereumClient(cc *grpc.ClientConn) X2EthereumClient {
	return &x2EthereumClient{cc}
}

// Server API for X2Ethereum service

type X2EthereumServer interface {
}

func RegisterX2EthereumServer(s *grpc.Server, srv X2EthereumServer) {
	s.RegisterService(&_X2Ethereum_serviceDesc, srv)
}

var _X2Ethereum_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.x2ethereum",
	HandlerType: (*X2EthereumServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "x2ethereum.proto",
}

func init() { proto.RegisterFile("x2ethereum.proto", fileDescriptor_x2ethereum_88bd3685a702d97e) }

var fileDescriptor_x2ethereum_88bd3685a702d97e = []byte{
	// 1121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x1b, 0xae, 0xe3, 0x24, 0xfd, 0xfc, 0x26, 0xdb, 0xe6, 0x9b, 0x6d, 0x8a, 0x0f, 0xca, 0x6e, 0x64,
	0x21, 0x14, 0x15, 0x51, 0xa1, 0x74, 0xf9, 0x3b, 0x01, 0xda, 0x34, 0x4b, 0x7b, 0xb0, 0x10, 0x26,
	0x11, 0x3f, 0x12, 0x27, 0xb3, 0xf6, 0x50, 0x5b, 0x38, 0x9e, 0xc8, 0x9e, 0xb4, 0xc9, 0x8d, 0x70,
	0xc4, 0x11, 0xb7, 0x81, 0xc4, 0x09, 0x17, 0xc1, 0x5d, 0x70, 0x0d, 0x68, 0xc6, 0x63, 0x7b, 0xec,
	0xb8, 0xd1, 0x6a, 0xc5, 0x01, 0x48, 0x1c, 0xce, 0xf3, 0xfe, 0x3d, 0xef, 0xeb, 0x67, 0x7e, 0x0c,
	0xbd, 0xf5, 0x88, 0x72, 0x9f, 0xc6, 0x74, 0xb5, 0x38, 0x5b, 0xc6, 0x8c, 0x33, 0xd4, 0xe2, 0x9b,
	0x25, 0x4d, 0x9c, 0x5f, 0x9a, 0xd0, 0xfb, 0x36, 0xb7, 0x5d, 0xb8, 0x3c, 0x60, 0x11, 0xfa, 0x00,
	0x3a, 0x94, 0xfb, 0xa3, 0xb1, 0x4f, 0x82, 0xe8, 0xfc, 0xdc, 0x36, 0x06, 0xc6, 0xb0, 0x33, 0x42,
	0x67, 0x32, 0xe2, 0x6c, 0x52, 0x58, 0xae, 0xf7, 0xb0, 0xee, 0x28, 0xe2, 0xee, 0x03, 0xee, 0x7b,
	0x31, 0xb9, 0x9f, 0x70, 0xdf, 0x6e, 0xec, 0x8a, 0xd3, 0x1c, 0xd1, 0xa7, 0x70, 0x98, 0x2d, 0xb3,
	0x9a, 0xa6, 0x8c, 0x7d, 0xac, 0x62, 0x15, 0x3a, 0x67, 0x13, 0xee, 0x5f, 0xef, 0xe1, 0xaa, 0x37,
	0xfa, 0x18, 0xba, 0xae, 0xe6, 0x62, 0x37, 0x77, 0x45, 0x97, 0x5c, 0x45, 0x28, 0xf1, 0xbc, 0xaf,
	0x49, 0x18, 0x78, 0x84, 0xb3, 0xd8, 0x6e, 0x95, 0x42, 0x5f, 0x24, 0xb7, 0xb9, 0x49, 0x84, 0xea,
	0xae, 0x82, 0x76, 0x4c, 0x17, 0xec, 0x8e, 0x16, 0xd1, 0xed, 0x5d, 0xd1, 0x55, 0x6f, 0xf4, 0x21,
	0x74, 0x16, 0xcc, 0x0b, 0x7e, 0xd8, 0x4c, 0xd9, 0x3d, 0x8d, 0xed, 0xfd, 0x5d, 0xc1, 0xba, 0x27,
	0x9a, 0x43, 0x3f, 0xa1, 0x7c, 0xcc, 0xa2, 0x84, 0x46, 0xc9, 0x2a, 0x99, 0xfb, 0x31, 0x4d, 0x7c,
	0x16, 0x7a, 0xf6, 0xff, 0x64, 0x8a, 0x93, 0x22, 0xc5, 0xb6, 0xcf, 0xf5, 0x1e, 0xae, 0x0f, 0x46,
	0x07, 0xd0, 0xe0, 0x1b, 0x1b, 0x06, 0xc6, 0xb0, 0x85, 0x1b, 0x7c, 0x73, 0xb9, 0x0f, 0xad, 0x3b,
	0x12, 0xae, 0xa8, 0xf3, 0x39, 0xf4, 0x6b, 0x53, 0xa1, 0x33, 0x40, 0xee, 0x36, 0x09, 0xa1, 0x17,
	0x13, 0xd7, 0x58, 0x9c, 0x4f, 0xa0, 0xab, 0xb7, 0x85, 0x6c, 0xd8, 0x27, 0x9e, 0x17, 0xd3, 0x24,
	0x91, 0x41, 0x16, 0xce, 0x96, 0xe8, 0x08, 0x5a, 0x4b, 0x39, 0x94, 0x86, 0x4c, 0x96, 0x2e, 0x9c,
	0x5f, 0x4d, 0xe8, 0x68, 0x3a, 0x42, 0x43, 0x38, 0x9c, 0x28, 0xe9, 0x4a, 0xe8, 0xe6, 0x4a, 0x15,
	0xaf, 0xc2, 0xe8, 0x19, 0xf4, 0x2f, 0xe3, 0xc0, 0xbb, 0xa5, 0x63, 0x16, 0xf1, 0x98, 0xb8, 0xfc,
	0x42, 0xd5, 0x6d, 0xc8, 0xba, 0xf5, 0x46, 0xc1, 0xe2, 0x0b, 0x16, 0xb9, 0x54, 0xca, 0xd1, 0xc4,
	0xe9, 0x42, 0x54, 0x0d, 0x99, 0x4b, 0xc2, 0x31, 0x0b, 0xa2, 0xd9, 0x66, 0xf1, 0x92, 0x85, 0x52,
	0x70, 0x16, 0xae, 0xc2, 0xe8, 0x2d, 0x78, 0x94, 0x43, 0x93, 0x35, 0x75, 0xa5, 0xba, 0x2c, 0x5c,
	0x06, 0xd1, 0x08, 0x8e, 0xe6, 0xec, 0x47, 0x1a, 0x55, 0xa9, 0xb5, 0xa5, 0x73, 0xad, 0x0d, 0xbd,
	0x0d, 0x07, 0x59, 0x8b, 0x33, 0x1a, 0x79, 0x4a, 0x3d, 0x16, 0xae, 0xa0, 0x82, 0xab, 0x1a, 0x16,
	0xa6, 0x2e, 0x0d, 0xee, 0x68, 0x2c, 0x35, 0x62, 0xe1, 0x2a, 0x8c, 0x4e, 0xa1, 0x97, 0x7f, 0x98,
	0x8c, 0x81, 0x25, 0x5d, 0xb7, 0x70, 0x74, 0x0c, 0xed, 0x8b, 0x05, 0x5b, 0x45, 0x5c, 0xaa, 0xa5,
	0x89, 0xd5, 0x0a, 0x9d, 0x80, 0x35, 0x0e, 0x49, 0xb0, 0x98, 0x6f, 0x96, 0xd4, 0xee, 0xc8, 0x99,
	0x15, 0x80, 0xc3, 0x01, 0x7d, 0x19, 0x13, 0x37, 0xa4, 0x12, 0x12, 0x1d, 0xd1, 0x88, 0xd7, 0x31,
	0x34, 0xea, 0x19, 0x16, 0x55, 0x1b, 0x0f, 0x57, 0x35, 0xab, 0x55, 0xff, 0x34, 0xa0, 0xab, 0x9f,
	0x00, 0xe2, 0xa3, 0x94, 0x46, 0xaa, 0xca, 0x95, 0x41, 0xe1, 0xa5, 0xa2, 0xd4, 0x7c, 0x53, 0xa1,
	0x94, 0x41, 0x31, 0xb4, 0x6c, 0xe0, 0x39, 0x7b, 0x33, 0x1d, 0x5a, 0x15, 0xd7, 0xe8, 0x37, 0x4b,
	0xf4, 0x6b, 0xe4, 0xd4, 0x7a, 0x45, 0x39, 0xb5, 0x6b, 0xe4, 0xe4, 0xfc, 0xd4, 0x04, 0x24, 0x8b,
	0x2e, 0xf9, 0x7f, 0x7b, 0xe5, 0x5f, 0xba, 0x57, 0xc4, 0xc9, 0xb8, 0x9e, 0xaf, 0xaf, 0x49, 0xe2,
	0xdb, 0xdd, 0x81, 0x31, 0xec, 0xe2, 0x6c, 0x29, 0x2d, 0xd7, 0x34, 0xb8, 0xf5, 0xb9, 0xfd, 0x48,
	0x26, 0xcc, 0x96, 0xe8, 0x09, 0xc0, 0x34, 0x66, 0x4b, 0x9f, 0xba, 0x9b, 0x9b, 0x2b, 0xfb, 0x40,
	0xf2, 0xd1, 0x10, 0xe7, 0x77, 0x03, 0x1e, 0x2b, 0x61, 0xfc, 0xa3, 0x37, 0xc4, 0x09, 0x58, 0x13,
	0xee, 0x97, 0xb6, 0x42, 0x01, 0x38, 0x77, 0xd0, 0x53, 0x4d, 0xbc, 0xf6, 0x3d, 0xa2, 0x4f, 0xd7,
	0x7c, 0x70, 0xba, 0xcd, 0xd2, 0x74, 0x9d, 0xdf, 0x0c, 0x38, 0x51, 0x85, 0x67, 0xb5, 0xd7, 0xe7,
	0x33, 0xe8, 0x2f, 0x63, 0x3a, 0x7e, 0xe8, 0x3e, 0xac, 0x37, 0x8a, 0xa8, 0x88, 0xdd, 0xd7, 0x44,
	0xa5, 0x84, 0xeb, 0x8d, 0xaf, 0xd5, 0xc0, 0x10, 0x8e, 0xbf, 0x5a, 0xd1, 0x78, 0x33, 0xe1, 0x7e,
	0x26, 0x8a, 0x29, 0x89, 0xc9, 0x22, 0x11, 0x17, 0xbf, 0x3a, 0x0d, 0x2c, 0xdc, 0xb8, 0xb9, 0x72,
	0xfe, 0x30, 0xf4, 0x13, 0x24, 0x73, 0xae, 0xba, 0xa1, 0x77, 0xa1, 0x3d, 0xe3, 0x84, 0xaf, 0x12,
	0xf5, 0xd2, 0xeb, 0xab, 0x67, 0x47, 0x16, 0x90, 0x1a, 0xb1, 0x72, 0x42, 0x9f, 0xc1, 0xa1, 0xd4,
	0x77, 0xfe, 0xd9, 0x12, 0xdb, 0x1c, 0x98, 0xc3, 0xce, 0xe8, 0x38, 0x7b, 0xa7, 0x95, 0xad, 0xb8,
	0xea, 0x2e, 0x32, 0xe4, 0x2b, 0x69, 0x4b, 0xec, 0x66, 0x29, 0x43, 0xc5, 0x8a, 0xab, 0xee, 0xce,
	0x77, 0x5b, 0x1c, 0x84, 0x42, 0x5c, 0x01, 0xa9, 0xc6, 0xd2, 0x05, 0x7a, 0x0f, 0xe0, 0xae, 0xe0,
	0x99, 0xf6, 0xd7, 0x53, 0x55, 0x66, 0x3c, 0x0e, 0xa2, 0xdb, 0x17, 0x64, 0x89, 0x35, 0x1f, 0x67,
	0xb2, 0x45, 0x4e, 0x08, 0x39, 0x77, 0x50, 0xe9, 0x0b, 0xa0, 0x28, 0xdc, 0xd0, 0x0a, 0x3b, 0xef,
	0x80, 0x95, 0xe7, 0x17, 0x3b, 0x5a, 0x63, 0x61, 0x0c, 0x4c, 0xb1, 0xa3, 0xb5, 0x9a, 0xdf, 0xc3,
	0x41, 0x79, 0xd8, 0xe8, 0x14, 0x9a, 0x73, 0xba, 0x4e, 0xb7, 0xf0, 0x41, 0x3e, 0x97, 0x09, 0xf7,
	0xd3, 0x43, 0x5b, 0x7d, 0x12, 0xe9, 0x23, 0xb2, 0x3f, 0x0f, 0x22, 0x12, 0x8e, 0x35, 0x16, 0x1a,
	0xe2, 0xbc, 0x0f, 0x7d, 0x29, 0x98, 0x62, 0x58, 0x4a, 0x2f, 0x3b, 0xfb, 0x72, 0x42, 0xe8, 0x2b,
	0xf1, 0x94, 0xa3, 0xd1, 0xf9, 0x56, 0x37, 0xf5, 0xaf, 0x5d, 0xbd, 0x45, 0x41, 0x92, 0x33, 0x4e,
	0xc2, 0xa9, 0xb6, 0x8b, 0x35, 0xc4, 0x79, 0x43, 0x91, 0x9c, 0xe7, 0x50, 0x4a, 0xd2, 0xf9, 0x08,
	0x8e, 0x75, 0x1a, 0x85, 0xbd, 0x92, 0xd2, 0xd8, 0x4a, 0xf9, 0x14, 0xde, 0x94, 0x21, 0xdb, 0xfb,
	0x4e, 0xa5, 0x9e, 0xc2, 0x13, 0x3d, 0xf5, 0xdf, 0xf0, 0x30, 0xde, 0xc0, 0x53, 0x99, 0x2a, 0x3d,
	0xe3, 0x2e, 0x92, 0x84, 0xf2, 0xe4, 0x72, 0x33, 0x5f, 0x8b, 0xbb, 0x40, 0x0d, 0x7d, 0x00, 0x1d,
	0x2e, 0x0e, 0x64, 0x75, 0x2e, 0xa6, 0x63, 0xd7, 0x21, 0xf1, 0x59, 0xbc, 0x20, 0xa6, 0xf2, 0x1f,
	0x4e, 0x4d, 0xaa, 0x00, 0xc4, 0x69, 0xcb, 0xd7, 0xf9, 0x13, 0xc9, 0xc2, 0x6a, 0xe5, 0xfc, 0x6c,
	0xc0, 0x40, 0xef, 0xa6, 0x8e, 0xc2, 0x2b, 0x14, 0x97, 0x1e, 0x9c, 0x84, 0xa5, 0x17, 0x9a, 0x0e,
	0x3d, 0x44, 0xa0, 0x4c, 0xbb, 0x59, 0xa1, 0x7d, 0xca, 0xe4, 0xb3, 0x45, 0x57, 0x2f, 0xea, 0xc3,
	0xff, 0xa7, 0x34, 0xf2, 0x82, 0xe8, 0x36, 0x05, 0x84, 0x98, 0x7b, 0x7b, 0x02, 0x9e, 0xad, 0x5c,
	0x97, 0x26, 0x89, 0x06, 0x1b, 0xe8, 0x08, 0x7a, 0xcf, 0x49, 0x10, 0x52, 0x4f, 0x43, 0x1b, 0xc8,
	0x86, 0xa3, 0x6f, 0xd4, 0x4f, 0x64, 0xc9, 0x62, 0x8e, 0xba, 0x00, 0xc5, 0xcf, 0xf2, 0xcb, 0xb6,
	0xfc, 0x5b, 0x3e, 0xff, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xf0, 0xca, 0xf5, 0x41, 0x0f, 0x00,
	0x00,
}
