// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relayer.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//以太坊账户信息
// 	 privkey : 账户地址对应的私钥
//	 addr :账户地址
type Account4Relayer struct {
	Privkey              []byte   `protobuf:"bytes,1,opt,name=privkey,proto3" json:"privkey,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account4Relayer) Reset()         { *m = Account4Relayer{} }
func (m *Account4Relayer) String() string { return proto.CompactTextString(m) }
func (*Account4Relayer) ProtoMessage()    {}
func (*Account4Relayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{0}
}

func (m *Account4Relayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account4Relayer.Unmarshal(m, b)
}
func (m *Account4Relayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account4Relayer.Marshal(b, m, deterministic)
}
func (m *Account4Relayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account4Relayer.Merge(m, src)
}
func (m *Account4Relayer) XXX_Size() int {
	return xxx_messageInfo_Account4Relayer.Size(m)
}
func (m *Account4Relayer) XXX_DiscardUnknown() {
	xxx_messageInfo_Account4Relayer.DiscardUnknown(m)
}

var xxx_messageInfo_Account4Relayer proto.InternalMessageInfo

func (m *Account4Relayer) GetPrivkey() []byte {
	if m != nil {
		return m.Privkey
	}
	return nil
}

func (m *Account4Relayer) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ValidatorAddr4EthRelayer struct {
	EthValidator         string   `protobuf:"bytes,1,opt,name=ethValidator,proto3" json:"ethValidator,omitempty"`
	Chain33Validator     string   `protobuf:"bytes,2,opt,name=chain33Validator,proto3" json:"chain33Validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorAddr4EthRelayer) Reset()         { *m = ValidatorAddr4EthRelayer{} }
func (m *ValidatorAddr4EthRelayer) String() string { return proto.CompactTextString(m) }
func (*ValidatorAddr4EthRelayer) ProtoMessage()    {}
func (*ValidatorAddr4EthRelayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{1}
}

func (m *ValidatorAddr4EthRelayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorAddr4EthRelayer.Unmarshal(m, b)
}
func (m *ValidatorAddr4EthRelayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorAddr4EthRelayer.Marshal(b, m, deterministic)
}
func (m *ValidatorAddr4EthRelayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorAddr4EthRelayer.Merge(m, src)
}
func (m *ValidatorAddr4EthRelayer) XXX_Size() int {
	return xxx_messageInfo_ValidatorAddr4EthRelayer.Size(m)
}
func (m *ValidatorAddr4EthRelayer) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorAddr4EthRelayer.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorAddr4EthRelayer proto.InternalMessageInfo

func (m *ValidatorAddr4EthRelayer) GetEthValidator() string {
	if m != nil {
		return m.EthValidator
	}
	return ""
}

func (m *ValidatorAddr4EthRelayer) GetChain33Validator() string {
	if m != nil {
		return m.Chain33Validator
	}
	return ""
}

type Txhashes struct {
	Txhash               []string `protobuf:"bytes,1,rep,name=txhash,proto3" json:"txhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Txhashes) Reset()         { *m = Txhashes{} }
func (m *Txhashes) String() string { return proto.CompactTextString(m) }
func (*Txhashes) ProtoMessage()    {}
func (*Txhashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{2}
}

func (m *Txhashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Txhashes.Unmarshal(m, b)
}
func (m *Txhashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Txhashes.Marshal(b, m, deterministic)
}
func (m *Txhashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Txhashes.Merge(m, src)
}
func (m *Txhashes) XXX_Size() int {
	return xxx_messageInfo_Txhashes.Size(m)
}
func (m *Txhashes) XXX_DiscardUnknown() {
	xxx_messageInfo_Txhashes.DiscardUnknown(m)
}

var xxx_messageInfo_Txhashes proto.InternalMessageInfo

func (m *Txhashes) GetTxhash() []string {
	if m != nil {
		return m.Txhash
	}
	return nil
}

type ReqSetPasswd struct {
	OldPassphase         string   `protobuf:"bytes,1,opt,name=oldPassphase,proto3" json:"oldPassphase,omitempty"`
	NewPassphase         string   `protobuf:"bytes,2,opt,name=newPassphase,proto3" json:"newPassphase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSetPasswd) Reset()         { *m = ReqSetPasswd{} }
func (m *ReqSetPasswd) String() string { return proto.CompactTextString(m) }
func (*ReqSetPasswd) ProtoMessage()    {}
func (*ReqSetPasswd) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{3}
}

func (m *ReqSetPasswd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSetPasswd.Unmarshal(m, b)
}
func (m *ReqSetPasswd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSetPasswd.Marshal(b, m, deterministic)
}
func (m *ReqSetPasswd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSetPasswd.Merge(m, src)
}
func (m *ReqSetPasswd) XXX_Size() int {
	return xxx_messageInfo_ReqSetPasswd.Size(m)
}
func (m *ReqSetPasswd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSetPasswd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSetPasswd proto.InternalMessageInfo

func (m *ReqSetPasswd) GetOldPassphase() string {
	if m != nil {
		return m.OldPassphase
	}
	return ""
}

func (m *ReqSetPasswd) GetNewPassphase() string {
	if m != nil {
		return m.NewPassphase
	}
	return ""
}

type Account4Show struct {
	Privkey              string   `protobuf:"bytes,1,opt,name=privkey,proto3" json:"privkey,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account4Show) Reset()         { *m = Account4Show{} }
func (m *Account4Show) String() string { return proto.CompactTextString(m) }
func (*Account4Show) ProtoMessage()    {}
func (*Account4Show) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{4}
}

func (m *Account4Show) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account4Show.Unmarshal(m, b)
}
func (m *Account4Show) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account4Show.Marshal(b, m, deterministic)
}
func (m *Account4Show) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account4Show.Merge(m, src)
}
func (m *Account4Show) XXX_Size() int {
	return xxx_messageInfo_Account4Show.Size(m)
}
func (m *Account4Show) XXX_DiscardUnknown() {
	xxx_messageInfo_Account4Show.DiscardUnknown(m)
}

var xxx_messageInfo_Account4Show proto.InternalMessageInfo

func (m *Account4Show) GetPrivkey() string {
	if m != nil {
		return m.Privkey
	}
	return ""
}

func (m *Account4Show) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type AssetType struct {
	Chain                string   `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	IssueContract        string   `protobuf:"bytes,2,opt,name=issueContract,proto3" json:"issueContract,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetType) Reset()         { *m = AssetType{} }
func (m *AssetType) String() string { return proto.CompactTextString(m) }
func (*AssetType) ProtoMessage()    {}
func (*AssetType) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{5}
}

func (m *AssetType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetType.Unmarshal(m, b)
}
func (m *AssetType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetType.Marshal(b, m, deterministic)
}
func (m *AssetType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetType.Merge(m, src)
}
func (m *AssetType) XXX_Size() int {
	return xxx_messageInfo_AssetType.Size(m)
}
func (m *AssetType) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetType.DiscardUnknown(m)
}

var xxx_messageInfo_AssetType proto.InternalMessageInfo

func (m *AssetType) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *AssetType) GetIssueContract() string {
	if m != nil {
		return m.IssueContract
	}
	return ""
}

func (m *AssetType) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type EthBridgeClaim struct {
	EthereumChainID       int32    `protobuf:"varint,1,opt,name=ethereumChainID,proto3" json:"ethereumChainID,omitempty"`
	BridgeContractAddress []byte   `protobuf:"bytes,2,opt,name=bridgeContractAddress,proto3" json:"bridgeContractAddress,omitempty"`
	Nonce                 int64    `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TokenContractAddress  []byte   `protobuf:"bytes,4,opt,name=tokenContractAddress,proto3" json:"tokenContractAddress,omitempty"`
	Symbol                string   `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	EthereumSender        []byte   `protobuf:"bytes,6,opt,name=ethereumSender,proto3" json:"ethereumSender,omitempty"`
	Chain33Receiver       []byte   `protobuf:"bytes,7,opt,name=chain33Receiver,proto3" json:"chain33Receiver,omitempty"`
	ValidatorAddress      []byte   `protobuf:"bytes,8,opt,name=ValidatorAddress,proto3" json:"ValidatorAddress,omitempty"`
	Amount                int64    `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	ClaimType             int32    `protobuf:"varint,10,opt,name=claimType,proto3" json:"claimType,omitempty"`
	ChainName             string   `protobuf:"bytes,11,opt,name=chainName,proto3" json:"chainName,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *EthBridgeClaim) Reset()         { *m = EthBridgeClaim{} }
func (m *EthBridgeClaim) String() string { return proto.CompactTextString(m) }
func (*EthBridgeClaim) ProtoMessage()    {}
func (*EthBridgeClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{6}
}

func (m *EthBridgeClaim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EthBridgeClaim.Unmarshal(m, b)
}
func (m *EthBridgeClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EthBridgeClaim.Marshal(b, m, deterministic)
}
func (m *EthBridgeClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthBridgeClaim.Merge(m, src)
}
func (m *EthBridgeClaim) XXX_Size() int {
	return xxx_messageInfo_EthBridgeClaim.Size(m)
}
func (m *EthBridgeClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_EthBridgeClaim.DiscardUnknown(m)
}

var xxx_messageInfo_EthBridgeClaim proto.InternalMessageInfo

func (m *EthBridgeClaim) GetEthereumChainID() int32 {
	if m != nil {
		return m.EthereumChainID
	}
	return 0
}

func (m *EthBridgeClaim) GetBridgeContractAddress() []byte {
	if m != nil {
		return m.BridgeContractAddress
	}
	return nil
}

func (m *EthBridgeClaim) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *EthBridgeClaim) GetTokenContractAddress() []byte {
	if m != nil {
		return m.TokenContractAddress
	}
	return nil
}

func (m *EthBridgeClaim) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *EthBridgeClaim) GetEthereumSender() []byte {
	if m != nil {
		return m.EthereumSender
	}
	return nil
}

func (m *EthBridgeClaim) GetChain33Receiver() []byte {
	if m != nil {
		return m.Chain33Receiver
	}
	return nil
}

func (m *EthBridgeClaim) GetValidatorAddress() []byte {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *EthBridgeClaim) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *EthBridgeClaim) GetClaimType() int32 {
	if m != nil {
		return m.ClaimType
	}
	return 0
}

func (m *EthBridgeClaim) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

type ImportKeyReq struct {
	PrivateKey           string   `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportKeyReq) Reset()         { *m = ImportKeyReq{} }
func (m *ImportKeyReq) String() string { return proto.CompactTextString(m) }
func (*ImportKeyReq) ProtoMessage()    {}
func (*ImportKeyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{7}
}

func (m *ImportKeyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportKeyReq.Unmarshal(m, b)
}
func (m *ImportKeyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportKeyReq.Marshal(b, m, deterministic)
}
func (m *ImportKeyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportKeyReq.Merge(m, src)
}
func (m *ImportKeyReq) XXX_Size() int {
	return xxx_messageInfo_ImportKeyReq.Size(m)
}
func (m *ImportKeyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportKeyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ImportKeyReq proto.InternalMessageInfo

func (m *ImportKeyReq) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type RelayerRunStatus struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayerRunStatus) Reset()         { *m = RelayerRunStatus{} }
func (m *RelayerRunStatus) String() string { return proto.CompactTextString(m) }
func (*RelayerRunStatus) ProtoMessage()    {}
func (*RelayerRunStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{8}
}

func (m *RelayerRunStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayerRunStatus.Unmarshal(m, b)
}
func (m *RelayerRunStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayerRunStatus.Marshal(b, m, deterministic)
}
func (m *RelayerRunStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayerRunStatus.Merge(m, src)
}
func (m *RelayerRunStatus) XXX_Size() int {
	return xxx_messageInfo_RelayerRunStatus.Size(m)
}
func (m *RelayerRunStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayerRunStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RelayerRunStatus proto.InternalMessageInfo

func (m *RelayerRunStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RelayerRunStatus) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type NewProphecyClaim struct {
	ClaimType            uint32   `protobuf:"varint,1,opt,name=claimType,proto3" json:"claimType,omitempty"`
	Chain33Sender        string   `protobuf:"bytes,2,opt,name=chain33Sender,proto3" json:"chain33Sender,omitempty"`
	TokenAddr            string   `protobuf:"bytes,3,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Symbol               string   `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	EthReceiver          string   `protobuf:"bytes,5,opt,name=ethReceiver,proto3" json:"ethReceiver,omitempty"`
	Amount               int64    `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewProphecyClaim) Reset()         { *m = NewProphecyClaim{} }
func (m *NewProphecyClaim) String() string { return proto.CompactTextString(m) }
func (*NewProphecyClaim) ProtoMessage()    {}
func (*NewProphecyClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{9}
}

func (m *NewProphecyClaim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProphecyClaim.Unmarshal(m, b)
}
func (m *NewProphecyClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProphecyClaim.Marshal(b, m, deterministic)
}
func (m *NewProphecyClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProphecyClaim.Merge(m, src)
}
func (m *NewProphecyClaim) XXX_Size() int {
	return xxx_messageInfo_NewProphecyClaim.Size(m)
}
func (m *NewProphecyClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProphecyClaim.DiscardUnknown(m)
}

var xxx_messageInfo_NewProphecyClaim proto.InternalMessageInfo

func (m *NewProphecyClaim) GetClaimType() uint32 {
	if m != nil {
		return m.ClaimType
	}
	return 0
}

func (m *NewProphecyClaim) GetChain33Sender() string {
	if m != nil {
		return m.Chain33Sender
	}
	return ""
}

func (m *NewProphecyClaim) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *NewProphecyClaim) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *NewProphecyClaim) GetEthReceiver() string {
	if m != nil {
		return m.EthReceiver
	}
	return ""
}

func (m *NewProphecyClaim) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BalanceAddr struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceAddr) Reset()         { *m = BalanceAddr{} }
func (m *BalanceAddr) String() string { return proto.CompactTextString(m) }
func (*BalanceAddr) ProtoMessage()    {}
func (*BalanceAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{10}
}

func (m *BalanceAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceAddr.Unmarshal(m, b)
}
func (m *BalanceAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceAddr.Marshal(b, m, deterministic)
}
func (m *BalanceAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceAddr.Merge(m, src)
}
func (m *BalanceAddr) XXX_Size() int {
	return xxx_messageInfo_BalanceAddr.Size(m)
}
func (m *BalanceAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceAddr.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceAddr proto.InternalMessageInfo

func (m *BalanceAddr) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *BalanceAddr) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

type MintToken struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MintToken) Reset()         { *m = MintToken{} }
func (m *MintToken) String() string { return proto.CompactTextString(m) }
func (*MintToken) ProtoMessage()    {}
func (*MintToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{11}
}

func (m *MintToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintToken.Unmarshal(m, b)
}
func (m *MintToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintToken.Marshal(b, m, deterministic)
}
func (m *MintToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintToken.Merge(m, src)
}
func (m *MintToken) XXX_Size() int {
	return xxx_messageInfo_MintToken.Size(m)
}
func (m *MintToken) XXX_DiscardUnknown() {
	xxx_messageInfo_MintToken.DiscardUnknown(m)
}

var xxx_messageInfo_MintToken proto.InternalMessageInfo

func (m *MintToken) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MintToken) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *MintToken) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ApproveAllowance struct {
	OwnerKey             string   `protobuf:"bytes,1,opt,name=ownerKey,proto3" json:"ownerKey,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveAllowance) Reset()         { *m = ApproveAllowance{} }
func (m *ApproveAllowance) String() string { return proto.CompactTextString(m) }
func (*ApproveAllowance) ProtoMessage()    {}
func (*ApproveAllowance) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{12}
}

func (m *ApproveAllowance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveAllowance.Unmarshal(m, b)
}
func (m *ApproveAllowance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveAllowance.Marshal(b, m, deterministic)
}
func (m *ApproveAllowance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveAllowance.Merge(m, src)
}
func (m *ApproveAllowance) XXX_Size() int {
	return xxx_messageInfo_ApproveAllowance.Size(m)
}
func (m *ApproveAllowance) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveAllowance.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveAllowance proto.InternalMessageInfo

func (m *ApproveAllowance) GetOwnerKey() string {
	if m != nil {
		return m.OwnerKey
	}
	return ""
}

func (m *ApproveAllowance) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *ApproveAllowance) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type LockEthErc20 struct {
	OwnerKey  string `protobuf:"bytes,1,opt,name=ownerKey,proto3" json:"ownerKey,omitempty"`
	TokenAddr string `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Amount    int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	//将lock住的资产跨链转移到chain33的该账户名下
	Chain33Receiver      string   `protobuf:"bytes,4,opt,name=chain33Receiver,proto3" json:"chain33Receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockEthErc20) Reset()         { *m = LockEthErc20{} }
func (m *LockEthErc20) String() string { return proto.CompactTextString(m) }
func (*LockEthErc20) ProtoMessage()    {}
func (*LockEthErc20) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{13}
}

func (m *LockEthErc20) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockEthErc20.Unmarshal(m, b)
}
func (m *LockEthErc20) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockEthErc20.Marshal(b, m, deterministic)
}
func (m *LockEthErc20) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockEthErc20.Merge(m, src)
}
func (m *LockEthErc20) XXX_Size() int {
	return xxx_messageInfo_LockEthErc20.Size(m)
}
func (m *LockEthErc20) XXX_DiscardUnknown() {
	xxx_messageInfo_LockEthErc20.DiscardUnknown(m)
}

var xxx_messageInfo_LockEthErc20 proto.InternalMessageInfo

func (m *LockEthErc20) GetOwnerKey() string {
	if m != nil {
		return m.OwnerKey
	}
	return ""
}

func (m *LockEthErc20) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *LockEthErc20) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *LockEthErc20) GetChain33Receiver() string {
	if m != nil {
		return m.Chain33Receiver
	}
	return ""
}

type Burn struct {
	OwnerKey             string   `protobuf:"bytes,1,opt,name=ownerKey,proto3" json:"ownerKey,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Chain33Receiver      string   `protobuf:"bytes,4,opt,name=chain33Receiver,proto3" json:"chain33Receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Burn) Reset()         { *m = Burn{} }
func (m *Burn) String() string { return proto.CompactTextString(m) }
func (*Burn) ProtoMessage()    {}
func (*Burn) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{14}
}

func (m *Burn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Burn.Unmarshal(m, b)
}
func (m *Burn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Burn.Marshal(b, m, deterministic)
}
func (m *Burn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Burn.Merge(m, src)
}
func (m *Burn) XXX_Size() int {
	return xxx_messageInfo_Burn.Size(m)
}
func (m *Burn) XXX_DiscardUnknown() {
	xxx_messageInfo_Burn.DiscardUnknown(m)
}

var xxx_messageInfo_Burn proto.InternalMessageInfo

func (m *Burn) GetOwnerKey() string {
	if m != nil {
		return m.OwnerKey
	}
	return ""
}

func (m *Burn) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *Burn) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Burn) GetChain33Receiver() string {
	if m != nil {
		return m.Chain33Receiver
	}
	return ""
}

type StaticsRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsRequest) Reset()         { *m = StaticsRequest{} }
func (m *StaticsRequest) String() string { return proto.CompactTextString(m) }
func (*StaticsRequest) ProtoMessage()    {}
func (*StaticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{15}
}

func (m *StaticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsRequest.Unmarshal(m, b)
}
func (m *StaticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsRequest.Marshal(b, m, deterministic)
}
func (m *StaticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsRequest.Merge(m, src)
}
func (m *StaticsRequest) XXX_Size() int {
	return xxx_messageInfo_StaticsRequest.Size(m)
}
func (m *StaticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsRequest proto.InternalMessageInfo

func (m *StaticsRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *StaticsRequest) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

type StaticsAll struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsAll) Reset()         { *m = StaticsAll{} }
func (m *StaticsAll) String() string { return proto.CompactTextString(m) }
func (*StaticsAll) ProtoMessage()    {}
func (*StaticsAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{16}
}

func (m *StaticsAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsAll.Unmarshal(m, b)
}
func (m *StaticsAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsAll.Marshal(b, m, deterministic)
}
func (m *StaticsAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsAll.Merge(m, src)
}
func (m *StaticsAll) XXX_Size() int {
	return xxx_messageInfo_StaticsAll.Size(m)
}
func (m *StaticsAll) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsAll.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsAll proto.InternalMessageInfo

type StaticsSingle struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsSingle) Reset()         { *m = StaticsSingle{} }
func (m *StaticsSingle) String() string { return proto.CompactTextString(m) }
func (*StaticsSingle) ProtoMessage()    {}
func (*StaticsSingle) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{17}
}

func (m *StaticsSingle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsSingle.Unmarshal(m, b)
}
func (m *StaticsSingle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsSingle.Marshal(b, m, deterministic)
}
func (m *StaticsSingle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsSingle.Merge(m, src)
}
func (m *StaticsSingle) XXX_Size() int {
	return xxx_messageInfo_StaticsSingle.Size(m)
}
func (m *StaticsSingle) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsSingle.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsSingle proto.InternalMessageInfo

type StaticsResponse struct {
	StaticsAll           *StaticsAll    `protobuf:"bytes,1,opt,name=staticsAll,proto3" json:"staticsAll,omitempty"`
	StaticsSingle        *StaticsSingle `protobuf:"bytes,2,opt,name=staticsSingle,proto3" json:"staticsSingle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StaticsResponse) Reset()         { *m = StaticsResponse{} }
func (m *StaticsResponse) String() string { return proto.CompactTextString(m) }
func (*StaticsResponse) ProtoMessage()    {}
func (*StaticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{18}
}

func (m *StaticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsResponse.Unmarshal(m, b)
}
func (m *StaticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsResponse.Marshal(b, m, deterministic)
}
func (m *StaticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsResponse.Merge(m, src)
}
func (m *StaticsResponse) XXX_Size() int {
	return xxx_messageInfo_StaticsResponse.Size(m)
}
func (m *StaticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsResponse proto.InternalMessageInfo

func (m *StaticsResponse) GetStaticsAll() *StaticsAll {
	if m != nil {
		return m.StaticsAll
	}
	return nil
}

func (m *StaticsResponse) GetStaticsSingle() *StaticsSingle {
	if m != nil {
		return m.StaticsSingle
	}
	return nil
}

func init() {
	proto.RegisterType((*Account4Relayer)(nil), "types.Account4Relayer")
	proto.RegisterType((*ValidatorAddr4EthRelayer)(nil), "types.ValidatorAddr4EthRelayer")
	proto.RegisterType((*Txhashes)(nil), "types.Txhashes")
	proto.RegisterType((*ReqSetPasswd)(nil), "types.ReqSetPasswd")
	proto.RegisterType((*Account4Show)(nil), "types.Account4Show")
	proto.RegisterType((*AssetType)(nil), "types.assetType")
	proto.RegisterType((*EthBridgeClaim)(nil), "types.EthBridgeClaim")
	proto.RegisterType((*ImportKeyReq)(nil), "types.ImportKeyReq")
	proto.RegisterType((*RelayerRunStatus)(nil), "types.RelayerRunStatus")
	proto.RegisterType((*NewProphecyClaim)(nil), "types.NewProphecyClaim")
	proto.RegisterType((*BalanceAddr)(nil), "types.BalanceAddr")
	proto.RegisterType((*MintToken)(nil), "types.MintToken")
	proto.RegisterType((*ApproveAllowance)(nil), "types.ApproveAllowance")
	proto.RegisterType((*LockEthErc20)(nil), "types.LockEthErc20")
	proto.RegisterType((*Burn)(nil), "types.Burn")
	proto.RegisterType((*StaticsRequest)(nil), "types.StaticsRequest")
	proto.RegisterType((*StaticsAll)(nil), "types.StaticsAll")
	proto.RegisterType((*StaticsSingle)(nil), "types.StaticsSingle")
	proto.RegisterType((*StaticsResponse)(nil), "types.StaticsResponse")
}

func init() {
	proto.RegisterFile("relayer.proto", fileDescriptor_202a89775a80bd4c)
}

var fileDescriptor_202a89775a80bd4c = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x4f, 0x6b, 0xdb, 0x48,
	0x14, 0x47, 0xf1, 0x9f, 0x44, 0xcf, 0x72, 0xec, 0x1d, 0xbc, 0x8b, 0x58, 0x96, 0xc5, 0x0c, 0x61,
	0x31, 0x7b, 0x30, 0xad, 0x93, 0x53, 0x29, 0x14, 0x27, 0xf1, 0x21, 0xa4, 0x0d, 0x41, 0x0e, 0xe9,
	0xb1, 0x4c, 0xa4, 0x47, 0xa4, 0x46, 0xd6, 0x28, 0x33, 0xe3, 0xb8, 0xbe, 0x95, 0x1e, 0xfb, 0x39,
	0xfa, 0x59, 0xfa, 0xb9, 0xca, 0x8c, 0xc6, 0xb6, 0xe4, 0x84, 0x1e, 0x42, 0xa1, 0xb7, 0x79, 0xbf,
	0xf7, 0xe6, 0xf7, 0x7e, 0xef, 0xcf, 0x48, 0xd0, 0x16, 0x98, 0xb2, 0x25, 0x8a, 0x61, 0x2e, 0xb8,
	0xe2, 0xa4, 0xa1, 0x96, 0x39, 0x4a, 0xfa, 0x06, 0x3a, 0xe3, 0x30, 0xe4, 0xf3, 0x4c, 0x1d, 0x05,
	0x85, 0x9f, 0xf8, 0xb0, 0x9b, 0x8b, 0xe4, 0xe1, 0x0e, 0x97, 0xbe, 0xd3, 0x77, 0x06, 0x5e, 0xb0,
	0x32, 0x09, 0x81, 0x3a, 0x8b, 0x22, 0xe1, 0xef, 0xf4, 0x9d, 0x81, 0x1b, 0x98, 0x33, 0xfd, 0x08,
	0xfe, 0x35, 0x4b, 0x93, 0x88, 0x29, 0x2e, 0xc6, 0x51, 0x24, 0x8e, 0x26, 0x2a, 0x5e, 0x31, 0x51,
	0xf0, 0x50, 0xc5, 0x6b, 0xb7, 0xa1, 0x73, 0x83, 0x0a, 0x46, 0xfe, 0x87, 0x6e, 0x18, 0xb3, 0x24,
	0x3b, 0x3c, 0xdc, 0xc4, 0x15, 0xfc, 0x8f, 0x70, 0x4a, 0x61, 0xef, 0xea, 0x53, 0xcc, 0x64, 0x8c,
	0x92, 0xfc, 0x05, 0x4d, 0x65, 0xce, 0xbe, 0xd3, 0xaf, 0x0d, 0xdc, 0xc0, 0x5a, 0xf4, 0x1a, 0xbc,
	0x00, 0xef, 0xa7, 0xa8, 0x2e, 0x99, 0x94, 0x8b, 0x48, 0x6b, 0xe0, 0x69, 0xa4, 0x8d, 0x3c, 0x66,
	0x12, 0x57, 0x1a, 0xca, 0x98, 0x8e, 0xc9, 0x70, 0xb1, 0x89, 0x29, 0xf2, 0x57, 0x30, 0xfa, 0x1a,
	0xbc, 0x55, 0xa3, 0xa6, 0x31, 0x5f, 0x6c, 0x77, 0xc9, 0xfd, 0x79, 0x97, 0x3e, 0x80, 0xcb, 0xa4,
	0x44, 0x75, 0xb5, 0xcc, 0x91, 0xf4, 0xa0, 0x61, 0x4a, 0xb3, 0x17, 0x0b, 0x83, 0x1c, 0x40, 0x3b,
	0x91, 0x72, 0x8e, 0x27, 0x3c, 0x53, 0x82, 0x85, 0xca, 0xde, 0xaf, 0x82, 0xba, 0x6c, 0xb9, 0x9c,
	0xdd, 0xf0, 0xd4, 0xaf, 0x19, 0xb7, 0xb5, 0xe8, 0xb7, 0x1a, 0xec, 0x4f, 0x54, 0x7c, 0x2c, 0x92,
	0xe8, 0x16, 0x4f, 0x52, 0x96, 0xcc, 0xc8, 0x00, 0x3a, 0xa8, 0x62, 0x14, 0x38, 0x9f, 0x9d, 0xe8,
	0x0c, 0x67, 0xa7, 0x26, 0x61, 0x23, 0xd8, 0x86, 0xc9, 0x11, 0xfc, 0x79, 0x53, 0x5c, 0xb4, 0x69,
	0xf4, 0x20, 0x51, 0x4a, 0x23, 0xc1, 0x0b, 0x9e, 0x76, 0xea, 0x32, 0x32, 0x9e, 0x85, 0x68, 0x94,
	0xd4, 0x82, 0xc2, 0x20, 0x23, 0xe8, 0x29, 0x7e, 0x87, 0xd9, 0x36, 0x55, 0xdd, 0x50, 0x3d, 0xe9,
	0x2b, 0x15, 0xd5, 0x28, 0x17, 0x45, 0xfe, 0x83, 0xfd, 0x95, 0xd4, 0x29, 0x66, 0x11, 0x0a, 0xbf,
	0x69, 0x58, 0xb6, 0x50, 0x5d, 0xa9, 0xdd, 0x95, 0x00, 0x43, 0x4c, 0x1e, 0x50, 0xf8, 0xbb, 0x26,
	0x70, 0x1b, 0xd6, 0xdb, 0x56, 0xd9, 0x56, 0xad, 0x6c, 0xcf, 0x84, 0x3e, 0xc2, 0xb5, 0x2a, 0x36,
	0xd3, 0x03, 0xf7, 0x5d, 0x53, 0xa0, 0xb5, 0xc8, 0x3f, 0xe0, 0x86, 0xba, 0xc1, 0x7a, 0x96, 0x3e,
	0x98, 0x8e, 0x6e, 0x00, 0xe3, 0xd5, 0x49, 0x2f, 0xd8, 0x0c, 0xfd, 0x96, 0x29, 0x67, 0x03, 0xd0,
	0x21, 0x78, 0x67, 0xb3, 0x9c, 0x0b, 0x75, 0x8e, 0xcb, 0x00, 0xef, 0xc9, 0xbf, 0x00, 0x7a, 0x6d,
	0x98, 0xc2, 0xf3, 0xf5, 0x22, 0x95, 0x10, 0x7a, 0x0a, 0x5d, 0xfb, 0x98, 0x82, 0x79, 0x36, 0x55,
	0x4c, 0xcd, 0x8b, 0x6e, 0x99, 0x93, 0x1d, 0xa7, 0xb5, 0xf4, 0x46, 0x46, 0xa8, 0x58, 0x92, 0x4a,
	0xbb, 0x3a, 0x2b, 0x93, 0x7e, 0x77, 0xa0, 0x7b, 0x81, 0x8b, 0x4b, 0xc1, 0xf3, 0x18, 0xc3, 0x65,
	0xb1, 0x1e, 0x95, 0x32, 0x34, 0x53, 0xbb, 0x5c, 0xc6, 0x01, 0xb4, 0x6d, 0xef, 0x6c, 0xe7, 0xed,
	0x36, 0x56, 0x40, 0xcd, 0x61, 0x06, 0xaa, 0x5b, 0x66, 0x17, 0x72, 0x03, 0x94, 0xc6, 0x5a, 0xaf,
	0x8c, 0xb5, 0x0f, 0x2d, 0xd4, 0x1f, 0x09, 0x3b, 0xaa, 0x62, 0xe6, 0x65, 0xa8, 0xd4, 0xfa, 0x66,
	0xb9, 0xf5, 0x74, 0x0c, 0xad, 0x63, 0x96, 0xb2, 0x2c, 0x44, 0x93, 0xa0, 0x07, 0x0d, 0xbe, 0xc8,
	0x70, 0xf5, 0x61, 0x29, 0x8c, 0xaa, 0xa8, 0x9d, 0x2d, 0x51, 0xf4, 0x3d, 0xb8, 0xef, 0x92, 0x4c,
	0x5d, 0x69, 0xe0, 0x39, 0x04, 0x25, 0x6d, 0xb5, 0x8a, 0xb6, 0x08, 0xba, 0xe3, 0x3c, 0x17, 0xfc,
	0x01, 0xc7, 0x69, 0xca, 0x17, 0x5a, 0x24, 0xf9, 0x1b, 0xf6, 0x0c, 0xe5, 0x66, 0xb8, 0x6b, 0xfb,
	0x99, 0x59, 0xbe, 0x3a, 0xe0, 0xbd, 0xe5, 0xe1, 0xdd, 0x44, 0xc5, 0x13, 0x11, 0x8e, 0x5e, 0xfc,
	0xfa, 0x14, 0x4f, 0xbd, 0xa6, 0x62, 0x7e, 0xdb, 0x30, 0xfd, 0xe2, 0x40, 0xfd, 0x78, 0x2e, 0xb2,
	0xdf, 0x2a, 0xe2, 0x14, 0xf6, 0xf5, 0xc3, 0x48, 0x42, 0x19, 0xe0, 0xfd, 0x1c, 0xa5, 0x7a, 0xd6,
	0x5a, 0x78, 0x00, 0x96, 0x65, 0x9c, 0xa6, 0xb4, 0x03, 0x6d, 0x6b, 0x4d, 0x93, 0xec, 0x36, 0x45,
	0xfa, 0xd9, 0x81, 0xce, 0x3a, 0x8b, 0xcc, 0x79, 0x26, 0x91, 0xbc, 0x04, 0x90, 0xeb, 0x2b, 0x26,
	0x57, 0x6b, 0xf4, 0xc7, 0xd0, 0xfc, 0x56, 0x87, 0x1b, 0xae, 0xa0, 0x14, 0x44, 0x5e, 0x41, 0x5b,
	0x96, 0x79, 0x8d, 0x8e, 0xd6, 0xa8, 0x57, 0xbd, 0x55, 0xf8, 0x82, 0x6a, 0xe8, 0x4d, 0xd3, 0xfc,
	0xb7, 0x0f, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x41, 0x55, 0x42, 0xd4, 0xc8, 0x07, 0x00, 0x00,
}
