// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relayer.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//以太坊账户信息
// 	 privkey : 账户地址对应的私钥
//	 addr :账户地址
type Account4Relayer struct {
	Privkey              []byte   `protobuf:"bytes,1,opt,name=privkey,proto3" json:"privkey,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account4Relayer) Reset()         { *m = Account4Relayer{} }
func (m *Account4Relayer) String() string { return proto.CompactTextString(m) }
func (*Account4Relayer) ProtoMessage()    {}
func (*Account4Relayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{0}
}

func (m *Account4Relayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account4Relayer.Unmarshal(m, b)
}
func (m *Account4Relayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account4Relayer.Marshal(b, m, deterministic)
}
func (m *Account4Relayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account4Relayer.Merge(m, src)
}
func (m *Account4Relayer) XXX_Size() int {
	return xxx_messageInfo_Account4Relayer.Size(m)
}
func (m *Account4Relayer) XXX_DiscardUnknown() {
	xxx_messageInfo_Account4Relayer.DiscardUnknown(m)
}

var xxx_messageInfo_Account4Relayer proto.InternalMessageInfo

func (m *Account4Relayer) GetPrivkey() []byte {
	if m != nil {
		return m.Privkey
	}
	return nil
}

func (m *Account4Relayer) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ValidatorAddr4EthRelayer struct {
	Chain33Validator     string   `protobuf:"bytes,1,opt,name=chain33Validator,proto3" json:"chain33Validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorAddr4EthRelayer) Reset()         { *m = ValidatorAddr4EthRelayer{} }
func (m *ValidatorAddr4EthRelayer) String() string { return proto.CompactTextString(m) }
func (*ValidatorAddr4EthRelayer) ProtoMessage()    {}
func (*ValidatorAddr4EthRelayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{1}
}

func (m *ValidatorAddr4EthRelayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorAddr4EthRelayer.Unmarshal(m, b)
}
func (m *ValidatorAddr4EthRelayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorAddr4EthRelayer.Marshal(b, m, deterministic)
}
func (m *ValidatorAddr4EthRelayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorAddr4EthRelayer.Merge(m, src)
}
func (m *ValidatorAddr4EthRelayer) XXX_Size() int {
	return xxx_messageInfo_ValidatorAddr4EthRelayer.Size(m)
}
func (m *ValidatorAddr4EthRelayer) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorAddr4EthRelayer.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorAddr4EthRelayer proto.InternalMessageInfo

func (m *ValidatorAddr4EthRelayer) GetChain33Validator() string {
	if m != nil {
		return m.Chain33Validator
	}
	return ""
}

type Txhashes struct {
	Txhash               []string `protobuf:"bytes,1,rep,name=txhash,proto3" json:"txhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Txhashes) Reset()         { *m = Txhashes{} }
func (m *Txhashes) String() string { return proto.CompactTextString(m) }
func (*Txhashes) ProtoMessage()    {}
func (*Txhashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{2}
}

func (m *Txhashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Txhashes.Unmarshal(m, b)
}
func (m *Txhashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Txhashes.Marshal(b, m, deterministic)
}
func (m *Txhashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Txhashes.Merge(m, src)
}
func (m *Txhashes) XXX_Size() int {
	return xxx_messageInfo_Txhashes.Size(m)
}
func (m *Txhashes) XXX_DiscardUnknown() {
	xxx_messageInfo_Txhashes.DiscardUnknown(m)
}

var xxx_messageInfo_Txhashes proto.InternalMessageInfo

func (m *Txhashes) GetTxhash() []string {
	if m != nil {
		return m.Txhash
	}
	return nil
}

type ReqChangePasswd struct {
	OldPassphase         string   `protobuf:"bytes,1,opt,name=oldPassphase,proto3" json:"oldPassphase,omitempty"`
	NewPassphase         string   `protobuf:"bytes,2,opt,name=newPassphase,proto3" json:"newPassphase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqChangePasswd) Reset()         { *m = ReqChangePasswd{} }
func (m *ReqChangePasswd) String() string { return proto.CompactTextString(m) }
func (*ReqChangePasswd) ProtoMessage()    {}
func (*ReqChangePasswd) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{3}
}

func (m *ReqChangePasswd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqChangePasswd.Unmarshal(m, b)
}
func (m *ReqChangePasswd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqChangePasswd.Marshal(b, m, deterministic)
}
func (m *ReqChangePasswd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqChangePasswd.Merge(m, src)
}
func (m *ReqChangePasswd) XXX_Size() int {
	return xxx_messageInfo_ReqChangePasswd.Size(m)
}
func (m *ReqChangePasswd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqChangePasswd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqChangePasswd proto.InternalMessageInfo

func (m *ReqChangePasswd) GetOldPassphase() string {
	if m != nil {
		return m.OldPassphase
	}
	return ""
}

func (m *ReqChangePasswd) GetNewPassphase() string {
	if m != nil {
		return m.NewPassphase
	}
	return ""
}

type ReqSetPasswd struct {
	Passphase            string   `protobuf:"bytes,1,opt,name=Passphase,proto3" json:"Passphase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSetPasswd) Reset()         { *m = ReqSetPasswd{} }
func (m *ReqSetPasswd) String() string { return proto.CompactTextString(m) }
func (*ReqSetPasswd) ProtoMessage()    {}
func (*ReqSetPasswd) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{4}
}

func (m *ReqSetPasswd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSetPasswd.Unmarshal(m, b)
}
func (m *ReqSetPasswd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSetPasswd.Marshal(b, m, deterministic)
}
func (m *ReqSetPasswd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSetPasswd.Merge(m, src)
}
func (m *ReqSetPasswd) XXX_Size() int {
	return xxx_messageInfo_ReqSetPasswd.Size(m)
}
func (m *ReqSetPasswd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSetPasswd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSetPasswd proto.InternalMessageInfo

func (m *ReqSetPasswd) GetPassphase() string {
	if m != nil {
		return m.Passphase
	}
	return ""
}

type Account4Show struct {
	Privkey              string   `protobuf:"bytes,1,opt,name=privkey,proto3" json:"privkey,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account4Show) Reset()         { *m = Account4Show{} }
func (m *Account4Show) String() string { return proto.CompactTextString(m) }
func (*Account4Show) ProtoMessage()    {}
func (*Account4Show) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{5}
}

func (m *Account4Show) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account4Show.Unmarshal(m, b)
}
func (m *Account4Show) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account4Show.Marshal(b, m, deterministic)
}
func (m *Account4Show) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account4Show.Merge(m, src)
}
func (m *Account4Show) XXX_Size() int {
	return xxx_messageInfo_Account4Show.Size(m)
}
func (m *Account4Show) XXX_DiscardUnknown() {
	xxx_messageInfo_Account4Show.DiscardUnknown(m)
}

var xxx_messageInfo_Account4Show proto.InternalMessageInfo

func (m *Account4Show) GetPrivkey() string {
	if m != nil {
		return m.Privkey
	}
	return ""
}

func (m *Account4Show) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type AssetType struct {
	Chain                string   `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	IssueContract        string   `protobuf:"bytes,2,opt,name=issueContract,proto3" json:"issueContract,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetType) Reset()         { *m = AssetType{} }
func (m *AssetType) String() string { return proto.CompactTextString(m) }
func (*AssetType) ProtoMessage()    {}
func (*AssetType) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{6}
}

func (m *AssetType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetType.Unmarshal(m, b)
}
func (m *AssetType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetType.Marshal(b, m, deterministic)
}
func (m *AssetType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetType.Merge(m, src)
}
func (m *AssetType) XXX_Size() int {
	return xxx_messageInfo_AssetType.Size(m)
}
func (m *AssetType) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetType.DiscardUnknown(m)
}

var xxx_messageInfo_AssetType proto.InternalMessageInfo

func (m *AssetType) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *AssetType) GetIssueContract() string {
	if m != nil {
		return m.IssueContract
	}
	return ""
}

func (m *AssetType) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type EthBridgeClaim struct {
	EthereumChainID      int64    `protobuf:"varint,1,opt,name=ethereumChainID,proto3" json:"ethereumChainID,omitempty"`
	BridgeBrankAddr      string   `protobuf:"bytes,2,opt,name=bridgeBrankAddr,proto3" json:"bridgeBrankAddr,omitempty"`
	Nonce                int64    `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TokenAddr            string   `protobuf:"bytes,4,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Symbol               string   `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	EthereumSender       string   `protobuf:"bytes,6,opt,name=ethereumSender,proto3" json:"ethereumSender,omitempty"`
	Chain33Receiver      string   `protobuf:"bytes,7,opt,name=chain33Receiver,proto3" json:"chain33Receiver,omitempty"`
	Amount               int64    `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	ClaimType            int32    `protobuf:"varint,10,opt,name=claimType,proto3" json:"claimType,omitempty"`
	ChainName            string   `protobuf:"bytes,11,opt,name=chainName,proto3" json:"chainName,omitempty"`
	Decimal              int64    `protobuf:"varint,12,opt,name=decimal,proto3" json:"decimal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EthBridgeClaim) Reset()         { *m = EthBridgeClaim{} }
func (m *EthBridgeClaim) String() string { return proto.CompactTextString(m) }
func (*EthBridgeClaim) ProtoMessage()    {}
func (*EthBridgeClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{7}
}

func (m *EthBridgeClaim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EthBridgeClaim.Unmarshal(m, b)
}
func (m *EthBridgeClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EthBridgeClaim.Marshal(b, m, deterministic)
}
func (m *EthBridgeClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthBridgeClaim.Merge(m, src)
}
func (m *EthBridgeClaim) XXX_Size() int {
	return xxx_messageInfo_EthBridgeClaim.Size(m)
}
func (m *EthBridgeClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_EthBridgeClaim.DiscardUnknown(m)
}

var xxx_messageInfo_EthBridgeClaim proto.InternalMessageInfo

func (m *EthBridgeClaim) GetEthereumChainID() int64 {
	if m != nil {
		return m.EthereumChainID
	}
	return 0
}

func (m *EthBridgeClaim) GetBridgeBrankAddr() string {
	if m != nil {
		return m.BridgeBrankAddr
	}
	return ""
}

func (m *EthBridgeClaim) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *EthBridgeClaim) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *EthBridgeClaim) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *EthBridgeClaim) GetEthereumSender() string {
	if m != nil {
		return m.EthereumSender
	}
	return ""
}

func (m *EthBridgeClaim) GetChain33Receiver() string {
	if m != nil {
		return m.Chain33Receiver
	}
	return ""
}

func (m *EthBridgeClaim) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *EthBridgeClaim) GetClaimType() int32 {
	if m != nil {
		return m.ClaimType
	}
	return 0
}

func (m *EthBridgeClaim) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *EthBridgeClaim) GetDecimal() int64 {
	if m != nil {
		return m.Decimal
	}
	return 0
}

type ImportKeyReq struct {
	PrivateKey           string   `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportKeyReq) Reset()         { *m = ImportKeyReq{} }
func (m *ImportKeyReq) String() string { return proto.CompactTextString(m) }
func (*ImportKeyReq) ProtoMessage()    {}
func (*ImportKeyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{8}
}

func (m *ImportKeyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportKeyReq.Unmarshal(m, b)
}
func (m *ImportKeyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportKeyReq.Marshal(b, m, deterministic)
}
func (m *ImportKeyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportKeyReq.Merge(m, src)
}
func (m *ImportKeyReq) XXX_Size() int {
	return xxx_messageInfo_ImportKeyReq.Size(m)
}
func (m *ImportKeyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportKeyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ImportKeyReq proto.InternalMessageInfo

func (m *ImportKeyReq) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type RelayerRunStatus struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayerRunStatus) Reset()         { *m = RelayerRunStatus{} }
func (m *RelayerRunStatus) String() string { return proto.CompactTextString(m) }
func (*RelayerRunStatus) ProtoMessage()    {}
func (*RelayerRunStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{9}
}

func (m *RelayerRunStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayerRunStatus.Unmarshal(m, b)
}
func (m *RelayerRunStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayerRunStatus.Marshal(b, m, deterministic)
}
func (m *RelayerRunStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayerRunStatus.Merge(m, src)
}
func (m *RelayerRunStatus) XXX_Size() int {
	return xxx_messageInfo_RelayerRunStatus.Size(m)
}
func (m *RelayerRunStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayerRunStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RelayerRunStatus proto.InternalMessageInfo

func (m *RelayerRunStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RelayerRunStatus) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type NewProphecyClaim struct {
	ClaimType            uint32   `protobuf:"varint,1,opt,name=claimType,proto3" json:"claimType,omitempty"`
	Chain33Sender        string   `protobuf:"bytes,2,opt,name=chain33Sender,proto3" json:"chain33Sender,omitempty"`
	TokenAddr            string   `protobuf:"bytes,3,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Symbol               string   `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	EthReceiver          string   `protobuf:"bytes,5,opt,name=ethReceiver,proto3" json:"ethReceiver,omitempty"`
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	TxHash               string   `protobuf:"bytes,7,opt,name=txHash,proto3" json:"txHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewProphecyClaim) Reset()         { *m = NewProphecyClaim{} }
func (m *NewProphecyClaim) String() string { return proto.CompactTextString(m) }
func (*NewProphecyClaim) ProtoMessage()    {}
func (*NewProphecyClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{10}
}

func (m *NewProphecyClaim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProphecyClaim.Unmarshal(m, b)
}
func (m *NewProphecyClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProphecyClaim.Marshal(b, m, deterministic)
}
func (m *NewProphecyClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProphecyClaim.Merge(m, src)
}
func (m *NewProphecyClaim) XXX_Size() int {
	return xxx_messageInfo_NewProphecyClaim.Size(m)
}
func (m *NewProphecyClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProphecyClaim.DiscardUnknown(m)
}

var xxx_messageInfo_NewProphecyClaim proto.InternalMessageInfo

func (m *NewProphecyClaim) GetClaimType() uint32 {
	if m != nil {
		return m.ClaimType
	}
	return 0
}

func (m *NewProphecyClaim) GetChain33Sender() string {
	if m != nil {
		return m.Chain33Sender
	}
	return ""
}

func (m *NewProphecyClaim) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *NewProphecyClaim) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *NewProphecyClaim) GetEthReceiver() string {
	if m != nil {
		return m.EthReceiver
	}
	return ""
}

func (m *NewProphecyClaim) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *NewProphecyClaim) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type BalanceAddr struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceAddr) Reset()         { *m = BalanceAddr{} }
func (m *BalanceAddr) String() string { return proto.CompactTextString(m) }
func (*BalanceAddr) ProtoMessage()    {}
func (*BalanceAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{11}
}

func (m *BalanceAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceAddr.Unmarshal(m, b)
}
func (m *BalanceAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceAddr.Marshal(b, m, deterministic)
}
func (m *BalanceAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceAddr.Merge(m, src)
}
func (m *BalanceAddr) XXX_Size() int {
	return xxx_messageInfo_BalanceAddr.Size(m)
}
func (m *BalanceAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceAddr.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceAddr proto.InternalMessageInfo

func (m *BalanceAddr) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *BalanceAddr) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

type MintToken struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MintToken) Reset()         { *m = MintToken{} }
func (m *MintToken) String() string { return proto.CompactTextString(m) }
func (*MintToken) ProtoMessage()    {}
func (*MintToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{12}
}

func (m *MintToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintToken.Unmarshal(m, b)
}
func (m *MintToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintToken.Marshal(b, m, deterministic)
}
func (m *MintToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintToken.Merge(m, src)
}
func (m *MintToken) XXX_Size() int {
	return xxx_messageInfo_MintToken.Size(m)
}
func (m *MintToken) XXX_DiscardUnknown() {
	xxx_messageInfo_MintToken.DiscardUnknown(m)
}

var xxx_messageInfo_MintToken proto.InternalMessageInfo

func (m *MintToken) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MintToken) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *MintToken) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type ApproveAllowance struct {
	OwnerKey             string   `protobuf:"bytes,1,opt,name=ownerKey,proto3" json:"ownerKey,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveAllowance) Reset()         { *m = ApproveAllowance{} }
func (m *ApproveAllowance) String() string { return proto.CompactTextString(m) }
func (*ApproveAllowance) ProtoMessage()    {}
func (*ApproveAllowance) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{13}
}

func (m *ApproveAllowance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveAllowance.Unmarshal(m, b)
}
func (m *ApproveAllowance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveAllowance.Marshal(b, m, deterministic)
}
func (m *ApproveAllowance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveAllowance.Merge(m, src)
}
func (m *ApproveAllowance) XXX_Size() int {
	return xxx_messageInfo_ApproveAllowance.Size(m)
}
func (m *ApproveAllowance) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveAllowance.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveAllowance proto.InternalMessageInfo

func (m *ApproveAllowance) GetOwnerKey() string {
	if m != nil {
		return m.OwnerKey
	}
	return ""
}

func (m *ApproveAllowance) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *ApproveAllowance) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type LockEthErc20 struct {
	OwnerKey  string `protobuf:"bytes,1,opt,name=ownerKey,proto3" json:"ownerKey,omitempty"`
	TokenAddr string `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Amount    string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	//将lock住的资产跨链转移到chain33的该账户名下
	Chain33Receiver      string   `protobuf:"bytes,4,opt,name=chain33Receiver,proto3" json:"chain33Receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockEthErc20) Reset()         { *m = LockEthErc20{} }
func (m *LockEthErc20) String() string { return proto.CompactTextString(m) }
func (*LockEthErc20) ProtoMessage()    {}
func (*LockEthErc20) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{14}
}

func (m *LockEthErc20) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockEthErc20.Unmarshal(m, b)
}
func (m *LockEthErc20) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockEthErc20.Marshal(b, m, deterministic)
}
func (m *LockEthErc20) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockEthErc20.Merge(m, src)
}
func (m *LockEthErc20) XXX_Size() int {
	return xxx_messageInfo_LockEthErc20.Size(m)
}
func (m *LockEthErc20) XXX_DiscardUnknown() {
	xxx_messageInfo_LockEthErc20.DiscardUnknown(m)
}

var xxx_messageInfo_LockEthErc20 proto.InternalMessageInfo

func (m *LockEthErc20) GetOwnerKey() string {
	if m != nil {
		return m.OwnerKey
	}
	return ""
}

func (m *LockEthErc20) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *LockEthErc20) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *LockEthErc20) GetChain33Receiver() string {
	if m != nil {
		return m.Chain33Receiver
	}
	return ""
}

type LockBTY struct {
	OwnerKey string `protobuf:"bytes,1,opt,name=ownerKey,proto3" json:"ownerKey,omitempty"`
	Amount   string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	//将lock住的资产跨链转移到ethereum的该账户名下
	EtherumReceiver      string   `protobuf:"bytes,3,opt,name=etherumReceiver,proto3" json:"etherumReceiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockBTY) Reset()         { *m = LockBTY{} }
func (m *LockBTY) String() string { return proto.CompactTextString(m) }
func (*LockBTY) ProtoMessage()    {}
func (*LockBTY) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{15}
}

func (m *LockBTY) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockBTY.Unmarshal(m, b)
}
func (m *LockBTY) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockBTY.Marshal(b, m, deterministic)
}
func (m *LockBTY) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockBTY.Merge(m, src)
}
func (m *LockBTY) XXX_Size() int {
	return xxx_messageInfo_LockBTY.Size(m)
}
func (m *LockBTY) XXX_DiscardUnknown() {
	xxx_messageInfo_LockBTY.DiscardUnknown(m)
}

var xxx_messageInfo_LockBTY proto.InternalMessageInfo

func (m *LockBTY) GetOwnerKey() string {
	if m != nil {
		return m.OwnerKey
	}
	return ""
}

func (m *LockBTY) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *LockBTY) GetEtherumReceiver() string {
	if m != nil {
		return m.EtherumReceiver
	}
	return ""
}

type ReplyAddr struct {
	IsOK                 bool     `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyAddr) Reset()         { *m = ReplyAddr{} }
func (m *ReplyAddr) String() string { return proto.CompactTextString(m) }
func (*ReplyAddr) ProtoMessage()    {}
func (*ReplyAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{16}
}

func (m *ReplyAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAddr.Unmarshal(m, b)
}
func (m *ReplyAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAddr.Marshal(b, m, deterministic)
}
func (m *ReplyAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAddr.Merge(m, src)
}
func (m *ReplyAddr) XXX_Size() int {
	return xxx_messageInfo_ReplyAddr.Size(m)
}
func (m *ReplyAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAddr proto.InternalMessageInfo

func (m *ReplyAddr) GetIsOK() bool {
	if m != nil {
		return m.IsOK
	}
	return false
}

func (m *ReplyAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ReplyBalance struct {
	IsOK                 bool     `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
	Balance              string   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyBalance) Reset()         { *m = ReplyBalance{} }
func (m *ReplyBalance) String() string { return proto.CompactTextString(m) }
func (*ReplyBalance) ProtoMessage()    {}
func (*ReplyBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{17}
}

func (m *ReplyBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyBalance.Unmarshal(m, b)
}
func (m *ReplyBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyBalance.Marshal(b, m, deterministic)
}
func (m *ReplyBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyBalance.Merge(m, src)
}
func (m *ReplyBalance) XXX_Size() int {
	return xxx_messageInfo_ReplyBalance.Size(m)
}
func (m *ReplyBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyBalance proto.InternalMessageInfo

func (m *ReplyBalance) GetIsOK() bool {
	if m != nil {
		return m.IsOK
	}
	return false
}

func (m *ReplyBalance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type Burn struct {
	OwnerKey             string   `protobuf:"bytes,1,opt,name=ownerKey,proto3" json:"ownerKey,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Chain33Receiver      string   `protobuf:"bytes,4,opt,name=chain33Receiver,proto3" json:"chain33Receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Burn) Reset()         { *m = Burn{} }
func (m *Burn) String() string { return proto.CompactTextString(m) }
func (*Burn) ProtoMessage()    {}
func (*Burn) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{18}
}

func (m *Burn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Burn.Unmarshal(m, b)
}
func (m *Burn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Burn.Marshal(b, m, deterministic)
}
func (m *Burn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Burn.Merge(m, src)
}
func (m *Burn) XXX_Size() int {
	return xxx_messageInfo_Burn.Size(m)
}
func (m *Burn) XXX_DiscardUnknown() {
	xxx_messageInfo_Burn.DiscardUnknown(m)
}

var xxx_messageInfo_Burn proto.InternalMessageInfo

func (m *Burn) GetOwnerKey() string {
	if m != nil {
		return m.OwnerKey
	}
	return ""
}

func (m *Burn) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *Burn) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Burn) GetChain33Receiver() string {
	if m != nil {
		return m.Chain33Receiver
	}
	return ""
}

type BurnFromChain33 struct {
	OwnerKey             string   `protobuf:"bytes,1,opt,name=ownerKey,proto3" json:"ownerKey,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	EthereumReceiver     string   `protobuf:"bytes,4,opt,name=ethereumReceiver,proto3" json:"ethereumReceiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BurnFromChain33) Reset()         { *m = BurnFromChain33{} }
func (m *BurnFromChain33) String() string { return proto.CompactTextString(m) }
func (*BurnFromChain33) ProtoMessage()    {}
func (*BurnFromChain33) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{19}
}

func (m *BurnFromChain33) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurnFromChain33.Unmarshal(m, b)
}
func (m *BurnFromChain33) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurnFromChain33.Marshal(b, m, deterministic)
}
func (m *BurnFromChain33) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurnFromChain33.Merge(m, src)
}
func (m *BurnFromChain33) XXX_Size() int {
	return xxx_messageInfo_BurnFromChain33.Size(m)
}
func (m *BurnFromChain33) XXX_DiscardUnknown() {
	xxx_messageInfo_BurnFromChain33.DiscardUnknown(m)
}

var xxx_messageInfo_BurnFromChain33 proto.InternalMessageInfo

func (m *BurnFromChain33) GetOwnerKey() string {
	if m != nil {
		return m.OwnerKey
	}
	return ""
}

func (m *BurnFromChain33) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *BurnFromChain33) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *BurnFromChain33) GetEthereumReceiver() string {
	if m != nil {
		return m.EthereumReceiver
	}
	return ""
}

type StaticsRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsRequest) Reset()         { *m = StaticsRequest{} }
func (m *StaticsRequest) String() string { return proto.CompactTextString(m) }
func (*StaticsRequest) ProtoMessage()    {}
func (*StaticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{20}
}

func (m *StaticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsRequest.Unmarshal(m, b)
}
func (m *StaticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsRequest.Marshal(b, m, deterministic)
}
func (m *StaticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsRequest.Merge(m, src)
}
func (m *StaticsRequest) XXX_Size() int {
	return xxx_messageInfo_StaticsRequest.Size(m)
}
func (m *StaticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsRequest proto.InternalMessageInfo

func (m *StaticsRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *StaticsRequest) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

type StaticsAll struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsAll) Reset()         { *m = StaticsAll{} }
func (m *StaticsAll) String() string { return proto.CompactTextString(m) }
func (*StaticsAll) ProtoMessage()    {}
func (*StaticsAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{21}
}

func (m *StaticsAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsAll.Unmarshal(m, b)
}
func (m *StaticsAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsAll.Marshal(b, m, deterministic)
}
func (m *StaticsAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsAll.Merge(m, src)
}
func (m *StaticsAll) XXX_Size() int {
	return xxx_messageInfo_StaticsAll.Size(m)
}
func (m *StaticsAll) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsAll.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsAll proto.InternalMessageInfo

type StaticsSingle struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsSingle) Reset()         { *m = StaticsSingle{} }
func (m *StaticsSingle) String() string { return proto.CompactTextString(m) }
func (*StaticsSingle) ProtoMessage()    {}
func (*StaticsSingle) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{22}
}

func (m *StaticsSingle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsSingle.Unmarshal(m, b)
}
func (m *StaticsSingle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsSingle.Marshal(b, m, deterministic)
}
func (m *StaticsSingle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsSingle.Merge(m, src)
}
func (m *StaticsSingle) XXX_Size() int {
	return xxx_messageInfo_StaticsSingle.Size(m)
}
func (m *StaticsSingle) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsSingle.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsSingle proto.InternalMessageInfo

type StaticsLockResponse struct {
	All                  *StaticsLock       `protobuf:"bytes,1,opt,name=all,proto3" json:"all,omitempty"`
	Single               *StaticsLockSingle `protobuf:"bytes,2,opt,name=single,proto3" json:"single,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StaticsLockResponse) Reset()         { *m = StaticsLockResponse{} }
func (m *StaticsLockResponse) String() string { return proto.CompactTextString(m) }
func (*StaticsLockResponse) ProtoMessage()    {}
func (*StaticsLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{23}
}

func (m *StaticsLockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsLockResponse.Unmarshal(m, b)
}
func (m *StaticsLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsLockResponse.Marshal(b, m, deterministic)
}
func (m *StaticsLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsLockResponse.Merge(m, src)
}
func (m *StaticsLockResponse) XXX_Size() int {
	return xxx_messageInfo_StaticsLockResponse.Size(m)
}
func (m *StaticsLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsLockResponse proto.InternalMessageInfo

func (m *StaticsLockResponse) GetAll() *StaticsLock {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *StaticsLockResponse) GetSingle() *StaticsLockSingle {
	if m != nil {
		return m.Single
	}
	return nil
}

type StaticsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsResponse) Reset()         { *m = StaticsResponse{} }
func (m *StaticsResponse) String() string { return proto.CompactTextString(m) }
func (*StaticsResponse) ProtoMessage()    {}
func (*StaticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{24}
}

func (m *StaticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsResponse.Unmarshal(m, b)
}
func (m *StaticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsResponse.Marshal(b, m, deterministic)
}
func (m *StaticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsResponse.Merge(m, src)
}
func (m *StaticsResponse) XXX_Size() int {
	return xxx_messageInfo_StaticsResponse.Size(m)
}
func (m *StaticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsResponse proto.InternalMessageInfo

type StaticsLock struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsLock) Reset()         { *m = StaticsLock{} }
func (m *StaticsLock) String() string { return proto.CompactTextString(m) }
func (*StaticsLock) ProtoMessage()    {}
func (*StaticsLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{25}
}

func (m *StaticsLock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsLock.Unmarshal(m, b)
}
func (m *StaticsLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsLock.Marshal(b, m, deterministic)
}
func (m *StaticsLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsLock.Merge(m, src)
}
func (m *StaticsLock) XXX_Size() int {
	return xxx_messageInfo_StaticsLock.Size(m)
}
func (m *StaticsLock) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsLock.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsLock proto.InternalMessageInfo

func (m *StaticsLock) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type StaticsDeposit struct {
	Supply               string   `protobuf:"bytes,1,opt,name=supply,proto3" json:"supply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsDeposit) Reset()         { *m = StaticsDeposit{} }
func (m *StaticsDeposit) String() string { return proto.CompactTextString(m) }
func (*StaticsDeposit) ProtoMessage()    {}
func (*StaticsDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{26}
}

func (m *StaticsDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsDeposit.Unmarshal(m, b)
}
func (m *StaticsDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsDeposit.Marshal(b, m, deterministic)
}
func (m *StaticsDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsDeposit.Merge(m, src)
}
func (m *StaticsDeposit) XXX_Size() int {
	return xxx_messageInfo_StaticsDeposit.Size(m)
}
func (m *StaticsDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsDeposit proto.InternalMessageInfo

func (m *StaticsDeposit) GetSupply() string {
	if m != nil {
		return m.Supply
	}
	return ""
}

type StaticsLockSingle struct {
	TotalLockedAccumated int64    `protobuf:"varint,1,opt,name=totalLockedAccumated,proto3" json:"totalLockedAccumated,omitempty"`
	Locked               []int64  `protobuf:"varint,2,rep,packed,name=locked,proto3" json:"locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticsLockSingle) Reset()         { *m = StaticsLockSingle{} }
func (m *StaticsLockSingle) String() string { return proto.CompactTextString(m) }
func (*StaticsLockSingle) ProtoMessage()    {}
func (*StaticsLockSingle) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{27}
}

func (m *StaticsLockSingle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticsLockSingle.Unmarshal(m, b)
}
func (m *StaticsLockSingle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticsLockSingle.Marshal(b, m, deterministic)
}
func (m *StaticsLockSingle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticsLockSingle.Merge(m, src)
}
func (m *StaticsLockSingle) XXX_Size() int {
	return xxx_messageInfo_StaticsLockSingle.Size(m)
}
func (m *StaticsLockSingle) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticsLockSingle.DiscardUnknown(m)
}

var xxx_messageInfo_StaticsLockSingle proto.InternalMessageInfo

func (m *StaticsLockSingle) GetTotalLockedAccumated() int64 {
	if m != nil {
		return m.TotalLockedAccumated
	}
	return 0
}

func (m *StaticsLockSingle) GetLocked() []int64 {
	if m != nil {
		return m.Locked
	}
	return nil
}

type TransferToken struct {
	TokenAddr            string   `protobuf:"bytes,1,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	FromKey              string   `protobuf:"bytes,2,opt,name=fromKey,proto3" json:"fromKey,omitempty"`
	ToAddr               string   `protobuf:"bytes,3,opt,name=toAddr,proto3" json:"toAddr,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferToken) Reset()         { *m = TransferToken{} }
func (m *TransferToken) String() string { return proto.CompactTextString(m) }
func (*TransferToken) ProtoMessage()    {}
func (*TransferToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{28}
}

func (m *TransferToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferToken.Unmarshal(m, b)
}
func (m *TransferToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferToken.Marshal(b, m, deterministic)
}
func (m *TransferToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferToken.Merge(m, src)
}
func (m *TransferToken) XXX_Size() int {
	return xxx_messageInfo_TransferToken.Size(m)
}
func (m *TransferToken) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferToken.DiscardUnknown(m)
}

var xxx_messageInfo_TransferToken proto.InternalMessageInfo

func (m *TransferToken) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *TransferToken) GetFromKey() string {
	if m != nil {
		return m.FromKey
	}
	return ""
}

func (m *TransferToken) GetToAddr() string {
	if m != nil {
		return m.ToAddr
	}
	return ""
}

func (m *TransferToken) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type Uint64 struct {
	Data                 uint64   `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uint64) Reset()         { *m = Uint64{} }
func (m *Uint64) String() string { return proto.CompactTextString(m) }
func (*Uint64) ProtoMessage()    {}
func (*Uint64) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{29}
}

func (m *Uint64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uint64.Unmarshal(m, b)
}
func (m *Uint64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uint64.Marshal(b, m, deterministic)
}
func (m *Uint64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uint64.Merge(m, src)
}
func (m *Uint64) XXX_Size() int {
	return xxx_messageInfo_Uint64.Size(m)
}
func (m *Uint64) XXX_DiscardUnknown() {
	xxx_messageInfo_Uint64.DiscardUnknown(m)
}

var xxx_messageInfo_Uint64 proto.InternalMessageInfo

func (m *Uint64) GetData() uint64 {
	if m != nil {
		return m.Data
	}
	return 0
}

type TokenStatics struct {
	TokenAddr            string   `protobuf:"bytes,1,opt,name=tokenAddr,proto3" json:"tokenAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenStatics) Reset()         { *m = TokenStatics{} }
func (m *TokenStatics) String() string { return proto.CompactTextString(m) }
func (*TokenStatics) ProtoMessage()    {}
func (*TokenStatics) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{30}
}

func (m *TokenStatics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenStatics.Unmarshal(m, b)
}
func (m *TokenStatics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenStatics.Marshal(b, m, deterministic)
}
func (m *TokenStatics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenStatics.Merge(m, src)
}
func (m *TokenStatics) XXX_Size() int {
	return xxx_messageInfo_TokenStatics.Size(m)
}
func (m *TokenStatics) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenStatics.DiscardUnknown(m)
}

var xxx_messageInfo_TokenStatics proto.InternalMessageInfo

func (m *TokenStatics) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

type EventLogIndex struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventLogIndex) Reset()         { *m = EventLogIndex{} }
func (m *EventLogIndex) String() string { return proto.CompactTextString(m) }
func (*EventLogIndex) ProtoMessage()    {}
func (*EventLogIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{31}
}

func (m *EventLogIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLogIndex.Unmarshal(m, b)
}
func (m *EventLogIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLogIndex.Marshal(b, m, deterministic)
}
func (m *EventLogIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLogIndex.Merge(m, src)
}
func (m *EventLogIndex) XXX_Size() int {
	return xxx_messageInfo_EventLogIndex.Size(m)
}
func (m *EventLogIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLogIndex.DiscardUnknown(m)
}

var xxx_messageInfo_EventLogIndex proto.InternalMessageInfo

func (m *EventLogIndex) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *EventLogIndex) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type EthTxStatus struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Txhash               string   `protobuf:"bytes,2,opt,name=txhash,proto3" json:"txhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EthTxStatus) Reset()         { *m = EthTxStatus{} }
func (m *EthTxStatus) String() string { return proto.CompactTextString(m) }
func (*EthTxStatus) ProtoMessage()    {}
func (*EthTxStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{32}
}

func (m *EthTxStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EthTxStatus.Unmarshal(m, b)
}
func (m *EthTxStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EthTxStatus.Marshal(b, m, deterministic)
}
func (m *EthTxStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthTxStatus.Merge(m, src)
}
func (m *EthTxStatus) XXX_Size() int {
	return xxx_messageInfo_EthTxStatus.Size(m)
}
func (m *EthTxStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EthTxStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EthTxStatus proto.InternalMessageInfo

func (m *EthTxStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EthTxStatus) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

type TokenAddress struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ChainName            string   `protobuf:"bytes,3,opt,name=chainName,proto3" json:"chainName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenAddress) Reset()         { *m = TokenAddress{} }
func (m *TokenAddress) String() string { return proto.CompactTextString(m) }
func (*TokenAddress) ProtoMessage()    {}
func (*TokenAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{33}
}

func (m *TokenAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenAddress.Unmarshal(m, b)
}
func (m *TokenAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenAddress.Marshal(b, m, deterministic)
}
func (m *TokenAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenAddress.Merge(m, src)
}
func (m *TokenAddress) XXX_Size() int {
	return xxx_messageInfo_TokenAddress.Size(m)
}
func (m *TokenAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenAddress.DiscardUnknown(m)
}

var xxx_messageInfo_TokenAddress proto.InternalMessageInfo

func (m *TokenAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TokenAddress) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenAddress) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

type TokenAddressArray struct {
	TokenAddress         []*TokenAddress `protobuf:"bytes,1,rep,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TokenAddressArray) Reset()         { *m = TokenAddressArray{} }
func (m *TokenAddressArray) String() string { return proto.CompactTextString(m) }
func (*TokenAddressArray) ProtoMessage()    {}
func (*TokenAddressArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{34}
}

func (m *TokenAddressArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenAddressArray.Unmarshal(m, b)
}
func (m *TokenAddressArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenAddressArray.Marshal(b, m, deterministic)
}
func (m *TokenAddressArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenAddressArray.Merge(m, src)
}
func (m *TokenAddressArray) XXX_Size() int {
	return xxx_messageInfo_TokenAddressArray.Size(m)
}
func (m *TokenAddressArray) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenAddressArray.DiscardUnknown(m)
}

var xxx_messageInfo_TokenAddressArray proto.InternalMessageInfo

func (m *TokenAddressArray) GetTokenAddress() []*TokenAddress {
	if m != nil {
		return m.TokenAddress
	}
	return nil
}

func init() {
	proto.RegisterType((*Account4Relayer)(nil), "types.Account4Relayer")
	proto.RegisterType((*ValidatorAddr4EthRelayer)(nil), "types.ValidatorAddr4EthRelayer")
	proto.RegisterType((*Txhashes)(nil), "types.Txhashes")
	proto.RegisterType((*ReqChangePasswd)(nil), "types.ReqChangePasswd")
	proto.RegisterType((*ReqSetPasswd)(nil), "types.ReqSetPasswd")
	proto.RegisterType((*Account4Show)(nil), "types.Account4Show")
	proto.RegisterType((*AssetType)(nil), "types.assetType")
	proto.RegisterType((*EthBridgeClaim)(nil), "types.EthBridgeClaim")
	proto.RegisterType((*ImportKeyReq)(nil), "types.ImportKeyReq")
	proto.RegisterType((*RelayerRunStatus)(nil), "types.RelayerRunStatus")
	proto.RegisterType((*NewProphecyClaim)(nil), "types.NewProphecyClaim")
	proto.RegisterType((*BalanceAddr)(nil), "types.BalanceAddr")
	proto.RegisterType((*MintToken)(nil), "types.MintToken")
	proto.RegisterType((*ApproveAllowance)(nil), "types.ApproveAllowance")
	proto.RegisterType((*LockEthErc20)(nil), "types.LockEthErc20")
	proto.RegisterType((*LockBTY)(nil), "types.LockBTY")
	proto.RegisterType((*ReplyAddr)(nil), "types.ReplyAddr")
	proto.RegisterType((*ReplyBalance)(nil), "types.ReplyBalance")
	proto.RegisterType((*Burn)(nil), "types.Burn")
	proto.RegisterType((*BurnFromChain33)(nil), "types.BurnFromChain33")
	proto.RegisterType((*StaticsRequest)(nil), "types.StaticsRequest")
	proto.RegisterType((*StaticsAll)(nil), "types.StaticsAll")
	proto.RegisterType((*StaticsSingle)(nil), "types.StaticsSingle")
	proto.RegisterType((*StaticsLockResponse)(nil), "types.StaticsLockResponse")
	proto.RegisterType((*StaticsResponse)(nil), "types.StaticsResponse")
	proto.RegisterType((*StaticsLock)(nil), "types.StaticsLock")
	proto.RegisterType((*StaticsDeposit)(nil), "types.StaticsDeposit")
	proto.RegisterType((*StaticsLockSingle)(nil), "types.StaticsLockSingle")
	proto.RegisterType((*TransferToken)(nil), "types.TransferToken")
	proto.RegisterType((*Uint64)(nil), "types.Uint64")
	proto.RegisterType((*TokenStatics)(nil), "types.TokenStatics")
	proto.RegisterType((*EventLogIndex)(nil), "types.EventLogIndex")
	proto.RegisterType((*EthTxStatus)(nil), "types.EthTxStatus")
	proto.RegisterType((*TokenAddress)(nil), "types.TokenAddress")
	proto.RegisterType((*TokenAddressArray)(nil), "types.TokenAddressArray")
}

func init() {
	proto.RegisterFile("relayer.proto", fileDescriptor_202a89775a80bd4c)
}

var fileDescriptor_202a89775a80bd4c = []byte{
	// 1100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x86, 0x7e, 0x6c, 0x47, 0x23, 0xc9, 0xb2, 0x99, 0xa0, 0x20, 0x8a, 0xa0, 0x10, 0x16, 0x41,
	0x2b, 0x04, 0x85, 0x11, 0x58, 0x46, 0x7b, 0x49, 0x50, 0xc8, 0xb6, 0x82, 0x1a, 0x76, 0xd3, 0x60,
	0xad, 0xb6, 0xc8, 0xa5, 0xc1, 0x9a, 0x9c, 0x88, 0x84, 0x29, 0x2e, 0xbd, 0xbb, 0xb2, 0xac, 0x6b,
	0x8f, 0xbd, 0xf4, 0x0d, 0xfb, 0x0c, 0x7d, 0x84, 0x62, 0x7f, 0x28, 0x91, 0xb4, 0xea, 0x83, 0xd1,
	0xa2, 0xb7, 0xfd, 0xbe, 0x1d, 0xce, 0x7c, 0x9c, 0x99, 0x9d, 0x5d, 0xe8, 0x0a, 0x4c, 0xd8, 0x12,
	0xc5, 0x41, 0x26, 0xb8, 0xe2, 0xde, 0x96, 0x5a, 0x66, 0x28, 0xc9, 0x77, 0xd0, 0x1b, 0x05, 0x01,
	0x9f, 0xa7, 0xea, 0x88, 0xda, 0x7d, 0xcf, 0x87, 0x9d, 0x4c, 0xc4, 0xb7, 0xd7, 0xb8, 0xf4, 0x6b,
	0xfd, 0xda, 0xa0, 0x43, 0x73, 0xe8, 0x79, 0xd0, 0x64, 0x61, 0x28, 0xfc, 0x7a, 0xbf, 0x36, 0x68,
	0x51, 0xb3, 0x26, 0x6f, 0xc1, 0xff, 0x99, 0x25, 0x71, 0xc8, 0x14, 0x17, 0xa3, 0x30, 0x14, 0x47,
	0x63, 0x15, 0xe5, 0x9e, 0x5e, 0xc2, 0x5e, 0x10, 0xb1, 0x38, 0x1d, 0x0e, 0x57, 0x26, 0xc6, 0x65,
	0x8b, 0xde, 0xe3, 0x09, 0x81, 0x27, 0x93, 0xbb, 0x88, 0xc9, 0x08, 0xa5, 0xf7, 0x19, 0x6c, 0x2b,
	0xb3, 0xf6, 0x6b, 0xfd, 0xc6, 0xa0, 0x45, 0x1d, 0x22, 0x1f, 0xa0, 0x47, 0xf1, 0xe6, 0x24, 0x62,
	0xe9, 0x14, 0xdf, 0x33, 0x29, 0x17, 0xa1, 0x47, 0xa0, 0xc3, 0x93, 0x50, 0x83, 0x2c, 0x62, 0x12,
	0x9d, 0xfb, 0x12, 0xa7, 0x6d, 0x52, 0x5c, 0xac, 0x6d, 0xac, 0xfc, 0x12, 0x47, 0xbe, 0x86, 0x0e,
	0xc5, 0x9b, 0x4b, 0x54, 0xce, 0xef, 0x73, 0x68, 0x55, 0x9d, 0xae, 0x09, 0xf2, 0x1a, 0x3a, 0x79,
	0xd6, 0x2e, 0x23, 0xbe, 0xa8, 0xa6, 0xac, 0xf5, 0x70, 0xca, 0x3e, 0x42, 0x8b, 0x49, 0x89, 0x6a,
	0xb2, 0xcc, 0xd0, 0x7b, 0x06, 0x5b, 0x26, 0x17, 0xee, 0x43, 0x0b, 0xbc, 0x17, 0xd0, 0x8d, 0xa5,
	0x9c, 0xe3, 0x09, 0x4f, 0x95, 0x60, 0x81, 0x72, 0xdf, 0x97, 0x49, 0x9d, 0x27, 0xb9, 0x9c, 0x5d,
	0xf1, 0xc4, 0x6f, 0x98, 0x6d, 0x87, 0xc8, 0x5f, 0x75, 0xd8, 0x1d, 0xab, 0xe8, 0x58, 0xc4, 0xe1,
	0x14, 0x4f, 0x12, 0x16, 0xcf, 0xbc, 0x01, 0xf4, 0x50, 0x45, 0x28, 0x70, 0x3e, 0x3b, 0xd1, 0x11,
	0xce, 0x4e, 0x4d, 0xc0, 0x06, 0xad, 0xd2, 0xda, 0xf2, 0xca, 0x7c, 0x78, 0x2c, 0x58, 0x7a, 0x3d,
	0x5a, 0x8b, 0xaf, 0xd2, 0x5a, 0x7a, 0xca, 0xd3, 0x00, 0x4d, 0xf4, 0x06, 0xb5, 0x40, 0x67, 0x4e,
	0xf1, 0x6b, 0x4c, 0xcd, 0x97, 0x4d, 0x9b, 0xb9, 0x15, 0x51, 0x90, 0xbc, 0x55, 0x94, 0xec, 0x7d,
	0x09, 0xbb, 0xb9, 0x90, 0x4b, 0x4c, 0x43, 0x14, 0xfe, 0xb6, 0xd9, 0xaf, 0xb0, 0x5a, 0x9d, 0x6b,
	0x1d, 0x8a, 0x01, 0xc6, 0xb7, 0x28, 0xfc, 0x1d, 0xab, 0xae, 0x42, 0xeb, 0x48, 0x6c, 0xa6, 0x4b,
	0xe4, 0xb7, 0x8c, 0x3c, 0x87, 0xb4, 0xbe, 0x40, 0xa7, 0x44, 0x67, 0xdf, 0x87, 0x7e, 0x6d, 0xb0,
	0x45, 0xd7, 0x84, 0xd9, 0xd5, 0x8e, 0xde, 0xb1, 0x19, 0xfa, 0x6d, 0xab, 0x7e, 0x45, 0xe8, 0x3a,
	0x87, 0x18, 0xc4, 0x33, 0x96, 0xf8, 0x1d, 0xe3, 0x34, 0x87, 0xe4, 0x00, 0x3a, 0x67, 0xb3, 0x8c,
	0x0b, 0x75, 0x8e, 0x4b, 0x8a, 0x37, 0xde, 0x17, 0x00, 0xba, 0x05, 0x98, 0xc2, 0xf3, 0x55, 0x53,
	0x14, 0x18, 0x72, 0x0a, 0x7b, 0xee, 0x94, 0xd0, 0x79, 0x7a, 0xa9, 0x98, 0x9a, 0x9b, 0xb6, 0x97,
	0x66, 0x65, 0xec, 0xb7, 0xa8, 0x43, 0x36, 0xaa, 0x62, 0x71, 0x22, 0x5d, 0x25, 0x72, 0x48, 0xfe,
	0xac, 0xc1, 0xde, 0x3b, 0x5c, 0xbc, 0x17, 0x3c, 0x8b, 0x30, 0x58, 0xda, 0x52, 0x97, 0x7e, 0x50,
	0x7b, 0xea, 0x16, 0x7f, 0xf0, 0x05, 0x74, 0x5d, 0xa6, 0x5c, 0x9e, 0x5d, 0x67, 0x95, 0xc8, 0x72,
	0x11, 0x1b, 0xff, 0x5c, 0xc4, 0x66, 0xa9, 0x88, 0x7d, 0x68, 0xa3, 0x3e, 0xfd, 0xae, 0x30, 0xb6,
	0xc2, 0x45, 0xaa, 0x50, 0x14, 0x5b, 0xde, 0xbc, 0x28, 0xe6, 0xc4, 0x7f, 0xaf, 0x4f, 0xbc, 0xad,
	0xa6, 0x43, 0x64, 0x04, 0xed, 0x63, 0x96, 0xb0, 0x34, 0xc0, 0xbc, 0xe3, 0xf8, 0x22, 0xc5, 0x7c,
	0x8a, 0x58, 0x50, 0x16, 0x5b, 0xaf, 0x88, 0x25, 0xbf, 0x40, 0xeb, 0x87, 0x38, 0x55, 0x13, 0x4d,
	0x3c, 0xc6, 0x41, 0x41, 0x73, 0xa3, 0xa8, 0x99, 0x84, 0xb0, 0x37, 0xca, 0x32, 0xc1, 0x6f, 0x71,
	0x94, 0x24, 0x7c, 0xa1, 0x45, 0x7a, 0x9f, 0xc3, 0x13, 0xe3, 0x72, 0x5d, 0xf4, 0x15, 0x7e, 0x64,
	0x94, 0xdf, 0x6b, 0xd0, 0xb9, 0xe0, 0xc1, 0xf5, 0x58, 0x45, 0x63, 0x11, 0x1c, 0xbe, 0xfa, 0xf7,
	0x43, 0x6c, 0x3a, 0x53, 0xcd, 0x8d, 0x67, 0x8a, 0x4c, 0x61, 0x47, 0x6b, 0x39, 0x9e, 0x7c, 0x78,
	0x50, 0xc6, 0x3a, 0x50, 0xbd, 0x1a, 0xc8, 0x1c, 0xe7, 0xf9, 0x6c, 0x15, 0xc8, 0x2a, 0xa9, 0xd2,
	0x64, 0x08, 0x2d, 0x8a, 0x59, 0xb2, 0x34, 0xba, 0x3d, 0x68, 0xc6, 0xf2, 0xc7, 0x73, 0x13, 0xe6,
	0x09, 0x35, 0xeb, 0x8d, 0x73, 0xf5, 0xb5, 0x9e, 0xe1, 0x59, 0xb2, 0x74, 0x1d, 0xb3, 0xf1, 0x3b,
	0x1f, 0x76, 0xae, 0xec, 0x76, 0x7e, 0x96, 0x1c, 0x24, 0xbf, 0xd5, 0xa0, 0x79, 0x3c, 0x17, 0xe9,
	0xff, 0x9a, 0xe0, 0x3f, 0x6a, 0xd0, 0xd3, 0x22, 0xde, 0x0a, 0x6e, 0x07, 0xf2, 0x70, 0xf8, 0x1f,
	0xe8, 0x79, 0x09, 0x7b, 0xf9, 0x58, 0xad, 0x08, 0xba, 0xc7, 0x93, 0x53, 0xd8, 0xd5, 0xe3, 0x29,
	0x0e, 0x24, 0xc5, 0x9b, 0x39, 0x4a, 0xf5, 0xa8, 0x43, 0xd8, 0x01, 0x70, 0x5e, 0x46, 0x49, 0x42,
	0x7a, 0xd0, 0x75, 0xe8, 0x32, 0x4e, 0xa7, 0x09, 0x92, 0x19, 0x3c, 0x75, 0x84, 0x6e, 0x2f, 0x8a,
	0x32, 0xe3, 0xa9, 0xd4, 0xb3, 0xaa, 0xc1, 0x92, 0xc4, 0xc4, 0x69, 0x1f, 0x7a, 0x07, 0xe6, 0xc5,
	0x72, 0x50, 0x34, 0xd4, 0xdb, 0xde, 0x2b, 0xd8, 0x96, 0xc6, 0x8d, 0x09, 0xdb, 0x3e, 0xf4, 0xef,
	0x1b, 0xda, 0x30, 0xd4, 0xd9, 0x91, 0x7d, 0xe8, 0xad, 0xfe, 0xc9, 0x86, 0x22, 0x5f, 0x41, 0xbb,
	0x60, 0x5f, 0x6c, 0x93, 0x5a, 0xb9, 0x4d, 0x06, 0xab, 0x7c, 0x9c, 0x62, 0xc6, 0x65, 0x6c, 0x6f,
	0xe1, 0x79, 0x96, 0x25, 0x79, 0x75, 0x1c, 0x22, 0x1f, 0x61, 0xff, 0x9e, 0x04, 0xef, 0x10, 0x9e,
	0x29, 0xae, 0x58, 0xa2, 0x29, 0x0c, 0x47, 0x41, 0x30, 0x9f, 0x31, 0x85, 0xa1, 0xbb, 0x8c, 0x37,
	0xee, 0xe9, 0x00, 0x89, 0xa1, 0xfc, 0x7a, 0xbf, 0xa1, 0x6f, 0x32, 0x8b, 0xc8, 0x02, 0xba, 0x13,
	0xc1, 0x52, 0xf9, 0x09, 0x85, 0x9d, 0x6e, 0xa5, 0x1a, 0xd4, 0xaa, 0xdd, 0xe0, 0xc3, 0xce, 0x27,
	0xc1, 0x67, 0xba, 0x8d, 0x5c, 0xeb, 0x3b, 0x68, 0xa6, 0x2f, 0x2f, 0x8c, 0x7a, 0x87, 0x0a, 0xfd,
	0xd3, 0x2c, 0xcd, 0xa4, 0xe7, 0xb0, 0xfd, 0x53, 0x9c, 0xaa, 0x6f, 0x8e, 0xf4, 0x11, 0x0b, 0x99,
	0x62, 0x26, 0x58, 0x93, 0x9a, 0xb5, 0x7e, 0x4a, 0x19, 0x39, 0xee, 0xe7, 0x1f, 0x56, 0x45, 0xde,
	0x40, 0x77, 0x7c, 0x8b, 0xa9, 0xba, 0xe0, 0xd3, 0xb3, 0x34, 0xc4, 0x3b, 0x1d, 0x34, 0xc2, 0x78,
	0x1a, 0x29, 0xe7, 0xd4, 0x21, 0xdd, 0x76, 0xb1, 0x36, 0x30, 0xe2, 0xbb, 0xd4, 0x02, 0xf2, 0x06,
	0xda, 0x63, 0x15, 0x4d, 0xee, 0x36, 0x5e, 0xa1, 0xad, 0xd5, 0x15, 0xba, 0x7e, 0x51, 0xd6, 0xf3,
	0xfb, 0xc5, 0xbc, 0x28, 0x7f, 0x75, 0x5a, 0xb5, 0x14, 0x94, 0xe6, 0xaa, 0x65, 0x76, 0x99, 0xd7,
	0xdd, 0xc1, 0xc2, 0x9d, 0x57, 0x2f, 0xdd, 0x79, 0xa5, 0x07, 0x43, 0xa3, 0xf2, 0x60, 0x20, 0x17,
	0xb0, 0x5f, 0xf4, 0x3f, 0x12, 0x82, 0x2d, 0xbd, 0x6f, 0xa1, 0xa3, 0x0a, 0xa4, 0x79, 0xe4, 0xb6,
	0x0f, 0x9f, 0xba, 0xb6, 0x2d, 0xda, 0xd3, 0x92, 0xe1, 0xd5, 0xb6, 0x79, 0xba, 0x0f, 0xff, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x28, 0x97, 0x98, 0xce, 0xcb, 0x0b, 0x00, 0x00,
}
